### ISSUE TITLE
The timestamp of the self-messages are invalid

### ISSUE THREAD

**Issue by fangfufu** [jgeboski/purple-facebook#101]
Self-messaging works. That's great, thanks a lot!

One small problem is that the timestamp for the self-messages are set to ``(01/01/70 01:00:00) ``, it is slightly confusing.

**Comment by dequis** [comment]
Duplicate of #97, which has been fixed as of [02346252cb7e](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/02346252cb7e), and will appear in the next release.
