### ISSUE TITLE
libfacebook.dll is reported by Norton Corporate AV as malicious

### ISSUE THREAD

**Issue by wacko69** [jgeboski/purple-facebook#102]
Norton Corporate reports this file as WS.Reputation.1 - There is strong evidence that this file is untrustworthy. and then removes the file.  

I went to http://community.norton.com/forums/clarification-wsreputation1-detection and read about why Norton was flagging this file.  They have a link to submit a dispute, but the link doesn't work.  

I guess this isn't a bug with the library, but more of an alarm to users with anti-virus trying to use this library and possibly thinking it's malicious.

**Comment by jgeboski** [comment]
Feel free to whitelist it somehow, but I have absolutely no interest in pleasing dysfunctional software.
