### ISSUE TITLE
Messages seen by friends

### ISSUE THREAD

**Issue by ZyperPL** [jgeboski/purple-facebook#103]
Is it possible to print an information whether our sended message was read or not?
That's only reason why I'm logging into Facebook in browser.

**Comment by marsjaninzmarsa** [comment]
Not in current version of purple, in version 3 - maybe.

19:44 czw., 13.08.2015 Kacper Zybała użytkownik <notifications@github.com>
napisał:

**Comment by dequis** [comment]
Yeah, what @marsjaninzmarsa said. No support for this on the pidgin/libpurple side. Sorry!

Libpurple 3 (which is still in development and doesn't look like it will be released soon) doesn't have this feature either, at least not yet, but you could request it in their [issue tracker](https://developer.pidgin.im/query)
