### ISSUE TITLE
Feature request: Display pictures and stickers in conversation window, not just URL.

### ISSUE THREAD

**Issue by zeevro** [jgeboski/purple-facebook#105]
Is this possible? If I remember correctly, it was on the TODO ticket.
If it's possible it'll be awesome!
P.S.: Even now, this is the best Pidgin plugin I have ever seen. Amazing work.

**Comment by jgeboski** [comment]
I meant to do this from the start, but the TODO list was a mile long, and the idea got lost somewhere.  Anyways, yes, this will happen.

**Comment by zeevro** [comment]
I wonder if something can be done with voice clips. Does pidgin even support sound clips in conversations?

**Comment by marsjaninzmarsa** [comment]
Pidgin support attachments, and if plugin can just save voice file to disk and display local link to it, it should be enough.
And in Pidgin 3.0 it can be done via `<audio>` tag, I'm right?

**Comment by fullinterest** [comment]
But, Pidgin 3... it will come a day? ^^

**Comment by marsjaninzmarsa** [comment]
Not really. :x

**Comment by fullinterest** [comment]
The development of Pidgin is still active?

**Comment by dequis** [comment]
No offtopic please!

**Comment by fullinterest** [comment]
Sorry about it

**Comment by jgeboski** [comment]
This has been implemented as of [d8e50d403e82](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/d8e50d403e82) and [ebcd09a1a124](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/ebcd09a1a124), and will appear in the next release.
