### ISSUE TITLE
Messages sent from other devices show with incorrect timestamp in message log.

### ISSUE THREAD

**Issue by aph3rson** [jgeboski/purple-facebook#106]
For example, here's what I see:

1. Open up new chat window with Facebook friend.  
2. Send message from other device (Android phone, specifically).  
3. Looking at Pidgin's chat window, an invalid timestamp is attached to the message that I just sent (12/31/1969, you know, that one).

**Comment by jgeboski** [comment]
This has already been fixed in the latest version.
