### ISSUE TITLE
Smileys in timestamp

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#108]
I recently updated purple-facebook from AUR. I now have smileys in my timestamp. For example, if the time is
12:30:33 the :3 becomes a smiley.

Is this a purple-facebook bug or a pidgin bug?

**Comment by Smile4ever** [comment]
It's a bug in the history plugin of Pidgin.

**Comment by jgeboski** [comment]
Yeah, I was about to say, the plugin has absolutely no control over this.
