### ISSUE TITLE
Facebook video link received twice

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#109]
If someone sends me a Facebook video, I get this as a message:
https://www.facebook.com/video.php?v=10153405285476754
http://www.facebook.com/video.php?v=10153405285476754

Both https and http links. Only one is enough, thank you.

**Comment by dequis** [comment]
This is because right after pasting the first url, the server adds another message with a playable video.

![](http://dump.dequis.org/mi4nc.png)

Not much we can do with this one, other than maybe making it part of #105 (to show the thumbnail in the conversation window)

**Comment by jgeboski** [comment]
Actually, it looks like we get a link to the URL of the MP4.

**Comment by jgeboski** [comment]
I am just going to fix the HTTP/S issue, however.

**Comment by jgeboski** [comment]
This has been fixed as of (14857ad5b6b7)[https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/14857ad5b6b7], and will appear in the next release.

**Comment by marsjaninzmarsa** [comment]
Now (at least in version `20150821~c9cbfbd~5727ffb502c7~14`) I'm not getting even single link if link is sent alone in message.

**Comment by dequis** [comment]
@marsjaninzmarsa See [this FAQ entry](https://github.com/jgeboski/purple-facebook/wiki#after-upgrading-the-plugin-some-features-that-should-work-like-image-thumbnails-seem-to-be-broken)

**Comment by marsjaninzmarsa** [comment]
@dequis ehh, after removing and re-adding account everything works.
PS: You should think about something without lose of logs and contacts/group info...

**Comment by jgeboski** [comment]
The plugin is still in development.  Once there is a stable release, yes.

**Comment by Smile4ever** [comment]
(18:44:29) name: https://www.youtube.com/watch?v=JDt1e7r820o you should watch this
(18:44:29) name: https://www.youtube.com/watch?v=JDt1e7r820o

The video link is still displayed twice if you add a comment to the link.
