### ISSUE TITLE
Contacts appear offline

### ISSUE THREAD

**Issue by bertenvdb** [jgeboski/purple-facebook#110]
All my FB contacts appear offline in pidgin, while facebook.com shows that they're actually online.

Am I the only one experiencing this issue?

**Comment by marsjaninzmarsa** [comment]
Have you newest version of plugin?
Have you tried turning it off and on again (and removing account and adding it again)?

**Comment by bertenvdb** [comment]
Removing the Facebook accounts and adding them again seems to work. Thanks!

FYI:
Perhaps I should have mentioned I have 2 Facebook account. Don't know wheter that's relevant.
So, I removed both my Facebook accounts and added them again. Everything OK now.

    apt-cache showpkg purple-facebook 
        Package: purple-facebook
        Versions: 
        20150815~8c708bb~dd1528f03f59~10
