### ISSUE TITLE
Connect OK but give "Unknown HTTP error" on few second after loggedin

### ISSUE THREAD

**Issue by reidsneo** [jgeboski/purple-facebook#112]
Hello first I having issue with empy JSON data, but now after update it give Unknown HTTP error a few second after logged in in pidgin
PS : I not using proxy just default network connection

I tried running this on terminal 
curl -I https://graph.facebook.com

HTTP/1.1 400 Bad Request
WWW-Authenticate: OAuth "Facebook Platform" "invalid_request" "Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api"
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
X-FB-Trace-ID: E2lJdiYw9JA
X-FB-Rev: 1890979
Pragma: no-cache
Cache-Control: no-store
Facebook-API-Version: v2.0
Expires: Sat, 01 Jan 2000 00:00:00 GMT
X-FB-Debug: GbHwcmfEhnDX5yoHPJ8E4n1P7zQKM2YFHVuPVvOfEeZVXfWx61A21UgR8BVp6/XpYsfcDn2pUvEu+IpfEv8lFQ==
Date: Wed, 19 Aug 2015 05:15:15 GMT
Connection: keep-alive
Content-Length: 0

**Comment by dequis** [comment]
Send jgeboski a [debug log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs)

Also that curl output looks okay.

**Comment by reidsneo** [comment]
@jgeboski @dequis 
here my log https://mega.nz/#!dpp3lCpT!eRT0Gk3AEVydrOUW8yLWjMe6bMDPuXphsJxXAcyl_ds

**Comment by dequis** [comment]
Please don't post debug logs publicly. As written in the page linked above:

>Please note, these logs often contain sensitive data, and are likely not ideal for posting to the issue tracker, public pastebins, or anywhere else. If a log has has been request from you, it is preferred you email it directly to the developer, jgeboski@gmail.com, to prevent from publicly displaying the log

Also, change your password.

**Comment by reidsneo** [comment]
Oh nevermind it just a facebook account ;)
Thank you for pointing me out

**Comment by jgeboski** [comment]
I have addressed two other issues from your log: [1cbcea2165c1](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/1cbcea2165c1) and [ed868baac87d](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/ed868baac87d).  I am still investigating the cause of a null contact fetch.

**Comment by jgeboski** [comment]
If you go on the Facebook website, and mark all messages as read, does this still occur?

**Comment by reidsneo** [comment]
OMG it solved!
I have thousand message that I not read before, then after mark is as read, the HTTP ERROR didn't occured again
Thank You! it solved

**Comment by jgeboski** [comment]
It looks like the account the unread message was from might have been deactivated or something.

**Comment by reidsneo** [comment]
Yeah.... plenty of message I cannot check it 1 by 1, some of them I've blocked from my account
Again thank you, now it work fully :D

**Comment by Damme** [comment]
Got this error then I had an -
"Attachment Unavailable
This attachment may have been ..."

I had to mark it as read and I stopped getting disconnected

I'll send log to  jgeboski@gmail.com
