### ISSUE TITLE
Facebook IDs are used as Pidgin room names

### ISSUE THREAD

**Issue by zeevro** [jgeboski/purple-facebook#115]
Real group names are used as the room topic

**Comment by dequis** [comment]
Does the room have a topic, or does it just show the list of participants in the title bar of the webchat? I'm pretty sure manually-set topics are supported.

**Comment by jgeboski** [comment]
Every entity (user, thread, etc) is represented by a 64-bit Facebook identifier.  As a result, chats are identified in libpurple with these identifiers.  The plugin has no control over this.  If you do not like it, add the chat and rename it.
