### ISSUE TITLE
Automatically disconnected almost immediately upon logging in.

### ISSUE THREAD

**Issue by 35Nick35** [jgeboski/purple-facebook#116]
Error message displayed is: No matches for $.story_attachment.target.__type__.name

![pidgin](https://cloud.githubusercontent.com/assets/4649836/9363839/959ef708-465d-11e5-8872-311911c6e17c.png)

**Comment by jgeboski** [comment]
Send me a [debugging log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs).

**Comment by 35Nick35** [comment]
I got pissed off and just reinstalled it, and now it works fine.

Date: Wed, 19 Aug 2015 11:25:23 -0700

**Comment by dequis** [comment]
...okay
