### ISSUE TITLE
received messages immediately marked as read

### ISSUE THREAD

**Issue by danielb2** [jgeboski/purple-facebook#117]
Several of my facebook friends have noticed this: as soon as they've sent me  a message, it's marked as read whether I'm there or not.  People end up thinking I'm ignoring them. 

I'm using finch together with the plugin.

**Comment by danielb2** [comment]
never mind, found an option in account settings

**Comment by danielb2** [comment]
Actually, can't the plugin detect which window I've made active and mark messages read based on that instead? or do all of them have to be marked read instantly?

**Comment by danielb2** [comment]
Right now it doesn't even mark as read _after_ I've typed, with the read setting off. And before it was reading everything. Seems like a happy medium would be nice

**Comment by jgeboski** [comment]
Duplicate of #80.  Update the plugin.

**Comment by danielb2** [comment]
These are not the same tickets. You have to read carefully to see that.

**Comment by danielb2** [comment]
@jgeboski

**Comment by danielb2** [comment]
but anyway, I'll open another ticket regarding the other behavior

**Comment by danielb2** [comment]
https://github.com/jgeboski/purple-facebook/issues/118
