### ISSUE TITLE
messages responded to should be marked as read

### ISSUE THREAD

**Issue by danielb2** [jgeboski/purple-facebook#118]
If I have "mark messages as read" option as off, then at least the messages I respond to should be marked as read.

Currently I respond to a message, and not even then does the message get marked as seen.

**Comment by jgeboski** [comment]
Please enlighten me on this "mark messages as seen" option.  Where does this option reside in the plugin?  I mean, the plugin has a "mark message as *read*" option, but nothing more.

Are you trying to mark messages as read, without marking them as seen?  If so, that is likely not going to happen.  This plugin marks messages as read over the Messenger protocol, which is automatically marking them as seen.  I can only assume the Facebook and Messenger websites operate in the same manner, though I have not tested this theory.

Also, it would be nice, if when you opened an issue, you explained yourself and elaborated a bit.  This is the *second* ticket in a row, where your ambiguity has been quite excessive.  Also, there is no need to spam this issue with fragmented responses, like the last one.

**Comment by danielb2** [comment]
I've changed the "seen" to "read".   Is it still ambiguous? 

Do you want to talk about what happened in the last ticket, or should we stay focused?   I can justify it if you want.


* Steps to reproduce *
1. Uncheck "Mark messages as read" in account options.
1. A friend sends you a message.
1. respond to message

* Expected result *

All messages received prior to response are marked as `read`

* Actual result *

Messages prior to response are still in `unread` state

**Comment by szr8** [comment]
@danielb2 If you have "Mark messages as read" turned /off/ (unchecked), then it would logically not mark any messages as read. If you want messages to be marked as read, then turn on "Mark messages as read" (so it's checked.)

I do understand that you are referring to messages that came before, but that doesn't change the fact that you're asking the plugin to /not/ mark messages as read, so the plugin is just behaving as instructed.

**Comment by danielb2** [comment]
@szr8 

If I check the box, then it immediately marks all messages as read, and then people mistakenly think I'm present reading what they write, causing frustration when I'm not responding.

What I'm trying to suggest is a middle ground that makes sense. And not marking them read after a response does not make sense.   I _must_ have read them if I'm responding.

**Comment by danielb2** [comment]
If that means adding a new checkbox, or altering it, or something, let's do that, but the current behavior doesn't make sense.

**Comment by zeevro** [comment]
This issue has been fixed (about a week or two ago) so messages are only marked as read if the conversation is focused. Update your plugin.

**Comment by marsjaninzmarsa** [comment]
I think that responded messages should be marked as read independent of option to marking as read on focus.

**Comment by danielb2** [comment]
Thanks @zeevro

**Comment by danielb2** [comment]
@marsjaninzmarsa agreed

**Comment by jgeboski** [comment]
Other people see differently, see #80.

**Comment by marsjaninzmarsa** [comment]
@jgeboski seen. And where is the difference in #80?

I see two cases:
1. You have checked "Mark messages as read" → messages are marked as read after focusing message (this is current behavior :+1:)
2. You have unchecked that box → messages are still marked as read, but only when you respond to it.

Or you can (can?) add second box and split this two marking as read strategies...

**Comment by danielb2** [comment]
I like the distinction @marsjaninzmarsa  brings up. I would prefer that over the current alternatives

**Comment by pekarja5** [comment]
@marsjaninzmarsa 
I see third case: 
You have unchecked the box (disabled the feature), because your client is just automated bot which replies in all situations -> You still want to recieve all unread (but answered) messages on your other client.

So that option not to mark messages at all might be also useful.

**Comment by danielb2** [comment]
@pekarja5   I think bots would be a case that should be secondary to common use by actual present users.  But sure, another option could be there just for bots ....

**Comment by marsjaninzmarsa** [comment]
@pekarja5 
> Or you can (can?) add second box and split this two marking as read strategies...

That's what I'm talking about. :smiley:

**Comment by pekarja5** [comment]
@danielb2 This option is already there -> Leaving the box unchecked. I just want it to preserve the way it is. So marking on response should be 3rd strategy.

**Comment by cipri-tom** [comment]
I support @marsjaninzmarsa 's [suggestion](https://github.com/jgeboski/purple-facebook/issues/118#issuecomment-133899977). This used to be the behaviour of the old client before facebook revoked access: messages were marked as read on reply only.

**Comment by jgeboski** [comment]
Closed in favor of #221.
