### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by fullinterest** [jgeboski/purple-facebook#120]
Could it be possible to show when there's notifications on facebook, using the mail function for example?

**Comment by dequis** [comment]
Sorry, not possible.

https://github.com/jgeboski/purple-facebook/issues/9#issuecomment-128165323

>Removed "Facebook notifications" as they are not sent over the Messenger stream

**Comment by Xylemon** [comment]
What about the fact there is a personal RSS feed for Facebook notifications? Could they perhaps be read the same way Pidgin gives new mail notifications?

**Comment by jgeboski** [comment]
If notifications came over the MQTT stream, this feature would be implemented.  But I really have no interest in bloating the plugin with a ton of code for something so trivial.  At the end of the day, this is a messaging client, not a Facebook client.

**Comment by Xylemon** [comment]
Well other messaging clients have this feature and so did a previous Facebook plugin, but if that's how you feel then so be it.

**Comment by dequis** [comment]
If by "previous facebook plugin" you mean the one that worked by html scraping the website (and which i believe stopped working years ago), well, that one was already doing awful stuff so it was easy to just go to the notifications page.

We don't even have access to the website with our auth tokens, so even if we really wanted to do things the awful way, we can't.

That also means we can't get the url for that RSS feed unless we ask the user to go to that page and copypaste it, but at that point it should be obvious it's completely unrelated to what this plugin does, and you should just use a libpurple plugin that reads RSS feeds instead.
