### ISSUE TITLE
Detached from group chat when offline with message saying about auto reattaching when reconnect, but no reattach.

### ISSUE THREAD

**Issue by marsjaninzmarsa** [jgeboski/purple-facebook#123]
And no reattach until I close chat window, even on new messages.

**Comment by jgeboski** [comment]
Did you add the chat and have it autojoin?

**Comment by marsjaninzmarsa** [comment]
Nope, chat was opened when someone added it to me. Manually adding chat to contacts may be a workaround, but not a solution.

**Comment by marsjaninzmarsa** [comment]
Adding chat and setting autojoin not solved the problem.

**Comment by jgeboski** [comment]
Please provide me steps to recreate.

**Comment by marsjaninzmarsa** [comment]
1. Log in
2. Get message on group conversation
3. Everything is ok
4. Get connection lost (sleep computer/go offline and online/turn WiFi off and on again)
5. Problem: you are detached from open conversation and you have no way to solve it different than get another message in conversation

**Comment by marsjaninzmarsa** [comment]
Ok, when I close chat window (and have unchecked "Persistant" or whatever is translation to "Trwałe") and open it again it works.

**Comment by jgeboski** [comment]
This has been resolved as of [2a83ef0](https://bitbucket.org/pidgin/main/commits/2a83ef0aed865b68e4412bfd7ec27854bea694bd) and will appear in the next release.
