### ISSUE TITLE
Broken compatibility with Password Keyring plugin

### ISSUE THREAD

**Issue by marsjaninzmarsa** [jgeboski/purple-facebook#124]
I don't like plaintext passwords on my disk, so I use Password Keyring plugin, but purple-facebook don't like it - password is not saved in keyring and I must rewrite it on every reconnect to network.

**Comment by dequis** [comment]
What password keyring plugin? Can you link to the source / where you got it from?

There was a similar issue, #48, with [pidgin-gnome-keyring](https://github.com/aebrahim/pidgin-gnome-keyring), and we concluded it's a bug in that plugin, which also affects other prpls.

**Comment by marsjaninzmarsa** [comment]
@dequis yeah, the same plugin, seems like duplicate (I missed it because is marked as resolved).
