### ISSUE TITLE
error: Package requirements (json-glib-1.0 >= 0.14.0) were not met:

### ISSUE THREAD

**Issue by elecu** [jgeboski/purple-facebook#125]
Hi, may you help me please? I use Fedora 22 and I have json-glib-1.0.4-1.fc22.i686 but purple-facebook needs json-glib-0.14.0-1.fc16.i686 that is older. What I should to do?

Thank you bro!

**Comment by jgeboski** [comment]
Install `json-glib-devel`.

**Comment by elecu** [comment]
I tried understand months ago haha and now it works!
Thank you so much!
