### ISSUE TITLE
FB disconnecting/reconnecting

### ISSUE THREAD

**Issue by khohmann** [jgeboski/purple-facebook#128]
1. Downloaded and installing the dll's per the instructions.
2. Restarted pidgin
3. Changed the account parameters per the instructions

As I'm observing, the account connects, I see a full display of a buddy list that corresponds to the FB account, and then a disconnect occurs with the error: "No matches for $.structured_name.text"
I've tried replacing the username field with username and email address - both lead to the same symptom. A few minutes later, pidgin attempts a reconnect and the cycle starts all over. Any thoughts or ideas would be much appreciated!

**Comment by khohmann** [comment]
This may have been an issue on Facebook's end - it seems to have resolved itself.

**Comment by jgeboski** [comment]
This is likely a duplicate of #121.  While I have yet to update this, what probably happened is that you marked the chat(s) as read.
