### ISSUE TITLE
Muting a group chat in Facebook doesn't mute it in Pidgin

### ISSUE THREAD

**Issue by rrthomas** [jgeboski/purple-facebook#129]
As far as I can tell, muting a group chat in Facebook has no effect in Pidgin.

[This plugin has gotten amazing good in an astonishingly short time; I don't remember anything like it in Pidgin's storied history. Mega props.]

**Comment by marsjaninzmarsa** [comment]
+1, amazing work @jgeboski!

**Comment by dequis** [comment]
Duplicate of #76, which was closed because https://github.com/jgeboski/purple-facebook/issues/76#issuecomment-129710666

That issue also mentions alternatives that are equivalent to muting group chats that can be done on the pidgin side.

**Comment by rrthomas** [comment]
Thanks for the pointer, and apologies for filing a duplicate.
