### ISSUE TITLE
Messages sent from other devices will open new window/tab

### ISSUE THREAD

**Issue by aph3rson** [jgeboski/purple-facebook#131]
More of a feature request/enhancement than anything else, but still:

Consider the following:

1. I want to send a Facebook friend a message, but I'm using a program which inhibits the usage of Pidgin (e.g. fullscreen game, etc.)
2. I send a message to a Facebook friend, from another device (phone, web, etc.)
3. My main instance of Pidgin, running on my computer, opens a window with the conversation in it.

Would it be possible to only open a window on a new conversation, if the other party started it? Or, perhaps make it an option in the accounts panel?

**Comment by dequis** [comment]
Uhm, even if it didn't open the window with your own message, it will open it when the other person replies. I don't think that is a great plan.

You could just use "hide new IM conversations when away", from the pidgin preferences.

**Comment by felagund** [comment]
Well, but sometimes they never reply or reply only much later and the opened window must be either closed anyway. I too would prefer if a new window would open on incoming conversation only (ideally, my message would be logged and would appear above the new message for context).

**Comment by random6969** [comment]
I also would like an option to disable this, I often send people messages on Facebook in Google Chrome and don't like it when Pidgin opens a popup showing I sent a message. I already know that I sent a message, I only want Pidgin to popup when someone replies or sends me a message.

**Comment by felagund** [comment]
Also, when somebody writes me and I just see it on facebook and it gets marked as read, the window of the new message is still flagged as needing attention (at least when using unity plugin on Ubuntu) - I would love if I could set the message window to close when I choose to respond through facebook interface.

**Comment by jgeboski** [comment]
Given the current limitations of the libpurple interfaces, this is not possible without digging into Pidgin or Finch. I have zero interest in doing anything which requires resources outside of libpurple. It really hinders the compatibility with other third-party clients.

The real issue is that there is no real self-message capability in libpurple, and this plugin has had to hack the functionality in. Maybe at some point in the future, the development version of libpurple will support such an interface.

**Comment by jgeboski** [comment]
As of [609d20c](https://bitbucket.org/pidgin/main/commits/609d20c561629a67fc6094c87fa14fe8af998869), self messages can now be disabled. This patch will appear in the next release.

**Comment by felagund** [comment]
Thanks:

BTW, would it be difficult to finegrain this to allow only show messages if a messaging window is open (that would actually be my desired behaviour).

I.e., if I start a conversation from other device, do not show it. If I use other device to add to a conversation that already has an open window/tab, show it.

**Comment by dequis** [comment]
>Given the current limitations of the libpurple interfaces, this is not possible without digging into Pidgin or Finch
