### ISSUE TITLE
Gifs in chat cause disconnect

### ISSUE THREAD

**Issue by ExarchD** [jgeboski/purple-facebook#132]
I doubt this is high priority but I just wanted to bring it to attention. 
The mobile fm messenger app now allows sending of gifs. When I use this plugin and receive a message with a gif the client, the plugin can't process the gif. In group chats it disconnects and you have to close and reopen the window to reconnect to the conversation.

**Comment by jgeboski** [comment]
This works for me in the latest version of the plugin.  Please make sure you are on the latest version.  If you are, try re-adding the account to pidgin.

**Comment by jgeboski** [comment]
Closing due to lack of reply.
