### ISSUE TITLE
Links get lost

### ISSUE THREAD

**Issue by jaymzh** [jgeboski/purple-facebook#134]
When someone sends me an IM that gets turned into a "link" by messenger, even if there's additional text with it, that message doesn't show up in Pidgin.

**Comment by dequis** [comment]
https://github.com/jgeboski/purple-facebook/wiki#after-upgrading-the-plugin-some-features-that-should-work-like-image-thumbnails-seem-to-be-broken

(and of course ensure you're using the latest version)

**Comment by jaymzh** [comment]
OK, gave that a shot, we'll see hwo it goes, tahnks

**Comment by dequis** [comment]
Anything?

**Comment by jaymzh** [comment]
Seems to have fixed it yeah. Not to mention images, thumbs up, etc. all now work.

Do you take donations? This plugin has made my life better, you're awesome.

**Comment by dequis** [comment]
I don't (since all I do here is helping a bit with tickets), ask @jgeboski, he's the awesome one

**Comment by jaymzh** [comment]
(that was intended to be redirected to @jgeboski , though I do appreciate your help :)

**Comment by jgeboski** [comment]
I added donation information to my [homepage](https://jgeboski.github.io/#donations).  :)

**Comment by jaymzh** [comment]
Awesome. Donated a little something just to say thanks for all your work.

**Comment by jgeboski** [comment]
Kudos! Thanks a lot!
