### ISSUE TITLE
Frequent disconnects with latest release

### ISSUE THREAD

**Issue by rrthomas** [jgeboski/purple-facebook#135]
Using release 6a0a79182ebc I get frequent disconnects. It seems to alternate between "Failed to write data" and "ERROR_QUEUE_NOT_FOUND".

I searched other issues, and found #112's mention of ensuring that all messages are marked as read in the Facebook web interface. I did that, and checked that I have nothing marked as unread, but that didn't seem to help.

**Comment by dequis** [comment]
Also try removing your pidgin account and adding it again.

**Comment by rrthomas** [comment]
Thanks @dequis, that seems to have fixed it.

**Comment by dequis** [comment]
Noice.
