### ISSUE TITLE
bad functioning

### ISSUE THREAD

**Issue by curchunflo** [jgeboski/purple-facebook#137]
I am using the last version from repositories at debian 7. When I open pidgin (it take around 30 seconds in being online) pidgin load all my past messages, that take a lot of time and a lot of memory (i have almost 5000 contacts, so I have a lot of messages) and then, I see the error: a lot of times pidgin says that I made a bad use of the function and now I can not use it anymore. If i delete the accounts.xml the message dissapear, and when I open pidgin after charging my user and password again I can use it, but the old messages does not appear anymore. I think that maybe pidgin is making a lot of petitions to facebook and facebook think that there is something wrong so they block my pidgin until I delete accounts.xml and again, and again, and again. I think that this is a design problem maybe??

Thank you james for your effort and your work!!

**Comment by jgeboski** [comment]
> When I open pidgin (it take around 30 seconds in being online) pidgin load all my past messages, that take a lot of time and a lot of memory (i have almost 5000 contacts, so I have a lot of messages)

It will always be "slow" due to the size of the JSON strings being received from Facebook.  The plugin has to parse all of these *massive* JSON strings, and extract the relevant information.  The processing and memory usage is not really noticeable with a "normal" amount of friends, but in this case, 5,000 is quite a lot.

> pidgin load all my past messages

This feature can be disabled under the `Advanced` tab in the account settings.  Just uncheck the `Mark messages as read`.

> I see the error: a lot of times pidgin says that I made a bad use of the function and now I can not use it anymore.

Send me a [debugging log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs).

**Comment by curchunflo** [comment]
Hello James! I had sent you the log!! Thank you!!

Date: Sun, 13 Sep 2015 09:05:01 -0700

**Comment by curchunflo** [comment]
hello! james! I sent you the log, than you very much!!

**Comment by jgeboski** [comment]
I only see errors relating to the MQTT stream dropping out, nothing more.  Is this the error you are talking about?

```
$ ag "Connection error" pidgin.log
7011:(13:20:55) connection: Connection error on 0xb9037e20 (reason: 0 description: Failed to read fixed header)
14183:(13:22:09) connection: Connection error on 0xb818e9c8 (reason: 0 description: Failed to read fixed header)
```

**Comment by curchunflo** [comment]
Hello! Today I deactivated the "mark as read" option and now I can connect. I think that Facebook does not give its confidence to third party programs so when pidgin ask for all the unread messages they think that is some kind of action that they disapproves so they cut the connection between pidgin and my account.
It is just a theory, but since I updated the plugin I can't connect and now that I deactivated that option I can do it. Maybe you can put that option disabled from default, if there is a lot of people doing the same thing (there is a LOT of people with many unread messages on their accounts)  maybe facebook try to block your plugin and nobody could use it anymore. Just thoughts, but I think that if they were blocking me because pidgin was reading all that messages in the same second they can be more agressive with other conducts. 
If I am right, the problem was that but it had other bigger problem. Because Pidgin never get online, the messages never was marked as read, so every moment I clicked "reconnect" the process started from the beginning, so, if I did not deactivated the option, probably I could not never get online with pidgin again. I think that is a very dangerous option cause if all people who is using your plugin starts to ask all unread messages at the same time, maybe facebook could start blocking accounts with that behavior.
If there is somebody with the same problem: I had to delete accounts.xml too, deleting that file made that Pidgin stop trying to get all unread menssages so it goes online again. Deactivating the option made that pidgin stop to asking for all my messages.
I still have the problem but it is not constant and now I can connect. 
BTW what does mean the "sync" contact option???  thank you very much!!

**Comment by jgeboski** [comment]
> I think that Facebook does not give its confidence to third party programs so when pidgin ask for all the unread messages they think that is some kind of action that they disapproves so they cut the connection between pidgin and my account.

If they really wanted to block the plugin, they'd likely block the agent used to initialize the MQTT stream.

> Because Pidgin never get online, the messages never was marked as read, so every moment I clicked "reconnect" the process started from the beginning, so, if I did not deactivated the option, probably I could not never get online with pidgin again.

Yes, but based on a quick glance at your log, the plugin never even attempts to fetch the unread message count.  The MQTT connection ends up failing even before the plugin has the chance to request such information.

> Pidgin stop trying to get all unread menssages so it goes online again. Deactivating the option made that pidgin stop to asking for all my messages.

While this should be irrelevant, I am curious, do you have happen to have a bunch of unread messages on the Facebook website?

> BTW what does mean the "sync" contact option???

It defines how often (in minutes) the friends list is refetched for updates.  This has to be done as Facebook does not send any events for users, only threads.  Given that you have 5,000 friends, I would recommend you keep this value at `30` (the default) or higher.

**Comment by curchunflo** [comment]
thanks James! you are right, they can block with other options. 

Yes, I had a lot of unread messages, like 50/60 every time I get online at the website, i have a lot of contacts and when I am not online I get a lot of new unread messages so I had that problem, but today is not a problema anymore!

Thank you james!

**Comment by jgeboski** [comment]
It is consistently dies right after the `SUBACK` for `/orca_message_notifications` is received.  It might be sending a large blob of data for presence states or something, which is not being read into the buffer correctly.  This is before the message queue is ever initialized.  Disabling unread messages should have nothing to do with this.  I have no idea why this is occurring, maybe due to the amount of friends.  If this issue is persistent, I will add some more debugging output for the MQTT socket when I get some free time.

```
(13:22:09) facebook: Reading 11 (flags: 0x0)
(13:22:09) facebook:   00000000  b0 02 00 03                                       |....|
(13:22:09) facebook:   00000010
(13:22:09) connection: Connection error on 0xb818e9c8 (reason: 0 description: Failed to read fixed header)
```

**Comment by curchunflo** [comment]
Hello James! Now it its working great and it reconnects 99% of the times when I click reconnect. Thank you!

**Comment by jgeboski** [comment]
Is this still working as expected after disabling the `Mark messages as read` option?

**Comment by jgeboski** [comment]
Closing due to lack of reply.

**Comment by curchunflo** [comment]
Hello James! I did answer you but to your email I think. 
Yes, when I deactivate the mark as unread option it works smoothly, but when it is activated i get the "falied to read fixed header" error
It is not resolved but I can use it whiout marking as read messages.
Thank you!

Date: Wed, 14 Oct 2015 06:29:33 -0700
