### ISSUE TITLE
Extraneous HTML formatting sent to users

### ISSUE THREAD

**Issue by instinctualjealousy** [jgeboski/purple-facebook#14]
Pidgin 2.10.11
Latest built Windows binary of libfacebook available

I haven't had any issues with receiving messages from others, but messages sent out to Facebook/its users sometimes get extraneous formatting on them.

For instance, I can type "This is a quoted text" in Pidgin and it will appear on the Facebook log/to other Facebook users as

 &quotThis is a quoted text&quot
with semicolons left out so GitHub will display it

Also, & appears as &amp

I do not have any conversation formatting settings on in the chat window. I am not using "Use font from theme" in Default Formatting, but this likely has nothing to do with it, anyway. I just have a font and a font size set as many normal users probably do. There aren't any workarounds inside Pidgin to fix this as i know of- it simply needs parsed out somehow or interpreted correctly.

**Comment by jgeboski** [comment]
This has been fixed [upstream](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/ac1d2fdaab42), and will be in the next update.
