### ISSUE TITLE
not trusting file .pidgin/.hg/hgrc from untrusted

### ISSUE THREAD

**Issue by Bucov** [jgeboski/purple-facebook#140]
Hi i have problem installing plugin in fedora 22. I have install all dependencies and i get this when i run autogen.sh 
[Vstojakov@localhost purple-facebook] $ sudo ./autogen.sh 
not trusting file .pidgin/.hg/hgrc from untrusted user Vstojakov, group Vstojakov
not trusting file /home/Vstojakov/purple-facebook/.pidgin/.hg/hgrc from untrusted user Vstojakov, group Vstojakov
abort: repository default not found!
not trusting file .pidgin/.hg/hgrc from untrusted user Vstojakov, group Vstojakov
not trusting file /home/Vstojakov/purple-facebook/.pidgin/.hg/hgrc from untrusted user Vstojakov, group Vstojakov
resolving manifests
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
./update.sh: ред 37: patch: нема такве наредбе
./update.sh: ред 37: patch: нема такве наредбе
./update.sh: ред 37: patch: нема такве наредбе
It is all same with su. Please help
Thanks

**Comment by dequis** [comment]
http://stackoverflow.com/questions/8535866/not-trusting-file-hg-hgrc-from-untrusted-user-root-group-dev

https://mercurial.selenic.com/wiki/Trust

If you download the tarball from the releases page https://github.com/jgeboski/purple-facebook/releases you won't need to mess with mercurial. Right now the latest release is the same as the latest mercurial commit.

**Comment by Bucov** [comment]
I dont understand how does mercurial works so i can not fix it. For tarball release i get error
configure: error: Package requirements (json-glib-1.0 >= 0.14.0) were not met:

No package 'json-glib-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JSON_CFLAGS
and JSON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
I have all required dependencies installed

**Comment by dequis** [comment]
Quoting wiki:

>If these packages came from the distribution's repository, they will likely need additional development packages, usually suffixed with -dev.

In the case of fedora you'd need json-glib-devel

**Comment by Bucov** [comment]
thank you i made it

**Comment by dequis** [comment]
Yay!
