### ISSUE TITLE
Typo in the wiki: "to support a the newer Facebook Messenger protocol."

### ISSUE THREAD

**Issue by shlomif** [jgeboski/purple-facebook#141]
Hi all,

thanks for purple-facebook - it is great. In https://github.com/jgeboski/purple-facebook/wiki “to support a the newer Facebook Messenger protocol.” should be s/a the/the/ .

Please fix it.

**Comment by jgeboski** [comment]
Fixed. Thanks.

**Comment by shlomif** [comment]
Thanks!
