### ISSUE TITLE
Messages not marked as read with telepathy-haze

### ISSUE THREAD

**Issue by nodevel** [jgeboski/purple-facebook#144]
Hi,

I am trying to use your plugin (great work, by the way) on telepathy, through the telepathy-haze layer, in order to have Facebook Messenger integrated on SailfishOS ( https://openrepos.net/content/nodevel/facebook-messenger-account ). Messages work well - can be sent and received - but there is one annoying problem: Messages are not be marked as read on the server, therefore they are being received over and over again on every reconnection.

Is there any way to mark messages read by default, as soon as they are received by the plugin?

I know that telepathy-haze in most likely not among supported solutions, but I don't understand why it should work any different, if message receiving already works.

I have tried two last releases (6a0a79182ebc, 5727ffb502c7) with the same outcome.

Thank you.

**Comment by jgeboski** [comment]
> Is there any way to mark messages read by default, as soon as they are received by the plugin?

It use to be done this way, then users wanted it done on conversation focus (#80). Now users want it done when a message is sent in response (#118). I will eventually have to make this more configurable.

> I know that telepathy-haze in most likely not among supported solutions, but I don't understand why it should work any different, if message receiving already works.

It needs to support the `conversation-updated` signal, the `deleting-conversation` signal, and `purple_conversation_has_focus()`. I was initially hesitant doing this as I figured people who were not using pidgin or finch, would run into this issue.

**Comment by MoritzJT** [comment]
Would be nice if we had the opportunity to configure this in the plugin settings lateron @nodevel 
I imagine some users want it done manually, some want the read status prevented alltogether etc...

**Comment by nodevel** [comment]
@jgeboski Thanks for your reply!

I see, so the current behavior is that it marks messages as read when you reply to the thread?

If I wanted to change that behavior (to the one I suggested), is there currently any easy way to change it? I mean either via patching the code, or changing the build flags?

**Comment by jgeboski** [comment]
> I see, so the current behavior is that it marks messages as read when you reply to the thread?

No, it is based on focus.  As soon as you focus the conversation in pidgin, it will then mark the message thread as read.

> If I wanted to change that behavior (to the one I suggested), is there currently any easy way to change it? I mean either via patching the code, or changing the build flags?

Could create your own patch, but I have non handy.

**Comment by psx01de** [comment]
I have the same problem with purple-facebook as transport with spectrum2. It worked for months without any problem but after the last update, I receive the messages again and again on all devices. Currently the plugin is not usable anymore for this purpose. How to change it back - and - if you include any option in your plugin - how can i set them through spectrum2?

Thanks,
Patrick

**Comment by rodneyrod** [comment]
@nodevel Is it possible for your work to be adapted to desktop Telepathy clients have access to this plugin too?

**Comment by psx01de** [comment]
Please help: Which version I need to go back to be able to continue using purple-facebook with spectrum2?

**Comment by nodevel** [comment]
@psx01de I went back to 3d30d24fdbef in my case (telepathy-haze) and it works fine.

@rodneyrod I haven't tried it, but you can look at the code (the rpm is noarch) and see for yourself:
https://openrepos.net/sites/default/files/packages/1033/haze-accounts-extensions-facebookmessenger-0.3-3.noarch.rpm

**Comment by psx01de** [comment]
@nodevel Thank you, it looks good!

**Comment by Thaodan** [comment]
anyone tried to create an account with mc-tool and is able to login?

**Comment by xbmcsport** [comment]
Any chance to get this fixed? Have the same issue with spectrum2 and had to revert to 3d30d24fdbef. Maybe it is possible to customize?

**Comment by jgeboski** [comment]
Closed in favor of #221.
