### ISSUE TITLE
FB@work ?

### ISSUE THREAD

**Issue by dhardy92** [jgeboski/purple-facebook#147]
Does this is compatible with facebook@work private social network ?

**Comment by jgeboski** [comment]
I have no idea, honestly.  Does it work with the Messenger app?  If so, then it will probably work.

**Comment by dhardy92** [comment]
I suppose not, because this exists : https://play.google.com/store/apps/details?id=com.facebook.work

**Comment by dhardy92** [comment]
actually your plugin is ok for my personal account but failed for now with my pro one (using email address as login pigdin complains about invalid login or email address)

**Comment by jgeboski** [comment]
I have no idea, I have no experience with Facebook at Work.  This plugin only supports the Messenger protocol, and will likely only ever support the Messenger protocol.

**Comment by dhardy92** [comment]
ok BTW this is open source and one days someone would look a it doing some tests and see what is missing to make it work with FB@work :)
Thank you for your Work on public facebook chat version this is the main part I suppose ...
