### ISSUE TITLE
Image receiving/sending: parse error: unexpected character `{'

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#148]
When I send an image from Facebook.com to my Facebook contact person who I'm chatting with on Pidgin, I often get this:

<data&gt;:1:468: Parse error: unexpected character `{', expected string constant

This also happens often with receiving images (almost every time). The result is that purple-facebook disconnects from Facebook and upon reconnecting, there is no image in the chat conversation window.

Seems like a JSON issue in purple-facebook.

**Comment by jgeboski** [comment]
Re-add the account.

**Comment by Smile4ever** [comment]
Thank you.
