### ISSUE TITLE
Buddy Avatars not loading with spectrum2

### ISSUE THREAD

**Issue by Ghabry** [jgeboski/purple-facebook#149]
Hi, I use spectrum2 (A XMPP-Server that provides transports to non-xmpp protocols for connecting with XMPP clients to legacy networks) and when using purple-facebook information about contacts (e.g. the avatar) do not load (but names are correctly fetched).

The spectrum2 log is:
```
VCardResponder: prpl-facebook.[....]: Requested VCard of 10000123456789
[...] one minute later
VCardResponder: Removing 1 timeouted VCard requests
```

Expected output (purple-skypeweb):
```
VCardResponder: prpl-skypeweb.[...]: Requested VCard of [username]
VCardResponder: prpl-skypeweb.[...]: Forwarding VCard of [username] from legacy network
```

Not sure if this is a bug in spectrum2 or in prpl-facebook but this is the first plugin where I encountered this issue, any other plugin works.

The logic is here https://github.com/hanzz/libtransport/blob/master/backends/libpurple/main.cpp#L512
(so it calls ```srv_get_info``` at the end, name is the id of the fb contact, e.g. 10000123456789)

**Comment by jgeboski** [comment]
Is this a duplicate of #65?

**Comment by Ghabry** [comment]
Yeah, sorry. I only checked the open issues.
Now I get avatars but other fields in the Vcard (when using different services then facebook) are not populated anymore. Not very critical (and not sure if bug in client or spectrum), the nicknames are received.

Will submit a patch to spectrum soon.

Thanks!

**Comment by jgeboski** [comment]
A fix upstream would be lovely!

**Comment by Ghabry** [comment]
Patch submitted: https://github.com/hanzz/libtransport/pull/64

**Comment by jgeboski** [comment]
Kudos!
