### ISSUE TITLE
No matches for $.data[0].fql_result_set[0].sync_sequence_id

### ISSUE THREAD

**Issue by ZXGuesser** [jgeboski/purple-facebook#15]
Trying to enable account always results in above error. Using pidgin 2.10.11 on windows 7 64-bit

**Comment by jgeboski** [comment]
Are you using a Facebook account which has no [messages](https://www.facebook.com/messages)?

**Comment by ZXGuesser** [comment]
my inbox is empty yes.

**Comment by jgeboski** [comment]
This is a known issue, which has yet to be addressed.  This will likely get addressed when I yank the FQL usage from the plugin, which is on the TODO (#9).  For now, just send a message to someone via the website, and that should resolve the issue.

**Comment by ZXGuesser** [comment]
excellent, working now thanks!

**Comment by jgeboski** [comment]
Neat!  I am going to go ahead and close this issue as this is indirectly on #9.

**Comment by jgeboski** [comment]
This should be fixed as of the latest release ([565fbae05259](https://github.com/jgeboski/purple-facebook/releases/tag/565fbae05259)).  I removed all usage of FQL, namely the weird retrieval of the thread sequence identifier.
