### ISSUE TITLE
Better support for 2fac

### ISSUE THREAD

**Issue by jaymzh** [jgeboski/purple-facebook#151]
Currently the flow if you have 2fac enabled is:
* Put in password, attempt to login, get message SMS code was sent
* Modify account to put in 2fac code
* Re-enable account

Then a month later when that token is expired you have to modify the account, put in your password and repeat.

It would be really nice if I could just save my password in the account normally, but get prompted for the SMS code (it's only ever used once, to get the token).

**Comment by Th3-822** [comment]
You should use app passwords: https://www.facebook.com/settings?tab=security&section=per_app_passwords
I got one for pìdgin and i don't have to worry about saving my real password or getting sms with tokens.

**Comment by dequis** [comment]
^this.

**Comment by jaymzh** [comment]
Oh, duh, forgot we had those. Thanks.

So I amend my bug report - instead of Pidgin telling you you'll get an SMS code, it should tell you to create an app password. :)

**Comment by dequis** [comment]
>instead of Pidgin telling you you'll get an SMS code

We have no control over those messages. It's a server side error.
