### ISSUE TITLE
Messages read through facebook shold remove notification in pidgin

### ISSUE THREAD

**Issue by felagund** [jgeboski/purple-facebook#152]
At least on Ubuntu using the Unity's plugin, when somebody writes me, the window demands attention (I think the signal is called "alert"?) by a little blue arrow next to it (and the messaging indicator turning blue). If I respond over Facebook interface, these alerts should be removed, I think.

**Comment by cherryleafroad** [comment]
It's the same on Windows as well.

**Comment by jgeboski** [comment]
Given the current limitations of the libpurple interfaces, this is not possible without digging into Pidgin or Finch. I have zero interest in doing anything which requires resources outside of libpurple. It really hinders the compatibility with other third-party clients.

The libpurple interfaces provide no access to the notifications or the read state of messages. This is information contained only at the user interface level. Maybe in future development versions of libpurple there will be a way to manipulate such information.
