### ISSUE TITLE
configure script is not available in the latest release

### ISSUE THREAD

**Issue by HouzuoGuo** [jgeboski/purple-facebook#153]
According to wiki page, configure script (./configure) should be available in the tarball release, however this is not the case in the latest release 6a0a79182ebc. Please fix, many thanks.

**Comment by dequis** [comment]
Download the one that says `purple-facebook-6a0a79182ebc.tar.gz`, not `source code (.tar.gz)`. The latter is automatically built by github from the git repo, we can't do anything about it.

**Comment by HouzuoGuo** [comment]
thank you.
