### ISSUE TITLE
Messages received repeated/duplicated periodically until disconnect/reconnect

### ISSUE THREAD

**Issue by PorcelainMouse** [jgeboski/purple-facebook#155]
Recently, when at least one of my FB friends sends me a txt mesg, purple-facebook will periodically repeat/replay/duplicate the exact messages.  They come in like new messages, in order, but I can see from the buffer that they are repeats.

It may not be everyone, though.  It has been happening always for one particular friend with whom I most often communicate via FB since this symptom began.  I only goes away when close and reopen the FB connection, manually.  But, I don't think it happened with someone I happen to chat with the other day, so it's not everyone. 

Anyone else see this?  Perhaps it is some interaction with the sender's FB client?

**Comment by jgeboski** [comment]
So, you can confirm the duplicate message(s) are sent over the MQTT stream?

**Comment by PorcelainMouse** [comment]
Hmm, I'm not sure.  I'm willing to test, but I don't know enough to design a test for that.  Do you have a test in mind?  What else would it be?  I can confirm they come from my FB contact, not the same person on another network, for example.  Does FB use anything other than MQTT?  I only have the one FB account and this is my only FB-chat plugin for purple.

**Comment by jgeboski** [comment]
The easiest thing to do would be to run the plugin with [debugging](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs) enabled.  Then, grep the debug output for the duplicated message, and see how many times it shows up in the results.  If it is more than once, then Facebook is sending more than one message.

**Comment by jgeboski** [comment]
I can confirm this is happening to me as well.

**Comment by Smile4ever** [comment]
I sometimes get the message up to 4 times, with more or less the same timestamp (max a few seconds difference).

**Comment by jgeboski** [comment]
@dequis provided me a log, and the message identifiers and time stamps are indeed the same. I still would like to poke at it more before patching based on time stamp or message identifiers to ensure consistency.

**Comment by Smile4ever** [comment]
If you fix it by comparing the timestamps, make sure you cover this case as well:
18:41:33,500 the same message 
18:41:33,700 the same message 
18:41:33,900 the same message 
18:41:34,200 the same message

**Comment by jgeboski** [comment]
Yes. It would need to be a mix of the message identifiers and time stamps.

**Comment by Smile4ever** [comment]
I found another case which has the same outcome:
(11:03:06) same message
Failed to read fixed header -> click Reconnect
(11:03:15) same message

**Comment by Smile4ever** [comment]
This bug applies for images as well.

**Comment by aeridus** [comment]
I also have this problem. Aside from this bug, the plugin has been flawless, so I really hope this gets fixed soon.

**Comment by deekej** [comment]
I have the similar/same issue, both on Linux & Windows platform.
For me, when I receive a single message, it is duplicated many times instantly.

I can post a screenshot, if necessary, after it happens again.

**Comment by dequis** [comment]
Posting here for reference:

orca 39.0.0.23.150 (2015-09-10) is affected http://dump.dequis.org/p2d_8.txt (but does client-side deduplication)

orca 52.0.0.19.66 (2015-12-16) isn't http://dump.dequis.org/t7SiC.txt (at least over 200 messages)

**Comment by jgeboski** [comment]
This has most been resolved as of [ad2ee74](https://bitbucket.org/pidgin/main/commits/ad2ee74b913ae50e170b1d06413fa2a494a9ee76), which is in the latest release.

**Comment by Smile4ever** [comment]
Great! Thank you!

**Comment by PaulDeStefano** [comment]
Yes, me too.  Best I can tell, this is fixed.  Thanks!

**Comment by PaulDeStefano** [comment]
Actually, it happened to me again.  25a255f32eee.

**Comment by jgeboski** [comment]
Please see the [commit message](https://bitbucket.org/pidgin/main/commits/ad2ee74b913ae50e170b1d06413fa2a494a9ee76). The fix is not bulletproof.

**Comment by PaulDeStefano** [comment]
Got it, thanks!

**Comment by greatquux** [comment]
I've only noticed it happening when a message has come in, and I have not switched to the pidgin window ro read it (and therefore mark it as read, or mark it as read some other way).  so it's mostly fixed for now.

**Comment by masterxq** [comment]
Hello, this bug still apears for me.
I'm using purple-facebook from Debian repository.
Version:
20160409~2a24dff~66ee77378d82~110
I'm not absolutly sure, but it seens that i repeatly get the message every time i reconnect.

I'm using purple-facebook with spectrum2 for ejabberd with xabber as client.

**Comment by dequis** [comment]
@masterxq 

Quoting from above:

> Please see the [commit message](https://bitbucket.org/pidgin/main/commits/ad2ee74b913ae50e170b1d06413fa2a494a9ee76). The fix is not bulletproof.

However, you seem to be describing something unrelated to this issue.

It sounds like you've disabled mark as read (or it doesn't work with spectrum) and that you have show unread messages enabled. Disabling that one should do it.

In the future (or if you have any further issues) please open a new issue. I'm locking this one.
