### ISSUE TITLE
Receiving audio or video clip links

### ISSUE THREAD

**Issue by advcomp2019** [jgeboski/purple-facebook#156]
I have a few friends send me audio and video clips from their phones in the last week or so, and most of the time, I get disconnected from Facebook. There was one time it had Pidgin crash. If I start Pidgin up fresh or enable the Facebook protocol, it get them just fine with no issue. Not sure if others can reproduce this. They was mp4 clip links.

**Comment by jgeboski** [comment]
Could you provide a [stack trace](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs#obtaining-a-gdb-backtrace) when it crashes?

**Comment by advcomp2019** [comment]
It only crashed once, but since it crashed the one time, it has not crash. Not sure if that crash happened from something else or not.

Whenever someone sends an audio or video clip, I get these in the debug window:
(12:56:21) facebook: Presence: 508662436 (0)
(12:56:21) blist: Updating buddy status for 508662436 (Facebook)
(12:56:27) util: Writing file blist.xml to directory C:\Users\<user>\AppData\Roaming\.purple
(12:56:27) util: Writing file C:\Users\<user>\AppData\Roaming\.purple\blist.xml
(12:56:28) facebook: Presence: 501799212 (1)
(12:56:28) blist: Updating buddy status for 501799212 (Facebook)
(12:56:31) facebook: Presence: 1153693003 (0)
(12:56:31) blist: Updating buddy status for 1153693003 (Facebook)
(12:56:36) util: Writing file blist.xml to directory C:\Users\<user>\AppData\Roaming\.purple
(12:56:36) util: Writing file C:\Users\<user>\AppData\Roaming\.purple\blist.xml
(12:56:36) facebook: Presence: 1246073287 (1)
(12:56:36) blist: Updating buddy status for 1246073287 (Facebook)
(12:56:40) connection: Connection error on 0AD05280 (reason: 0 description: <none>:1: Parse error: unexpected character `{', expected string constant)
(12:56:40) account: Disconnecting account <FACEBOOK_USERNAME> (038BA0C0)
(12:56:40) connection: Disconnecting connection 0AD05280
(12:56:40) connection: Destroying connection 0AD05280
(12:56:46) util: Writing file accounts.xml to directory C:\Users\<user>\AppData\Roaming\.purple
(12:56:46) util: Writing file C:\Users\<user>\AppData\Roaming\.purple\accounts.xml
(12:56:46) util: Writing file blist.xml to directory C:\Users\<user>\AppData\Roaming\.purple
(12:56:46) util: Writing file C:\Users\<user>\AppData\Roaming\.purple\blist.xml

I removed my user name and computer user name just in case.

**Comment by jgeboski** [comment]
Re-adding the account should fix this issue. The queue is likely still requesting malformed JSON, which when the queue is recreated (from re-adding the account), will no longer request the offending JSON values.

**Comment by advcomp2019** [comment]
I did that when you got the photos working in the client. I can try re-adding again, but I don't know if I can get a friend to test it again.

**Comment by dequis** [comment]
I tested this again and it works so closing. Add a comment if it still happens.
