### ISSUE TITLE
Group chat

### ISSUE THREAD

**Issue by AkelD** [jgeboski/purple-facebook#158]
I am not sure about this, but does the plugin support chatting in facebook groups?

**Comment by dequis** [comment]
Yes.

Tools menu -> room list -> "get list" button.

Or, to start a new one, right click a contact in the buddy list and select initiate chat.

**Comment by AkelD** [comment]
I already tried that one, doesn't show anything.

**Comment by jgeboski** [comment]
Then you have no active chat threads (or there is a bug). Either way, you should be able to start a new group chat like @dequis mentioned.

**Comment by AkelD** [comment]
> Then you have no active chat threads
Ah, that must be it. Thanks.
