### ISSUE TITLE
Startup without Internet connection does not connect to Facebook

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#160]
If I boot my computer, it may happen that there is no connection to the Internet yet.

If I set Pidgin to autostart on boot, purple-facebook tries to connect to the Facebook servers while there is no Internet connection. If the Internet connection comes online, purple-facebook is still stuck "connecting".

As a workaround, I have to quit Pidgin and start it again.

**Comment by jgeboski** [comment]
Is this related to #143 or #89?

**Comment by Smile4ever** [comment]
This problem seems to have the same root cause as #143.
