### ISSUE TITLE
Messages with links with previews are not delivered

### ISSUE THREAD

**Issue by Kvasi** [jgeboski/purple-facebook#163]
If I send a message from facebook with a link and that link gets a preview it will not show up in Pidgin.
If I remove the preview of the link before sending it will show up.
![pidgin_facebook](https://cloud.githubusercontent.com/assets/238312/10882526/c794f156-816b-11e5-82f4-4a1f0287b30d.png)

**Comment by dequis** [comment]
Works for me. Are you using an old version, or did you upgrade from an old version?

https://github.com/jgeboski/purple-facebook/wiki#after-upgrading-the-plugin-some-features-that-should-work-like-image-thumbnails-seem-to-be-broken

**Comment by Kvasi** [comment]
Works after deleting and recreating the account.
