### ISSUE TITLE
Own messages in group chat are not shown when chatting using Messenger app

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#167]
My own messages aren't inserted in the group chat (in Pidgin) that I have open when I use the Messenger app to reply in the group.

**Comment by jgeboski** [comment]
I just retested this with the latest release, and it appears to function as expected. This must have been fixed by something else, as I do not remember this working as intended previously. Can you confirm this issue has been resolved?

**Comment by Smile4ever** [comment]
I confirm this.
