### ISSUE TITLE
Timestamps of received offline messages

### ISSUE THREAD

**Issue by Riamse** [jgeboski/purple-facebook#168]
They're incorrect. Instead of showing the true timestamps of the messages, purple-facebook shows the timestamps of the time at which the messages were actually delivered to pidgin, ie whenever you connect.

**Comment by jgeboski** [comment]
This has been resolved as of [643d7b0](https://bitbucket.org/pidgin/main/commits/643d7b0aadbdd1ae27a8daee1e65ba93a3d2abda) and will appear in the next release.
