### ISSUE TITLE
Hide Offline users

### ISSUE THREAD

**Issue by bonelifer** [jgeboski/purple-facebook#169]
Would be nice to hide offline users.

**Comment by jgeboski** [comment]
This functionality is outside the scope of this plugin. Consult the manual of your libpurple client, such as Pidgin.

**Comment by Photon89** [comment]
In Pidgin: Buddies>Show>Offline Buddies

**Comment by bonelifer** [comment]
[**@Photon89**](https://github.com/Photon89) commented on [Nov 13, 2015, 3:09 PM CST](https://github.com/jgeboski/purple-facebook/issues/169#issuecomment-156557465 "2015-11-13T21:09:31Z - Replied by Github Comment Enhancer"):
> In Pidgin: Buddies&gt;Show&gt;Offline Buddies

Thanks.
