### ISSUE TITLE
Buddy aliases don't seem to work

### ISSUE THREAD

**Issue by slackhead** [jgeboski/purple-facebook#172]
I've just tried the plugin for the first time and it names my buddies by a long string of digits.
If I 'right click -> alias' then it shows their names in the alias box but it doesn't seem to allow setting an alias.

Any ideass?

**Comment by jgeboski** [comment]
It works for me. Do you have any third-party plugins enabled?

**Comment by slackhead** [comment]
Ah. I've just switched all my plugins off and the names show now. I'm not which one is breaking it, but I'll have a look at each to see what happens. Thanks for pointing me in the direction.

**Comment by slackhead** [comment]
Closing #172
