### ISSUE TITLE
Is pidgin's `Invisible' status supported?

### ISSUE THREAD

**Issue by slackhead** [jgeboski/purple-facebook#174]
I noticed when I set myself as invisible I can still double click on a facebook buddy and a chat window opens. IIRC for other protocols a window pops up that says I can't chat when invisible.

**Comment by jgeboski** [comment]
Being invisible offers the same functionality as normal, but your status just appears as offline to other users. It is worth noting, it takes several minutes for the invisibility to take effect.

**Comment by slackhead** [comment]
And if I start to chat with someone, does it make me visible again?

**Comment by jgeboski** [comment]
It does not, no.

**Comment by slackhead** [comment]
Ok thanks. Closing #174
