### ISSUE TITLE
Frequent Disconnects without Reconnecting - Pidgin

### ISSUE THREAD

**Issue by Swannicus** [jgeboski/purple-facebook#175]
My plugin works fine for 15 minutes to an hour then it disconnects, often without me noticing.  It wouldn't be an issue but it fails to automatically reconnect unless I manually disable the account and re-enable it.
I'm running it on Windows 7 in Pidgin with the 20151018~a418f60~6a0a79182ebc~24 version.

**Comment by kernc** [comment]
This happens to me with all sorts of accounts (namely GTalk (XMPP) and IRC with SASL). I think it's Pidgin's fault.

**Comment by dequis** [comment]
Sounds like the same thing as #143
