### ISSUE TITLE
Pidgin hangs on random disconnect from Facebook.

### ISSUE THREAD

**Issue by scuba78** [jgeboski/purple-facebook#176]
Running Windows 10 
I believe I am on the most recent version of the plugin.

Facebook sometimes randomly disconnects - When it attempts to reconnect the entire pidgin application hangs. 

Not sure what information you need to troubleshoot this, but quite happy to provide anything required.

**Comment by jgeboski** [comment]
Could you please provide a [report file](https://developer.pidgin.im/wiki/TipsForBugReports#WindowsUsers)?

**Comment by dequis** [comment]
*poke*

**Comment by jgeboski** [comment]
Closing due to lack of reply.
