### ISSUE TITLE
Intermittent crashes

### ISSUE THREAD

**Issue by alexfoster** [jgeboski/purple-facebook#178]
Hello, my name is Alejandro Guadelope Hidalgo Foster. I have been using your product for many days now and can say it is very decent! However I notice that there are periodic crashes. I run it on a BSD-based custom kernel on a modified Atari from my office in Bell Labs. Do you have support for this and if not can you please add on next release! 

Cheers mate!

**Comment by jgeboski** [comment]
Take the trolling elsewhere.
