### ISSUE TITLE
Allow offline messages

### ISSUE THREAD

**Issue by kesava-wow** [jgeboski/purple-facebook#18]
It seems offline messages are only available as a pounce through Pidgin. Facebook does actually have the capability to send messages to people while they're offline at which point it'll generally send them some sort of notification, e-mail, push or whatever, so it is beneficial to be able to send messages to offline friends.

**Comment by jgeboski** [comment]
Uh... what?  I am able to send offline messages.

**Comment by kesava-wow** [comment]
Uh, yep. So am I.

I guess that was caused by another plugin I had on Linux.

Um, sorry about that. Thanks for the plugin!

**Comment by leandroembu** [comment]
We can send offline messages to our buddies, but we can't receive messages sent to while we are offline.
