### ISSUE TITLE
Root node followed by invalid character '

### ISSUE THREAD

**Issue by advcomp2019** [jgeboski/purple-facebook#182]
I was invited to a group with lots of people in it, and whenever someone started talking, i started to get this message: https://dl.dropboxusercontent.com/u/4643460/pidginfacebook.PNG

Then a few times I got a few crashes: http://pastebin.com/cVaUcu8N or http://pastebin.com/xA6k15Hq

Sent email to jgeboski with a better debug.

**Comment by advcomp2019** [comment]
Update: It looks like it is when someone leaves or join the group the message pops up. Plus it is only with Windows that sees this issue.

**Comment by dequis** [comment]
https://github.com/jgeboski/bitlbee-facebook/commit/265169cd12cfdb15c89c7ee83d1a563be72c92a7

**Comment by jgeboski** [comment]
This issue has been resolved as of [7f8a2f3][c1], [56c7dbe][c2], and [df4d0ab][c3]. These patches will appear in the next release.

[c1]: https://bitbucket.org/pidgin/main/commits/7f8a2f301a8220750ee9f8b29de424749fab01d4
[c2]: https://bitbucket.org/pidgin/main/commits/56c7dbe972663344a58e6994b8ccaa0a162b73f9
[c3]: https://bitbucket.org/pidgin/main/commits/df4d0ab7eaae8edcc5f1bc8fbfcd50d319586f74
