### ISSUE TITLE
Plugin not detected on Windows 10

### ISSUE THREAD

**Issue by spartanhooah** [jgeboski/purple-facebook#183]
I downloaded the two dll files and put them in C:\Program Files (x86)\Pidgin and C:\Program Files (x86)\Pidgin\plugins, but Pidgin is not detecting the plugin, even after a couple of Pidgin restarts and a Windows restart. I have Windows 10 and Pidgin 2.10.11.

**Comment by sateffen** [comment]
I've got windows 10 as well, and here's all fine.

This plugin won't appear in the plugin menu, it's directly available at the account manager. Go to accounts -> manage accounts, and than add a new account, with the protocoll "facebook" (NOT facebook xmpp). At least there should be this option.

Sorry if the menus are called differently, I'm on a german version.

**Comment by spartanhooah** [comment]
Ah, thanks, that works; I misunderstood the instructions. Now to figure out why Google Chat isn't working...

**Comment by jgeboski** [comment]
Thanks @sateffen!
