### ISSUE TITLE
Certificate problem when receiving an image

### ISSUE THREAD

**Issue by redhead** [jgeboski/purple-facebook#184]
When an image is received (not a sticker but a photo), several dialog windows open with message about invalid certificate chain.

**Comment by redhead** [comment]
Also the images is not shown (do not know if that was supposed to be a feature).

**Comment by jgeboski** [comment]
Operating system?

**Comment by redhead** [comment]
Oh sorry. Windows.

**Comment by EionRobb** [comment]
What's the contents of the "dialog windows open with message about invalid certificate chain" messages?

**Comment by redhead** [comment]
I do have more and more problems with the certificates now. 

Unrelated to the issue here, sometimes the connection is lost and disabling and enabling the account does not help. Only when I restarted pidgin it worked. But now, even restarting doesn't help, and the account never connects. The message is always the same:

> The certificate for graph.facebook.com could not be validated. The certificate chain presented is invalid.

Now, it always mentions graph.facebook.com, but before it shown all sorts of facebook urls. In case of the image, every dialog (out of 5) had different URL, I think. But now, I cannot even connect to the chat.

**Comment by redhead** [comment]
I had problems with certificates [before](https://github.com/jgeboski/purple-facebook/issues/177#issuecomment-164244361), I removed the certificate from the user's app folder. And then it worked. But this fix does not help anymore.

**Comment by jgeboski** [comment]
What version of Pidgin?

**Comment by redhead** [comment]
Pidgin 2.10.7 (libpurple 2.10.7)

**Comment by sateffen** [comment]
Could you update to the newest verison of pidgin ([2.10.11](https://pidgin.im/)) and check if the errors are still there?

Reason is, that with pidgin 2.10.8 and 2.10.11 some SSL releated fixes came along ([see changelog](https://developer.pidgin.im/wiki/ChangeLog)). This way we can exclude the chance, that this bugs got fixed already.

**Comment by jgeboski** [comment]
Pidgin-2.10.7 is missing `DigiCertHighAssuranceEVRootCA.pem`, which is required for `graph.facebook.com`. This certificate is present in the latest version of Pidgin, 2.10.11.

**Comment by redhead** [comment]
Brilliant! It seems to work. I am so used to applications with autoupdate, that I forgot to update pidgin. Thanks!
