### ISSUE TITLE
Attempt to reconnect silently

### ISSUE THREAD

**Issue by jgeboski** [jgeboski/purple-facebook#186]
The plugin should attempt to reconnect silently after being disconnect by Facebook. Typically, when Facebook disconnects the plugin, the plugin is able to reconnect immediately after. I can only assume this is some sort of load balancing, after all this is a mobile platform. It has also been reported that logging out on the Facebook website causes the MQTT stream to be closed as well (#171). I can only assume there are other actions which trigger the MQTT stream to die as well. Pidgin will automatically reconnect the plugin after such a disconnection as of [50bb40c][c1], but the user sees an error. While these issues are trivial and low priority, the plugin could be more streamlined by providing a reconnection mechanism in the background.

We are able to keep track of the previous sequence identifier, which will allow us to pick up where we left off with the MQTT stream. In addition, we can queue the outbound MQTT messages, and ensure they are sent once the connection is reestablished. This should allow for such a reconnection mechanism to be easily implemented.

[c1]: https://bitbucket.org/pidgin/main/commits/50bb40c42245618dc0a2cc92901905c701ad9f58

**Comment by redhead** [comment]
Does this relate to a situation, where I start up my computer from sleep mode, so it lost connection to facebook? It does not reconnect by itself, but I have to manually disable the account and enable it again for it to work. It's pretty irritating

**Comment by jgeboski** [comment]
@redhead no. This issue has already been resolved in the latest version, please update.

**Comment by rrthomas** [comment]
This would be great to have: it's a minor distraction that my Pidgin tray icon keeps cycling through connected and connecting, purely because of the Facebook plugin.

**Comment by jgeboski** [comment]
This has been resolved as of [45f10c2](https://bitbucket.org/pidgin/main/commits/45f10c23412ded435f9f859e10a9ebf226c01356), which is in the latest release.
