### ISSUE TITLE
New default location of pidgin install on windows

### ISSUE THREAD

**Issue by ricardorms** [jgeboski/purple-facebook#189]
"This version of Pidgin downloads an appropriate version of GTK+. GTK+ is now installed locally for Pidgin, and not system-wide" so replace the according instructions 
https://github.com/jgeboski/purple-facebook/wiki/Installing-on-Windows
Download libjson-glib-1.0.dll to C:\Program Files\Pidgin  -> replace with C:\Users\Username\AppData\Roaming\Microsoft\Windows\Pidgin\
Download libfacebook.dll to C:\Program Files\Pidgin\plugins -> replace with C:\Users\Username\AppData\Roaming\Microsoft\Windows\Pidgin\plugins

**Comment by EionRobb** [comment]
Try reinstalling pidgin by right-clicking on the installer exe and choosing "Run as Administrator". That should install it system-wide

**Comment by ricardorms** [comment]
@EionRobb i know how to install pidgin for system-wide, but I'm suggesting, as the default behavior for new installations is to install for a single user, that tutorial's be updated, or at least have the 2 options(system wide and single user installations). Just a suggestion though.
