### ISSUE TITLE
Account consistently disconnects and fails to connect until disable/re-enable

### ISSUE THREAD

**Issue by liamrosen** [jgeboski/purple-facebook#191]
See Jing video for more details:
<snip>

**Comment by jgeboski** [comment]
What [version](https://github.com/jgeboski/purple-facebook/wiki#how-do-i-check-the-current-plugin-version) of the plugin are you running?

**Comment by liamrosen** [comment]
I was running 20151018~a418f60~6a0a79182ebc~24. Just installed the latest (I wasn't aware the plugin was updated often, so I never checked). It's possible that fixes it, so you can close for now. 

Thank you for the rapid response.

**Comment by jgeboski** [comment]
Try updating to the latest version, there have been a slew of connection related patches since your version.

**Comment by jgeboski** [comment]
Any update on this issue?

**Comment by liamrosen** [comment]
James, seems to be working great now. Thanks.
