### ISSUE TITLE
Wrong password still can login

### ISSUE THREAD

**Issue by stevenshiau** [jgeboski/purple-facebook#193]
Recently I accidentally found that even if I enter the wrong password, I can still use pidgin with purple-facebook plugin to login Facebook messenger. I am sure there is no other Facebok login on another device or browser. There is only one login for this case. I do not choose to save the password in my Pidgin preference.
This issue is reproducible on Ubuntu 14.04 with purple-facebook versions
20151225~fb34f49~1852eb9052a0~94
and
20160107~9e20dc9~ad2ee74b913a~97
I also tested the same thing on my Windows machine, and got the same results. Wrong password still can login.
My coworker also confirmed this issue on his Linux box.
Is it due to password cache, or?

Steven.

**Comment by dequis** [comment]
The password is only used for the first login, it uses access tokens afterwards.

**Comment by stevenshiau** [comment]
Got it. Thank you. In that case the program should not not prompt the user to enter the password in the next login.
BTW, is that possible to ask password every time without using the tokens afterwards?

Steven.

**Comment by jgeboski** [comment]
It is possible, but not really ideal. This would require that we generate new unique identifiers and reauthenticate every time, which would only delay the login process even more. There is also no need to "spam" the Facebook side of things with new sessions, when we already have a perfectly valid session. The only time we would need to use the Password again, is when the user logs out of all active sessions (via the Facebook website), which requires the plugin to reauthenticate. This is the main reason the plugin does employ the `OPT_PROTO_NO_PASSWORD` flag.
