### ISSUE TITLE
Empathy

### ISSUE THREAD

**Issue by arakan94** [jgeboski/purple-facebook#194]
Hi! I was wondering, if you could make a version for Empathy..

**Comment by EionRobb** [comment]
You can use it on Empathy via the telepathy-haze transport

**Comment by dragynbane222** [comment]
Theoretically, you can use it with said transport, yes. But this is only possible when you have a configuration widget to add the account, as it stands, that only exists for Sailfish OS as a plugin which can be used on KDE and their IM client, but not Gnome and Empathy. so this was never actually resolved as far as I can tell.
