### ISSUE TITLE
Display "seen" state for sent messages

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#195]
Messenger and the Facebook website support the "seen" functionality. Is this possible in Pidgin?

**Comment by dequis** [comment]
No, it's not possible, libpurple doesn't have an API for that, sorry.

**Comment by jkufner** [comment]
@dequis Could you please file a feature request to libpurple, so it may be possible in future?

**Comment by copycat-killer** [comment]
@dequis @jgeboski Any news on the feature request to libpurple, or how ca we file it?

**Comment by dequis** [comment]
https://developer.pidgin.im/newticket

**Comment by marsjaninzmarsa** [comment]
@copycat-killer: see majn/telegram-purple#251
