### ISSUE TITLE
Missing software license

### ISSUE THREAD

**Issue by h3xx** [jgeboski/purple-facebook#198]
Looks like your repo doesn't explicitly state its licensing terms.

Might I suggest:
* GPLv3
* or MIT

**Comment by jgeboski** [comment]
As stated in the [COPYING](https://github.com/jgeboski/purple-facebook/blob/master/COPYING) file, the project is licensed under GPLv2. This is the same license used by Pidgin itself, as well as the same license that some of the origainal work is based on ([jgeboski/bitlbee-facebook](https://github.com/jgeboski/purple-facebook)).

There is additional copying right information contained in `COPYING` and `COPYRIGHT` inside of the `pidgin` directory. This directory will only be created after the `./update.sh` or `./autogen.sh` script is run. Alternatively, you can use one of the source tarballs, which will contains these files.
