### ISSUE TITLE
How to update git repo?

### ISSUE THREAD

**Issue by PorcelainMouse** [jgeboski/purple-facebook#201]
I've been using this plugin for almost a year and I've rebuilt it several times, so I thought I knew how to do it.  My last build was 6a0a79182ebc and I'm still using it.  But after 'git fetch', 'git pull', 'autogen.sh', and 'make', the build fails and I cannot figure out how to restart.

I had to start all over with 'git clone'.  Is that right?  What is the proper way to update git working copy from a previous build?

**Comment by dequis** [comment]
>the build fails

Error messages?

What you did was right.

**Comment by jkufner** [comment]
Examine `git log --all --graph` and compare it to log on Github. Maybe you've created some unwanted merges when fetching or mixed in some minor changes. I recommend setting `git config --global pull.ff only` to prevent such mistakes in future; it sets `--ff` as default to git pull. You may try `make clean` too.

**Comment by PorcelainMouse** [comment]
Hmm, okay.  I'll try it again that way next time.  No problem.

In short, build failed at "libcompat.h not found", although it was clearly there.  And git pull was a fast-forward.  At some point, however, protocols/facebook/Makefile gets clobbered, though, and then 'make clean' was breaking.  That's where I got stuck.  But, here is the whole thing, if you are interested.

$ git pull
Updating 4f84a8a..909c36b
Fast-forward
 .travis.yml                                  |  49 ++++++--
 .travis/key                                  | Bin 0 -> 1680 bytes
 .travis/obs.sh                               |  50 ++++++++
 .travis/win32-build.sh                       |  13 +++
 .travis/win32-deploy.sh                      |  11 ++
 .travis/win32-install.sh                     |  24 ++++
 ChangeLog                                    |  36 ++++++
 Makefile.am                                  |   4 +-
 Makefile.mingw                               |   6 +-
 VERSION                                      |   2 +-
 autogen.sh                                   |   2 +-
 configure.ac                                 |   5 +-
 debian/changelog                             |   2 +-
 debian/control                               |   4 +-
 debian/copyright                             |   2 +-
 include/internal.h                           |   2 +-
 include/purple-compat.h                      |   6 +-
 patches/01-makefile.patch                    |  19 +--
 patches/02-glibcompat.patch                  |  37 ++++++
 patches/03-http-leaks.patch                  |  12 --
 patches/{02-plugin.patch => 03-plugin.patch} | 347 ++++++++++++++++++++++++++++++-------------------------
 update.sh                                    |  15 +--
 22 files changed, 436 insertions(+), 212 deletions(-)
 create mode 100644 .travis/key
 create mode 100755 .travis/obs.sh
 create mode 100755 .travis/win32-build.sh
 create mode 100755 .travis/win32-deploy.sh
 create mode 100755 .travis/win32-install.sh
 create mode 100644 patches/02-glibcompat.patch
 delete mode 100644 patches/03-http-leaks.patch
 rename patches/{02-plugin.patch => 03-plugin.patch} (64%)
$ ./autogen.sh 
pulling from https://hg.pidgin.im/soc/2015/jgeboski/facebook
searching for changes
all local heads known remotely
adding changesets
adding manifests
adding file changes
added 68 changesets with 147 changes to 79 files (+1 heads)
(run 'hg heads' to see heads)
abort: unknown revision '25a255f32eee'!
patching file libpurple/protocols/facebook/Makefile.am
Hunk #2 FAILED at 62.
1 out of 2 hunks FAILED -- saving rejects to file libpurple/protocols/facebook/Makefile.am.rej
patching file libpurple/protocols/facebook/Makefile.mingw
Hunk #2 succeeded at 64 (offset -1 lines).
Hunk #3 succeeded at 77 (offset -1 lines).
patching file libpurple/glibcompat.h
Hunk #1 succeeded at 192 with fuzz 2 (offset 131 lines).
patching file libpurple/protocols/facebook/facebook.c
Hunk #2 succeeded at 825 (offset -39 lines).
Hunk #3 succeeded at 1018 (offset -32 lines).
Hunk #4 succeeded at 1066 (offset -32 lines).
Hunk #5 succeeded at 1076 (offset -32 lines).
Hunk #6 succeeded at 1216 (offset -32 lines).
Hunk #7 succeeded at 1228 (offset -32 lines).
Hunk #8 succeeded at 1398 (offset -32 lines).
Hunk #9 succeeded at 1528 (offset -36 lines).
patching file libpurple/protocols/facebook/facebook.h
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] n
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file libpurple/protocols/facebook/facebook.h.rej


$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/<username>/local/src/purple-facebook/build-aux/missing aclocal-1.15 -Im4
 cd . && /bin/sh /home/<username>/local/src/purple-facebook/build-aux/missing automake-1.15 --gnu
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/<username>/local/src/purple-facebook/build-aux/missing autoconf
/bin/sh ./config.status --recheck
running CONFIG_SHELL=/bin/sh /bin/sh ./configure --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for JSON... yes
checking for PURPLE... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/sh ./config.status
config.status: creating Makefile
config.status: creating pidgin/libpurple/protocols/facebook/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in pidgin/libpurple/protocols/facebook
make[1]: Entering directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
  GEN      marshal.h
  GEN      marshal.c
  CC       libfacebook_la-marshal.lo
  CC       libfacebook_la-api.lo
api.c:26:24: fatal error: glibcompat.h: No such file or directory
compilation terminated.
Makefile:547: recipe for target 'libfacebook_la-api.lo' failed
make[1]: *** [libfacebook_la-api.lo] Error 1
make[1]: Leaving directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
Makefile:463: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

$ make
Making all in pidgin/libpurple/protocols/facebook
make[1]: Entering directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
  CC       libfacebook_la-api.lo
api.c:26:24: fatal error: glibcompat.h: No such file or directory
compilation terminated.
Makefile:547: recipe for target 'libfacebook_la-api.lo' failed
make[1]: *** [libfacebook_la-api.lo] Error 1
make[1]: Leaving directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
Makefile:463: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
$ make clean
Making clean in pidgin/libpurple/protocols/facebook
make[1]: Entering directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
test -z "marshal.c marshal.h" || rm -f marshal.c marshal.h
rm -rf .libs _libs
rm -rf ../../.libs ../../_libs
test -z "" || rm -f 
test -z "libfacebook.la" || rm -f libfacebook.la
rm -f ./so_locations
rm -f *.o
rm -f ../../*.o
rm -f ../../*.lo
rm -f *.lo
make[1]: Leaving directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
make[1]: Entering directory '/home/<username>/local/src/purple-facebook'
rm -rf .libs _libs
rm -f *.lo
make[1]: Leaving directory '/home/<username>/local/src/purple-facebook'
$ make
Making all in pidgin/libpurple/protocols/facebook
make[1]: Entering directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
  GEN      marshal.h
  GEN      marshal.c
  CC       libfacebook_la-marshal.lo
  CC       libfacebook_la-api.lo
api.c:26:24: fatal error: glibcompat.h: No such file or directory
compilation terminated.
Makefile:547: recipe for target 'libfacebook_la-api.lo' failed
make[1]: *** [libfacebook_la-api.lo] Error 1
make[1]: Leaving directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
Makefile:463: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

$ ./autogen.sh 
pulling from https://hg.pidgin.im/soc/2015/jgeboski/facebook
searching for changes
no changes found
abort: unknown revision '25a255f32eee'!
patching file libpurple/protocols/facebook/Makefile.am
Hunk #2 FAILED at 62.
1 out of 2 hunks FAILED -- saving rejects to file libpurple/protocols/facebook/Makefile.am.rej
patching file libpurple/protocols/facebook/Makefile.mingw
Hunk #2 succeeded at 64 (offset -1 lines).
Hunk #3 succeeded at 77 (offset -1 lines).
patching file libpurple/glibcompat.h
Hunk #1 succeeded at 192 with fuzz 2 (offset 131 lines).
patching file libpurple/protocols/facebook/facebook.c
Hunk #2 succeeded at 825 (offset -39 lines).
Hunk #3 succeeded at 1018 (offset -32 lines).
Hunk #4 succeeded at 1066 (offset -32 lines).
Hunk #5 succeeded at 1076 (offset -32 lines).
Hunk #6 succeeded at 1216 (offset -32 lines).
Hunk #7 succeeded at 1228 (offset -32 lines).
Hunk #8 succeeded at 1398 (offset -32 lines).
Hunk #9 succeeded at 1528 (offset -36 lines).
patching file libpurple/protocols/facebook/facebook.h
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] n
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file libpurple/protocols/facebook/facebook.h.rej
$ make
Making all in pidgin/libpurple/protocols/facebook
make[1]: Entering directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
Makefile:463: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
$ make clean
Making clean in pidgin/libpurple/protocols/facebook
make[1]: Entering directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/home/<username>/local/src/purple-facebook/pidgin/libpurple/protocols/facebook'
Makefile:463: recipe for target 'clean-recursive' failed
make: *** [clean-recursive] Error 1

**Comment by jgeboski** [comment]
Your source tree is severely broken. Try fixing it:

```
git clean -dfxe .pidgin
git reset --hard
./autogen.sh
```

**Comment by PorcelainMouse** [comment]
Thanks for your continued help, @jgeboski.

Yeah, clearly.  I'm just confused how that happened, though.  I only ran git, autogen.sh, and make.  No worries, though, I'll try it next time and let you know if it happens again.  I already blew away the old working dir.  Just wanted to make sure I had the right approach from the wiki.

Thanks for the git clean w/ option suggestion.  I assumed that git clean would work, but wouldn't be much better than re-clone since the bulk of code comes from hg.  But, saving .pidgin/ would have cut way down on the download time.  Much appreciated.
