### ISSUE TITLE
hello.c libpurple and getting Timeout reached for request

### ISSUE THREAD

**Issue by tomwolfgang** [jgeboski/purple-facebook#205]
On my machine, using pidgin (using the same libpurple.dll) it is working.

Using the hello.c (http://libpurple.com/) it fails with:

libpurple version: 2.10.7
Glib:2.28.8

Connecting to account XXX
Connecting. gc = 02836FB8
Performing new request 02841E80 to b-api.facebook.com.
Performing DNS lookup for b-api.facebook.com
IP resolved for b-api.facebook.com
Attempting connection to 31.13.90.37
Connecting to b-api.facebook.com:443 with no proxy
Connection in progress
Connecting to b-api.facebook.com:443.
Connected to b-api.facebook.com:443.
subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=CA,C=US issuer=CN=DigiCert High Assurance CA-3,OU=www.digicert.com,O=DigiCert Inc,C=US
subject=CN=DigiCert High Assurance CA-3,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
partial certificate chain
Starting verify for b-api.facebook.com
Checking for cached cert...
...Found cached cert
Loading certificate from ...certificates\x509\tls_peers\b-api.facebook.com
Peer cert matched cached
Exporting certificate to ...\certificates\x509\tls_peers\b-api.facebook.com
Writing file ...\certificates\x509\tls_peers\b-api.facebook.com
Successfully verified certificate for b-api.facebook.com
Writing file prefs.xml to directory ...
Writing file ...\prefs.xml
Writing file accounts.xml to directory ...
Writing file ...\accounts.xml

Timeout reached for request 02841E80
Request 02841E80 performed without success.
Connection error on 02836FB8 (reason: 0 description: Unknown HTTP error)

Disconnecting account XXX (00D07F50)
Disconnecting connection 02836FB8
Destroying connection 02836FB8
Writing file accounts.xml to directory ...
Writing file ...\accounts.xml

**Comment by tomwolfgang** [comment]
It's on windows

**Comment by dequis** [comment]
Works for me. Try using a libpurple version that isn't ancient.

**Comment by jgeboski** [comment]
Any update on this?

**Comment by dequis** [comment]
I'd just close it because it works with pidgin for OP, this is unlikely to be a bug on our side.

**Comment by tomwolfgang** [comment]
Tried with a new version - doesn't work either.
This is what I'm calling:

  PurpleAccount *account = purple_account_new("email@domain.com", "prpl-facebook");
  purple_account_set_password(account, "password");
  purple_accounts_add(account);
  purple_account_set_enabled(account, UI_ID, TRUE);

**Comment by jgeboski** [comment]
What version of the plugin?

**Comment by tomwolfgang** [comment]
20160126~e30dc45~92885e0456ed~106

**Comment by jgeboski** [comment]
Does it work via pidgin?

**Comment by tomwolfgang** [comment]
Yes it does - the same dll and all.

**Comment by jgeboski** [comment]
I honestly have no idea, nor do I have the time to help debug other clients, sorry. :(

**Comment by tomwolfgang** [comment]
Might be stuck because libpurple is trying to connect with TLS 1.0 and not 1.2?
Any ideas how to set it to 1.2?

Maybe with purple_plugins_find_with_id("ssl-nss"); and somehow setting the TLS level as a pref?

Thanks
