### ISSUE TITLE
no notification for new messages in groupchats

### ISSUE THREAD

**Issue by mightyBroccoli** [jgeboski/purple-facebook#207]
I am using the plugin on my windows maschine with the newest pidgin installed everything works fine. Recieving messages works perfectly and in a normal chat I get the notification (blinking in the tastkbar or stuff) and the optional bell.
In Groupchats I do not get these. I testend on a clean device with fresh installed piding and just this plugin, no sound no notification. What am I doing wrong ? Am I even right here to ask this?

**Comment by EionRobb** [comment]
The built-in Pidgin plugin, Message Notification, lets you configure the alerts for this.
![message notification screenshot](https://cloud.githubusercontent.com/assets/1063865/12796818/a7f6a3c2-cb25-11e5-9d05-60a968bf84f5.png)
