### ISSUE TITLE
Group chat title should be the group name, not the id

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#208]
Currently, the title of a group chat is the Facebook id. Can this be the group name instead?

**Comment by EionRobb** [comment]
Unfortunately libpurple needs group names to be the internal id number for libpurple to know where to send the message to, eg from Pidgin.  You could save the chat to your buddy list and alias it though

**Comment by jgeboski** [comment]
The plugin has no control over this.
