### ISSUE TITLE
./configure --prefix= doesn't seem to work

### ISSUE THREAD

**Issue by mxmlnkn** [jgeboski/purple-facebook#209]
I tried to do:

    ./configure --prefix=$HOME/.purple/plugins/
    make
    make install

But i get an error message which indicates that the prefix is ignored:

    /usr/bin/install: cannot create regular file '/usr/lib/purple-2/libfacebook.so': Permission denied

Note that I already did a `sudo make install` without a prefix and after that I manually moved `libfacebook.la` and `libfacebook.so` from `/usr/lib/purple-2/` to `$HOME/.purple/plugins` and it worked. I only wanted to automatize that process using a prefix and noticed that it didn't seem to work

**Comment by dequis** [comment]
https://github.com/jgeboski/purple-facebook/wiki/Building-on-*NIX#local-installation-to-your-user-home

> ```
$ mkdir -p ~/.purple/plugins
$ cp pidgin/libpurple/protocols/facebook/.libs/libfacebook.so ~/.purple/plugins
```

**Comment by mxmlnkn** [comment]
Ok, sorry my fault. I only skimmed over the Readme.md.
But I still think a working prefix would be a nice feature to have to allow standard installation procedure.

**Comment by jgeboski** [comment]
Use `--with-plugindir=...`. The prefix means nothing to autoconf in this case as this is a module, not a library. As a result, autoconf must rely on pkg-config to define the plugin directory, which may differ from system-to-system.
