### ISSUE TITLE
names display as numbers in bitlbee

### ISSUE THREAD

**Issue by Miesco** [jgeboski/purple-facebook#210]
In bitlbee, the names show as numbers:

> 06:53am <  _533115958> | [2016-02-08 23:23:23] love it!

Is this a purple-facebook issue?  The names show with pidgin (using purple-facebook).

I have bitlbee 3.2.2; libpurple 2.10.11; I am on debian Jessie; irssi 0.8.17.

Let me know if you need any more information.

**Comment by dequis** [comment]
You probably want to use bitlbee-facebook instead.

**Comment by cheronobyl** [comment]
Would you mind sharing the fix you found? I am having the same issue with the same parameters.

**Comment by dequis** [comment]
@cheronobyl Using bitlbee? Why not use bitlbee-facebook? The fix is probably along the lines of nick_format, but please don't use this plugin with bitlbee.

**Comment by cheronobyl** [comment]
I had thought purple-facebook had extended functionality, but I appear to have been wrong. I switched over to bitlee-facebook yesterday and it works flawlessly, thanks!
