### ISSUE TITLE
Windows releases

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [jgeboski/purple-facebook#212]
Seems like there's some changes on travis-ci, do you know where are the windows releases now?

**Comment by dequis** [comment]
https://github.com/jgeboski/purple-facebook/wiki/Installing-on-Windows links to https://dl.voidium.net/pidgin/libfacebook.dll

**Comment by ZatsuneNoMokou** [comment]
Oh true, sorry didn't read well I guess
