### ISSUE TITLE
"Failed to parse thread information"

### ISSUE THREAD

**Issue by AkelD** [jgeboski/purple-facebook#214]
I've been getting this error for a few days now. The process is always the same: Pidgin manages to connect for half a second or so (I can get to see the connected contacts) and then it disconnects, giving me the error and giving the reconnect and modify account options. Any idea of why it could be happening?

**Comment by jgeboski** [comment]
Please send me a [debugging log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs).

**Comment by cubantek** [comment]
I had the same issue.  It was trying to send a group message that the name was later changed.  I also had other messages that tried popping up right before I got the error and it look like pigin signed me out and had the error Failed to parse thread.  I had to go into facebook and read all messages. Then I was able to go back to Pigin and that error when away and working fine now.  I hope that helps.

**Comment by AkelD** [comment]
I've been trying to replicate the error in pidgin itself (Rather than pidgin portable, since I haven't been able to find how to save the debug logs for that one) and its being impossible, as the error doesn't seem to be happening there at all.
  ----- Original Message -----

**Comment by arnoldkao** [comment]
I had this problem just now on Windows, then I removed from AppData\Roaming\.purple\blist.xml a Facebook group chat of which I'm no longer a member, and I'm able to log in (and stay logged in) again.

**Comment by AkelD** [comment]
Thanks! that solved it.
  ----- Original Message -----

**Comment by jgeboski** [comment]
Has this issue reappeared at all or is it resolved?

**Comment by AkelD** [comment]
Completely resolved. Sorry fortaking so long to answer.

**Comment by acli** [comment]
How do you find out which group chat should be removed? I’m having the same issue (on Linux).

**Comment by tsdmgz** [comment]
@acli Had the same issue, tried grepping my whole `.purple` folder for the number it gave (chat ID?) but no hits, ended up trashing the whole file instead (renamed it to blist.xml.old). Aside from Pidgin complaining on next startup about a bad blist.xml, I don't see negative effects so far?

Don't rename it to blist.xml~, that's the filename Pidgin does when it tried to back up mine before creating a new one.

**Comment by smeagolthellama** [comment]
same problem, linux, sollution does not work.

**Comment by brianfreud** [comment]
I was still having this problem, even with clearing out blist.xml.  The fix turned out to be simple; load facebook.com and in the messages dropdown up top, click "mark all read", then reconnect in pidgin.
