### ISSUE TITLE
just a note on the installation instructions:

### ISSUE THREAD

**Issue by dadacetacean** [jgeboski/purple-facebook#217]
for installing from git: the first command should be

`$ git clone https://github.com/jgeboski/purple-facebook`

so without the `.git` at the end; it gave me an error (ubuntu)

**Comment by dequis** [comment]
What error?

**Comment by dadacetacean** [comment]
github returned fatal: repository not found

**Comment by dequis** [comment]
What ubuntu version? What git version?

**Comment by dequis** [comment]
I tried with ubuntu 12.04 and it works both ways. I'll assume it's just a temporary server issue.
