### ISSUE TITLE
FB users no longer in "new message" type ahead

### ISSUE THREAD

**Issue by jaymzh** [jgeboski/purple-facebook#219]
In the last few days I noticed that when I do ^m for new message and start typing in a friend's name, FB users don't show up in the type ahead list...

**Comment by jgeboski** [comment]
I cannot recreate this on my end. Are you using any third party plugins? If you enable the display of offline buddies, do they show in the buddy list?

**Comment by jaymzh** [comment]
It works this morning. Maybe it was an FB-side thing - didn't work on 3 different machines for me for 2 days...

**Comment by jgeboski** [comment]
Weird. The only thing I can think of is that the query for contacts was returning less than it should be. But I do not know for sure. Re-open if the issue returns. Hopefully you can get a [debugging log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs) if it does.
