### ISSUE TITLE
Limit to buddies?

### ISSUE THREAD

**Issue by Akiryx** [jgeboski/purple-facebook#220]
I've noticed that for some reason I appear to be limited to only 200 Facebook Friends, which is a problem as several that I talk to regularly do not show up in my contact list. I'm unsure if this is a problem with Pidgin or this Plugin, but as I could find no settings for this anywhere within Pidgin, I am hoping this plugin is responsible, so that it could be changed.

**Comment by jgeboski** [comment]
What [version](https://github.com/jgeboski/purple-facebook/wiki#how-do-i-check-the-current-plugin-version) of the plugin are you running?

**Comment by Akiryx** [comment]
Unsure, let me update it. It's strange though I didn't used to have this problem so not sure what the deal is.

**Comment by Akiryx** [comment]
Okay, I updated it, that fixed it completely. Thank you!
