### ISSUE TITLE
apt line issues 

### ISSUE THREAD

**Issue by technomooney** [jgeboski/purple-facebook#222]
the way the apt line is formed in the "Package Repositories" section on the site you tell us how to get the *NIX version of the plugin is not working for ubuntu 15.04 and even when i re work it so it will accept it it seems it still cant find it as it throughs a 404 error 

that said upon looking at the repositories dir on http://download.opensuse.org/  aka http://download.opensuse.org/repositories/, the dir ./home does not exist it, i find that there is nothing that suggests this site has your repo on there so i would like it if you can update me on where i can get the pre-built binaries for linux. 

edit: i also cant really build or i really dont want to set up my laptop that was built when vista was mainstream as it really is a hassle.. and its not all that powerful 
if you need more info as to what i got for an error and how i typed the apt line let me know

**Comment by technomooney** [comment]
i had not put a ":" so the "home:/ was not there

**Comment by technomooney** [comment]
nope it still doenst like it
i put this in the *.list 
`deb http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_15.04/`

and this is what i get from apt-get

`marty@marty-Aspire-5100:~$ sudo apt-get update
E: Malformed line 1 in source list /etc/apt/sources.list.d/jgeboski.list (dist)
E: The list of sources could not be read.`

when we type it in a way that apt-get will like 
`deb http://download.opensuse.org/repositories/home:/ jgeboski xUbuntu_15.04` 

i get this 
`W: Failed to fetch http://download.opensuse.org/repositories/home:/dists/jgeboski/xUbuntu_15.04/binary-amd64/Packages  404  Not Found [IP: 2001:67c:2178:8::13 80]

W: Failed to fetch http://download.opensuse.org/repositories/home:/dists/jgeboski/xUbuntu_15.04/binary-i386/Packages  404  Not Found [IP: 2001:67c:2178:8::13 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by technomooney** [comment]
at the moment i just used the repo's web interface to download the appropriate deb file

**Comment by jgeboski** [comment]
You did not copy step one correctly. You are missing a `./` at the end of the `deb` line.

**Comment by technomooney** [comment]
ok well i did that previously.. but didnt know there was a space that was needed in between the `./

**Comment by jgeboski** [comment]
Has this issue been resolved?

**Comment by technomooney** [comment]
yea sorry forgot to close
