### ISSUE TITLE
Cannot find facebook.c

### ISSUE THREAD

**Issue by alexui** [jgeboski/purple-facebook#224]
Hello guys, I have recently discovered this plugin as I am starting a similar project for Android. I am not a professional. Please help me find "libpurple/protocols/facebook/facebook.c" - the file that is mentioned in patches/03-plugin.patch as I suppose the lines in this file are the core for this plugin.

**Comment by dequis** [comment]
You might want to download this instead https://github.com/jgeboski/purple-facebook/releases/download/92885e0456ed/purple-facebook-92885e0456ed.tar.gz

**Comment by jgeboski** [comment]
Look at the source tarball @dequis linked, or the upstream development [sources](https://bitbucket.org/pidgin/main/src/3cf4744a9521349f341ce9f953403d3828c0de96/libpurple/protocols/facebook/?at=default).
