### ISSUE TITLE
Facebook names not shown when using purple-facebook with spectrum

### ISSUE THREAD

**Issue by ChStoltz** [jgeboski/purple-facebook#225]
Is there any way to get the real facebook names of my contacts? Right now, it only shows numbers (like ICQ UIN) in my buddy list. I'm using ejabberd 16.01 with spectrum 2.02 and purple-facebook via git and tried different clients. 
In the logs I can see, the vCard with the Photo coming in, but no real names.

**Comment by vitalyster** [comment]
Please add your facebook transport jid to roster "managers": https://www.process-one.net/docs/ejabberd/guide_en.html#htoc61

**Comment by ChStoltz** [comment]
I added facebook.jabjab.de as manager to mod_roster, and restarted the server but no effect.

**Comment by vitalyster** [comment]
It may need to remove your registration and register again, as buddies with empty names are already in spectrum db

**Comment by ChStoltz** [comment]
EDIT: Problem solved. After deleting the contact, logout and login, the contact reappeart, with its actual name.

**Comment by jgeboski** [comment]
Thanks @vitalyster.
