### ISSUE TITLE
Linux mint 17.3 x64 Cinnamon

### ISSUE THREAD

**Issue by iTpain** [jgeboski/purple-facebook#229]
Hi there i did try to install this on my system and the protocol dose not show up on my list  i did like this 

added the source list

deb http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_14.04 ./ 

Installed the package 

sudo apt-get install purple-facebook

everything was ok in terminal and i did restarted pidgin but did not show the new protocol

**Comment by iTpain** [comment]
Well my mistake , after i restarted the notebook is working :) good job with this plugin you should add it to their list of plugins / protocols so more users will use it :)

**Comment by dequis** [comment]
yay
