### ISSUE TITLE
FB Contact list not being retrieved 

### ISSUE THREAD

**Issue by dicecollector** [jgeboski/purple-facebook#23]
I installed the plugin to replace the FB XMPP protocol and so far it is working well ... BUT ... it does not retrieve my FB contact list ... as such ... I can only reply to messages ... unless I lookup the FB users full userid and use New Instant Message ... which is more trouble than using FB to send the message 

OS: Windows 7 PRO SP1 ... latest Patchset 

Pidgin version : 2.10.11

Instructions followed for plugin installation 
      https://github.com/jgeboski/purple-facebook#installing-on-windows

Has anyone run into this?

**Comment by jgeboski** [comment]
I will need sensitive debugging information in order to dig deeper.  If you do not feel comfortable with sending the debug information to me, then discard the following instructions.

1. Open `Help => Debug Window` on the `Buddy List` window
2. Quit Pidgin with `Debug` window open
3. Open `Command Prompt` and run the following commands:
  1. `set PURPLE_UNSAFE_DEBUG=1`
  2. `set PURPLE_VERBOSE_DEBUG=1`
  3. `pidgin`
4. Recreate the issue with the `Debug` window open
5. Click `Save` in the `Debug` window
6. Send the log to me via [email](mailto:jgeboski@gmail.com)

**Comment by dicecollector** [comment]
Hi James

Thank you for the prompt response

I work for Oracle Support ... so Debugging is my life :)

Here is the debug file

Should I unset the debug parameters that were set at the OS level? ... if
so .. will setting them back to 0 be sufficient?

On Sun, Jul 12, 2015 at 12:47 PM, James Geboski <notifications@github.com>
wrote:

> I will need sensitive debugging information in order to dig deeper. If you
> do not feel comfortable with sending the debug information to me, then
> discard the following instructions.
>
>    1. Open Help => Debug Window on the Buddy List window
>    2. Quit Pidgin with Debug window open
>    3. Open Command Prompt and run the following commands:
>       1. set PURPLE_UNSAFE_DEBUG=1
>       2. set PURPLE_VERBOSE_DEBUG=1
>       3. pidgin
>     4. Recreate the issue with the Debug window open
>    5. Click Save in the Debug window
>    6. Send the log to me via email <jgeboski@gmail.com>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120753788>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by jgeboski** [comment]
They variables are only set for the lifetime of the session, so once you close command prompt, they are gone.  I did not get the log as you will have to send it to my personal email (jgeboski@gmail.com).

**Comment by jgeboski** [comment]
Well, it does look like it is skipping or silently failing the HTTP request for contacts.  I really need to add in some more debugging output.  But I have many other things (homework for summer class) in the way of doing that today, though.

In the meantime, you can try re-adding the account to clear out the session stuff, *maybe* that will have an effect.  You can also try disabling any of the proxy stuff.  I does not look like the Facebook stuff is going through it, but it might somehow be messing it up.  Also, I can only assume you are on the latest release, but it might be wise to ensure you are.

**Comment by dicecollector** [comment]
Hi James

On Sun, Jul 12, 2015 at 1:53 PM, James Geboski <notifications@github.com>
wrote:

> Well, it does look like it is skipping or silently failing the HTTP
> request for contacts. I really need to add in some more debugging output.
> But I have many other things (homework for summer class) in the way of
> doing that today, though.
>

No worries


> In the meantime, you can try re-adding the account to clear out the
> session stuff, *maybe* that will have an effect.
>

Do you mean drop the existing FB entry (account for FB)  ... then add it
back? ... or create a duplicate account entry in pidgin?


> You can also try disabling any of the proxy stuff.
>
That is part of the problem I need it to work with the Oracle proxy ... as
well as No Proxy ... and I am not using a proxy at present ... and the list
is not being retrieved :(



> I does not look like the Facebook stuff is going through it, but it might
> somehow be messing it up. Also, I can only assume you are on the latest
> release, but it might be wise to ensure you are.
>

Yes .. Pidgin 2.10.11 (libpurple 2.10.11) e38a9aa5b1f8 ... is the latest
version according to Pidgin


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120756741>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by dicecollector** [comment]
I dropped the Pidgin account kevin.cook.9250595 ... then re-added it ...
and did not mess with Proxy ... I am seeing the same results :(

I have attached a new debug log

On Sun, Jul 12, 2015 at 4:33 PM, Kevin Cook <dicecollector@gmail.com> wrote:

> Hi James
>
> On Sun, Jul 12, 2015 at 1:53 PM, James Geboski <notifications@github.com>
> wrote:
>
>> Well, it does look like it is skipping or silently failing the HTTP
>> request for contacts. I really need to add in some more debugging output.
>> But I have many other things (homework for summer class) in the way of
>> doing that today, though.
>>
>
> No worries
>
>
>> In the meantime, you can try re-adding the account to clear out the
>> session stuff, *maybe* that will have an effect.
>>
>
> Do you mean drop the existing FB entry (account for FB)  ... then add it
> back? ... or create a duplicate account entry in pidgin?
>
>
>> You can also try disabling any of the proxy stuff.
>>
> That is part of the problem I need it to work with the Oracle proxy ... as
> well as No Proxy ... and I am not using a proxy at present ... and the list
> is not being retrieved :(
>
>
>
>> I does not look like the Facebook stuff is going through it, but it might
>> somehow be messing it up. Also, I can only assume you are on the latest
>> release, but it might be wise to ensure you are.
>>
>
> Yes .. Pidgin 2.10.11 (libpurple 2.10.11) e38a9aa5b1f8 ... is the latest
> version according to Pidgin
>
>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120756741>
>> .
>>
>
>
>
> --
> <http://www.dicecollector.com/>
>



-- 
<http://www.dicecollector.com/>

**Comment by jgeboski** [comment]
I was referring to the version of the plugin.  Anyways, I'll get a patch done ASAP for more verbose debugging information.

**Comment by jgeboski** [comment]
Please update to the least version of the plugin ([4098e875ebcb](https://github.com/jgeboski/purple-facebook/releases/tag/4098e875ebcb)), and directly email me [debugging](https://github.com/jgeboski/purple-facebook#debugging) output or a log file.

**Comment by dicecollector** [comment]
Thank you James

From that link ... do I only install the *libfacebook.dll*
<https://github.com/jgeboski/purple-facebook/releases/download/4098e875ebcb/libfacebook.dll>
?

On Sun, Jul 12, 2015 at 9:34 PM, James Geboski <notifications@github.com>
wrote:

> Please update to the least version of the plugin (4098e875ebcb
> <https://github.com/jgeboski/purple-facebook/releases/tag/4098e875ebcb>),
> and directly email me debugging
> <https://github.com/jgeboski/purple-facebook#debugging> output or a log
> file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120798796>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by dequis** [comment]
Yeah, replacing the old one in `C:\Program Files\Pidgin\plugins`

**Comment by dicecollector** [comment]
Hi James

Ok ... I have done that ... BUT ... I am now inside the Oracle firewall ..
and thus am using a proxy ... is it ok to send you the debug now ... or do
I have to wait until I am outside the firewall?

On Mon, Jul 13, 2015 at 4:37 AM, dx <notifications@github.com> wrote:

> Yeah, replacing the old one in C:\Program Files\Pidgin\plugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120887595>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by dequis** [comment]
Well if the issue happens with the firewall/proxy, then debug logs behind the firewall would be useful. His suggestion to disable proxies was just in case the proxy is messing with the traffic in some way, which we don't know for sure. But if you say the problem happens *without* the proxy, then that probably means the proxy is irrelevant.

(I'm not @jgeboski btw)

**Comment by dicecollector** [comment]
HI <sorry I dont know your name>

I have the debug file (see attached) ... but it does not seem to attach
well when I sent it via Github ... Please let me know if I need to send via
a different method



On Mon, Jul 13, 2015 at 4:45 AM, dx <notifications@github.com> wrote:

> Well if the issue happens with the firewall/proxy, then debug logs behind
> the firewall would be useful. His suggestion to disable proxies was just in
> case the proxy is messing with the traffic in some way, which we don't know
> for sure. But if you say the problem happens *without* the proxy, then
> that probably means the proxy is irrelevant.
>
> (I'm not @jgeboski <https://github.com/jgeboski> btw)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120888599>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by dequis** [comment]
I'm dx. Just send it to jgeboski's email address like the last one. And yeah github drops attachments.

**Comment by dicecollector** [comment]
Did you receive it? ... I did sent it to James

On Mon, Jul 13, 2015 at 5:10 AM, dx <notifications@github.com> wrote:

> I'm dx. Just send it to jgeboski's email address like the last one. And
> yeah github drops attachments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120892175>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by rhymeAsylum** [comment]
set PURPLE_UNSAFE_DEBUG=1
set PURPLE_VERBOSE_DEBUG=1

This work for me now I can see my userlist

TYVM

**Comment by dicecollector** [comment]
Hi TYVM

I had those parameters set when I ran the debug

On Mon, Jul 13, 2015 at 7:32 AM, rhymeAsylum <notifications@github.com>
wrote:

> set PURPLE_UNSAFE_DEBUG=1
> set PURPLE_VERBOSE_DEBUG=1
>
> This work for me now I can see my userlist
>
> TYVM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120927131>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by rhymeAsylum** [comment]
Still don't know how to quote in this forum
TYVM stands for thank you very much.
I'm using facebook ID instead of email. No proxy

**Comment by dicecollector** [comment]
HI again

I am using both .. with the same results .. I can send if I open a new
message manually

but I do not see anyone in my facebook contacts

On Mon, Jul 13, 2015 at 8:17 AM, rhymeAsylum <notifications@github.com>
wrote:

> Still don't know how to quote in this forum
> TYVM stands for thank you very much.
> I'm using facebook ID instead of email. No proxy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120942570>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by rhymeAsylum** [comment]
Did you put the plugin into main Pidgin folder and the purple somethig in the plugin folder?

I'm using Pidgin 2.10.9

**Comment by dicecollector** [comment]
I followed these instructions (from James) each time I changed the DLL's as
appropriate


   1. Open Help => Debug Window on the Buddy List window
   2. Quit Pidgin with Debug window open
   3. Open Command Prompt and run the following commands:
      1. set PURPLE_UNSAFE_DEBUG=1
      2. set PURPLE_VERBOSE_DEBUG=1
      3. pidgin
   4. Recreate the issue with the Debug window open
   5. Click Save in the Debug window
   6. Send the log to me via email <jgeboski@gmail.com>

I am using 2.10.11 ... the most current version as suggested


On Mon, Jul 13, 2015 at 8:22 AM, rhymeAsylum <notifications@github.com>
wrote:

> Did you put the plugin into main Pidgin folder and the purple somethig in
> the plugin folder?
>
> I'm using Pidgin 2.10.9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120945827>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by rhymeAsylum** [comment]
I speak about Windows instructions:

Installing on windows

Download: libjson-glib-1.0.dll
Copy the downloaded libjson-glib-1.0.dll to C:\Program Files\Pidgin
Download the latest libfacebook.dll from the releases
Copy the downloaded libfacebook.dll to C:\Program Files\Pidgin\plugins

**Comment by dicecollector** [comment]
Yes .. sorry

That is what I am doing

I am a support senior engineer for Oracle Support (kevin.cook@oracle.com)
... so in general ... you can trust it when I say I am following debug
instructions :)

A new facebook.dll was installed in the C:\Program Files
(x86)\Pidgin\plugins directory today

Does that help?

On Mon, Jul 13, 2015 at 8:26 AM, rhymeAsylum <notifications@github.com>
wrote:

> I speak about Windows instructions:
>
> Installing on windows
>
> Download: libjson-glib-1.0.dll
> Copy the downloaded libjson-glib-1.0.dll to C:\Program Files\Pidgin
> Download the latest libfacebook.dll from the releases
> Copy the downloaded libfacebook.dll to C:\Program Files\Pidgin\plugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120947906>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by jgeboski** [comment]
@dicecollector Yeah, go ahead and email me directly a debug log, even with the proxy present.  As @dx said, either way, it will be helpful to have that log as it should be working behind the proxy.

**Comment by dicecollector** [comment]
Hi David

Here is the log again

On Mon, Jul 13, 2015 at 9:05 AM, James Geboski <notifications@github.com>
wrote:

> @dicecollector <https://github.com/dicecollector> Yeah, go ahead and
> email me directly a debug log, even with the proxy present. As @dx
> <https://github.com/dx> said, either way, it will be helpful to have that
> log as it should be working behind the proxy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120961185>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by jgeboski** [comment]
According to the log it is retrieving the contact list, and it is setting the status for them.  If you show offline buddies, do they appear?  Do you have some sort of plugin breaking things?

**Comment by dicecollector** [comment]
HI James?

On Mon, Jul 13, 2015 at 10:29 AM, James Geboski <notifications@github.com>
wrote:

> According to the log it is retrieving the contact list, and it is setting
> the status for them.
>


> If you show offline buddies, do they appear?
>
That is my normal setting ... so no .. they do not show


> Do you have some sort of plugin breaking things?
>
How can I tell this? I will try disabling the plugins .. will that work ...
or will I have to uninstall them?

Plugins that I have enabled ... from the Purple Pack are

Conversation Colors 2.10.11
History 2.10.11
Join/Part hiding 2.10.11
Log Reader 2.10.11
Message Notification 2.10.11
Release Notification 2.10.11
Windows Plugin Options 2.10.11



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120986986>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by dicecollector** [comment]
I disabled all of those plugins ... stopped and restarted Pidgin ... but
there is still no FB contacts :(

On Mon, Jul 13, 2015 at 10:50 AM, Kevin Cook <dicecollector@gmail.com>
wrote:

> HI James?
>
> On Mon, Jul 13, 2015 at 10:29 AM, James Geboski <notifications@github.com>
> wrote:
>
>> According to the log it is retrieving the contact list, and it is setting
>> the status for them.
>>
>
>
>> If you show offline buddies, do they appear?
>>
> That is my normal setting ... so no .. they do not show
>
>
>> Do you have some sort of plugin breaking things?
>>
> How can I tell this? I will try disabling the plugins .. will that work
> ... or will I have to uninstall them?
>
> Plugins that I have enabled ... from the Purple Pack are
>
> Conversation Colors 2.10.11
> History 2.10.11
> Join/Part hiding 2.10.11
> Log Reader 2.10.11
> Message Notification 2.10.11
> Release Notification 2.10.11
> Windows Plugin Options 2.10.11
>
>
>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-120986986>
>> .
>>
>
>
>
> --
> <http://www.dicecollector.com/>
>



-- 
<http://www.dicecollector.com/>

**Comment by rhymeAsylum** [comment]
I'm getting this error sometimes when I try to speak to someone
Failed to read fixed header

it is random

**Comment by dequis** [comment]
@rhymeAsylum Please open a new ticket for unrelated issues.

**Comment by dicecollector** [comment]
I dont recall seeing that error .. where are you seeing it? ... Screenshot?

On Mon, Jul 13, 2015 at 12:13 PM, rhymeAsylum <notifications@github.com>
wrote:

> I'm getting this error sometimes when I try to speak to someone
> Failed to read fixed header
>
> it is random
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/23#issuecomment-121011095>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by jgeboski** [comment]
I am really running out of ideas on this one.  From what I see in the log, everything is working as intended.  Do you have any other third-party protocol plugins?

**Comment by jgeboski** [comment]
Could you try creating a fresh purple environment?  This will help determine if it is something weird with your Facebook account.

1. Quit Pidgin
2. Move `%APPDATA%\.purple` to `%APPDATA%\.purple.old`
3. Start Pidgin and add your Facebook account
4. Check if the issue is still present
5. Remove `%APPDATA%\.purple`
6. Move `%APPDATA%\.purple.old` to `%APPDATA%\.purple`

**Comment by dicecollector** [comment]
HI James

Unfortunately for me ... that worked ...

I will have to create a new purple account and find a way to get the passwords to some IM accounts that I have not known in years ... since Pidgin automatically logs in

Any suggestion if this can be fixed without having to recreate all of my accounts?

Also .. Step 6 in your instructions is pretty devastating ... as you cannot rename .purple.old to .purple ... you have to move the contents (as you stated) for me ... this is over 50000 files and 3gb

**Comment by jgeboski** [comment]
Look in `%APPDATA%\.purple.old\accounts.xml`.

**Comment by jgeboski** [comment]
You might be able to get away with just yanking `%APPDATA%\.purple.old\blist.xml`.

**Comment by dicecollector** [comment]
Thanks James 

What should I look for in accounts.xml? 

If possible I need to keep the existing accounts ... minus Facebook ... and I can read a new facebook

**Comment by jgeboski** [comment]
Look for your old passwords `accounts.xml`.

**Comment by dicecollector** [comment]
Ah .. I have fixed that part now .. I have all of my account passwords ... the problem I am encountering now is all the settings (both Account and Pidgin) ... that have been set over the past 7? years

**Comment by jgeboski** [comment]
Did you manage to resolve this issue?

**Comment by dicecollector** [comment]
Yes .. thank you ... the rebuild fixed it

**Comment by dicecollector** [comment]
HI James 

it seems the FB Plugin stopped working again today ... I have sent you the debug file via the email address above

**Comment by dicecollector** [comment]
Sorry for the false alarm James 

FB seems to be working now ... please discard the debugs :)
