### ISSUE TITLE
libfacebook.dll link is down

### ISSUE THREAD

**Issue by KronosKoderS** [jgeboski/purple-facebook#230]
The link to the pre-built [libfacebook.dll](https://dl.voidium.net/pidgin/libfacebook.dll) appears to be down.

**Comment by KronosKoderS** [comment]
This link is found in your wiki:

https://github.com/jgeboski/purple-facebook/wiki/Installing-on-Windows

**Comment by jgeboski** [comment]
Hurricane Electric's DNS service failed. I have migrated things over to CloudFlare. This should be resolved once things have propagated (could take many hours).

**Comment by KronosKoderS** [comment]
just checked, and appears to be already working.
