### ISSUE TITLE
Feature request retrieve old messages

### ISSUE THREAD

**Issue by shtrb** [jgeboski/purple-facebook#235]
I was interacting with a contact using the web interface, when I open pidgin and click show log it would be nice If I could get the old messages from the past. 

example:

I added a contact in 2014, since 2014 we had been interacting using the web interface.
in 2016 I open pidgin and click on show log. I wish to be able to see the 2014 conversations in the log.

**Comment by dequis** [comment]
This is pretty much the same as #51. See that ticket for reasons on why this can't be done.

**Comment by shtrb** [comment]
that was related to #197

**Comment by shtrb** [comment]
As I understand #51 correctly, it does not talk about the log functionality but about in message context (within a single message).
