### ISSUE TITLE
IM notification sounds still played when away

### ISSUE THREAD

**Issue by jaymzh** [jgeboski/purple-facebook#24]
My pidgin is configured to only make sounds on received IMs when "available" - but the FB plugin doesn't seem to obey this and I get sounds when away.

**Comment by jgeboski** [comment]
So, the plugin does not define any sort of "away" state, which is likely why this happens.  This is due to the fact that Facebook only supports "Available" and "Offline."  I am going to have to bother some of the other Pidgin developers to hopefully figure out the best course of action.

**Comment by jaymzh** [comment]
I figured as much. I'd just make a dummy away state that doesn't change the state from Facebook's perspective (still "available"), but allows libpurple to know you're away.

BTW, this software is stellar - thanks so much for saving my ability to communicate with FB friends via my preferred chat platform. So happy.

**Comment by jgeboski** [comment]
So, I talked to two of the pidgin developers, and they were pretty neutral on the matter of this being implemented.  It is good for the people, such as you, and bad for people who expect to be away.  But it seems there might be some sort of idle presence state, which could be used for the "Away" state.

I think the general consensus is a better way to handle presence states in purple3.  But for now, I am going to go ahead implement this at some point in the near future.

**Comment by jaymzh** [comment]
That's awesome! Thanks.

**Comment by jgeboski** [comment]
I have implemented this in [051e2725dec4](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/051e2725dec4).  It will appear in the next update.

**Comment by jaymzh** [comment]
You are awesome, thanks!
