### ISSUE TITLE
Sending messages when offline

### ISSUE THREAD

**Issue by rrthomas** [jgeboski/purple-facebook#25]
[It's quite possible I misunderstand something about Pidgin or about the plugin, in which case apologies (and thanks very much for this plugin, which I found just after Facebook turned off my XMPP access).]

When a friend is offline, my messages are saved as pounces. But this is not necessary for the Facebook protocol: they can and should be sent immediately.

(I am using the Offline Message Emulation plugin, so one other possibility is that this is interacting in a bad way with a protocol that doesn't need it?)

**Comment by jgeboski** [comment]
This certainly sounds like the plugin is playing badly with the other plugin.  I have not tested this plugin with any other plugins enabled (both built-in and third-party).  I will take a look at making this work with that plugin.  This might be the same issue @kesava-wow experienced in #18.

**Comment by kesava-wow** [comment]
That was indeed the problem. I disabled Offline Message Emulation and it allowed me to send offline messages. That's sort of the behaviour I expected, though it doesn't happen with the XMPP plugin.

**Comment by rrthomas** [comment]
Thanks, in fact I just confirmed it. Can you comment on how easy it would be to fix the offline emulation plugin, i.e. get it to understand that some protocols work in offline mode? I would like to make a constructive bug report for it…

**Comment by dequis** [comment]
Seems that implementing this prpl is needed

```c
/** Checks whether offline messages to @a buddy are supported.
 *  @return @c TRUE if @a buddy can be sent messages while they are
 *          offline, or @c FALSE if not.
 */
gboolean (*offline_message)(const PurpleBuddy *buddy);
```

**Comment by rrthomas** [comment]
Great, at which end?

**Comment by dequis** [comment]
This one. So, easy.

**Comment by jgeboski** [comment]
This has been fixed [upstream](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/bf3c5b94071f), and will be in the next update.

**Comment by rrthomas** [comment]
Thanks, awesome stuff @jgeboski!
