### ISSUE TITLE
quotes are sent html-encoded to receipient

### ISSUE THREAD

**Issue by jaymzh** [jgeboski/purple-facebook#26]
I typed a sentence that said `3/8"` and it came out `3/8&quot;`

**Comment by jgeboski** [comment]
This should be fixed in latest release ([dc35ba3e7fac](https://github.com/jgeboski/purple-facebook/releases/tag/dc35ba3e7fac)).  Are you running this version?

**Comment by jaymzh** [comment]
I downloaded the latest release Friday... how do I know what version I'm running?

**Comment by jgeboski** [comment]
You need the version released last night. :)

See: `Help => Plugin Information`

**Comment by jaymzh** [comment]
I can confirm this is fixed in the latest release. Thanks!
