### ISSUE TITLE
There is no mention in the relevant readme.md required for packages

### ISSUE THREAD

**Issue by SergL** [jgeboski/purple-facebook#27]
It is advisable to indicate the need to install the system packages.
Or display more informative labels on the right if there is no error packages.

sudo apt-get install mercurial meld
sudo apt-get install libglib2.0-dev
sudo apt-get install libjson-glib-dev
sudo apt-get install pidgin-dev

**Comment by dequis** [comment]
Uhm... it's all there already

>Make sure **glib, json-glib, libpurple (pidgin), and zlib** are installed with their headers and development information. If these packages came from the distribution's repository, **they will likely need additional development packages, usually suffixed with -dev.**

>Otherwise, to build from this git repository, which additionally requires **autoconf, automake and mercurial** (for update.sh)

And meld? What is meld for? I'm pretty sure it's not required.

**Comment by jgeboski** [comment]
The README does not have, and will never have distro specific build instructions.  If you feel like contributing distro specific build instructions, please edit the wiki.
