### ISSUE TITLE
Server closed the connection

### ISSUE THREAD

**Issue by mrmusial** [jgeboski/purple-facebook#29]
Hello,

Since about two days I'm facing issue with connecting to FB chat via pidgin - I'm getting something like "connection closed by server".
I was using for many months till now and it was working fine, nothing was modified. Just two days ago it crashed :(

I have it configured in that way:

"
Protocol: XMPP
Username: xyz (This might not be the username that you enter at facebook login page - But the one which you see on your timeline link - https://www.facebook.com/xyz)
Domain: chat.facebook.com
Resource: Pidgin (this is what is missing most of the time)
Password: xyx

On the advanced tab:
Connect port: 5222
Connect server: chat.facebook.com
"

I know that the same issues has few my friends :(

Many thanks and regards,
Maciej

**Comment by EionRobb** [comment]
You're using the old XMPP stuff that no longer works.

Follow the readme here to install the new plugin and use that instead.
