### ISSUE TITLE
HTTP error and Fixed header error.

### ISSUE THREAD

**Issue by AyushBhat** [jgeboski/purple-facebook#31]
all i get is HTTP error and Fixed header error every second.

**Comment by rhymeAsylum** [comment]
Have you tried facebook username instead of email?

**Comment by AyushBhat** [comment]
whats it? the serial number that facebook gives to every account?

**Comment by rhymeAsylum** [comment]
I think it is what's after .com/HERE

could be a number if you didnt change your personal URL

**Comment by AyushBhat** [comment]
yeah, i have tried even that, nothing, it keeps disconnecting giving me an error, cant read the fixed header

**Comment by rhymeAsylum** [comment]
have you check your facebook if there is a connection that you have to recognize as yours?

**Comment by AyushBhat** [comment]
no i dont get the notification of log in, that i used to get when i would log in from XMPP, 
is the problem somewhere there?

**Comment by rhymeAsylum** [comment]
When i changed from XMPP to this plugin facebook asked me to recognize.

I'm a simple user don't know what else can be
