### ISSUE TITLE
Invalid HTTP response code (401)

### ISSUE THREAD

**Issue by AyushBhat** [jgeboski/purple-facebook#32]
thats what i get whenever i log in "Invalid HTTP response code (401)"

**Comment by jgeboski** [comment]
Please email me a [debugging log](https://github.com/jgeboski/purple-facebook#debugging-logs).

**Comment by AyushBhat** [comment]
Pidgin Debug Log : 7/14/2015 12:46:18 AM
(00:45:59) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png': No such file or directory
(00:45:59) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\omegle.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\omegle.png': No such file or directory
(00:45:59) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\okcupid.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\okcupid.png': No such file or directory
(00:45:59) account: Connecting to account tfeayush.
(00:45:59) connection: Connecting. gc = 0621A820
(00:45:59) http: Performing new request 05EF7628 to graph.facebook.com.
(00:45:59) dnsquery: Performing DNS lookup for graph.facebook.com
(00:46:00) dnsquery: IP resolved for graph.facebook.com
(00:46:00) proxy: Attempting connection to 31.13.79.246
(00:46:00) proxy: Connecting to graph.facebook.com:443 with no proxy
(00:46:00) proxy: Connection in progress
(00:46:01) proxy: Connecting to graph.facebook.com:443.
(00:46:01) proxy: Connected to graph.facebook.com:443.
(00:46:01) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 256-bit ECDSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
(00:46:01) nss: subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=CA,C=US issuer=CN=DigiCert High Assurance CA-3,OU=www.digicert.com,O=DigiCert Inc,C=US
(00:46:01) nss: partial certificate chain
(00:46:01) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(00:46:01) certificate/x509/tls_cached: Checking for cached cert...
(00:46:01) certificate/x509/tls_cached: ...Found cached cert
(00:46:01) nss/x509: Loading certificate from F:\PidginPortable\Data\settings\.purple\certificates\x509\tls_peers\graph.facebook.com
(00:46:01) certificate/x509/tls_cached: Peer cert matched cached
(00:46:01) nss/x509: Exporting certificate to F:\PidginPortable\Data\settings\.purple\certificates\x509\tls_peers\graph.facebook.com
(00:46:01) util: Writing file F:\PidginPortable\Data\settings\.purple\certificates\x509\tls_peers\graph.facebook.com
(00:46:01) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=CA,C=US
(00:46:01) certificate: Successfully verified certificate for graph.facebook.com
(00:46:02) http: Request 05EF7628 performed without success.
(00:46:02) connection: Connection error on 0621A820 (reason: 16 description: Invalid HTTP response code (401))
(00:46:02) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png': No such file or directory
(00:46:02) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\omegle.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\omegle.png': No such file or directory
(00:46:02) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\okcupid.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\okcupid.png': No such file or directory
(00:46:02) account: Disconnecting account tfeayush (0223D3D8)
(00:46:02) connection: Disconnecting connection 0621A820
(00:46:02) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png': No such file or directory
(00:46:02) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\omegle.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\omegle.png': No such file or directory
(00:46:02) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\okcupid.png: Failed to open file 'F:\PidginPortable\App\Pidgin\pixmaps\pidgin\protocols\16\okcupid.png': No such file or directory
(00:46:02) connection: Destroying connection 0621A820
(00:46:03) util: Writing file prefs.xml to directory F:\PidginPortable\Data\settings\.purple
(00:46:03) util: Writing file F:\PidginPortable\Data\settings\.purple\prefs.xml
(00:46:05) util: Writing file accounts.xml to directory F:\PidginPortable\Data\settings\.purple
(00:46:05) util: Writing file F:\PidginPortable\Data\settings\.purple\accounts.xml
(00:46:18) prefs: /pidgin/filelocations/last_save_folder changed, scheduling save.

**Comment by AyushBhat** [comment]
i have emailed you the debugging log :), kindly help

**Comment by jgeboski** [comment]
Your log is missing all of the extended debugging information.  Either you did not follow the [instructions](https://github.com/jgeboski/purple-facebook#debugging-logs) fully, or your version of the plugin is too old.

**Comment by AyushBhat** [comment]
thanks @jgeboski , i fixed this plugin by my own

**Comment by EionRobb** [comment]
How did you fix it?
