### ISSUE TITLE
Another HTTP Error, Timing Out

### ISSUE THREAD

**Issue by tyeo098** [jgeboski/purple-facebook#33]
Pidgin complains "unknown http error"

Debug log says its a timeout. 

11:10:04) account: Connecting to account tyeo098.
(11:10:04) connection: Connecting. gc = 0xb9cc9f88
(11:10:04) http: Performing new request 0xba027b00 for https://b-api.facebook.com/method/auth.login.
(11:10:04) http: Connecting to https://b-api.facebook.com/method/auth.login...
(11:10:04) facebook: HTTP Request (0xba027b00):
(11:10:04) facebook:   Request URL: https://b-api.facebook.com/method/auth.login
(11:10:04) facebook:   Request Data: fb_api_req_friendly_name=authenticate&fb_api_caller_class=com.facebook.auth.protocol.d&email=tyeo098&password=(Plaintext passwords, really?)&locale=en_US&format=json&device_id=(redacted)&api_key=256002347743983&sig=(redacted)&method=auth.login
(11:10:04) dnsquery: Performing DNS lookup for b-api.facebook.com
(11:10:04) http: new socket created: 0xb9d18a10
(11:10:04) http: locking a (new) socket: 0xb9d18a10
(11:10:04) dns: DNS child 1843 no longer exists
(11:10:04) dns: Created new DNS child 1864, there are now 1 children.
(11:10:04) dns: Successfully sent DNS request to child 1864
(11:10:05) dns: Got response for 'b-api.facebook.com'
(11:10:05) dnsquery: IP resolved for b-api.facebook.com
(11:10:05) proxy: Attempting connection to 2a03:2880:f000:6:face:b00c:0:1
(11:10:05) proxy: Connecting to b-api.facebook.com:443 with no proxy
(11:10:05) proxy: Connection in progress
(11:10:10) util: Writing file accounts.xml to directory /home/tyler/.purple
(11:10:10) util: Writing file /home/tyler/.purple/accounts.xml
dns[1864]: nobody needs me... =(
(11:10:35) http: Timeout reached for request 0xba027b00
(11:10:35) http: Cancelling connection 0xba027b00...
(11:10:35) http: destroying socket: 0xb9d18a10
(11:10:35) http: Request 0xba027b00 performed without success.
(11:10:35) facebook: HTTP Response (0xba027b00):
(11:10:35) facebook:   Response Data: 
(11:10:35) connection: Connection error on 0xb9cc9f88 (reason: 16 description: Unknown HTTP error)
(11:10:35) account: Disconnecting account tyeo098 (0xb9562528)
(11:10:35) connection: Disconnecting connection 0xb9cc9f88
(11:10:35) http: Cancelling all running HTTP connections
(11:10:35) connection: Destroying connection 0xb9cc9f88

**Comment by jgeboski** [comment]
Looks like your IPv6 connection to `b-api.facebook.com` is broken.

Test the connection with: `curl -6I https://b-api.facebook.com`

**Comment by tyeo098** [comment]
Woops.
Thought I had gotten rid of everything IPV6.
sysctl seems to have re-enabled it. 

Running through and disabling it according to http://askubuntu.com/questions/440649/how-to-disable-ipv6-in-ubuntu-14-04 seems to have resolved it. 

Friends list loaded, send and receive confirmed.

Great job! Thanks a lot! Now about those plaintext passwords...

**Comment by jgeboski** [comment]
It is all sent over an encrypted HTTP connection.  The password is only being dumped to `stdout` as you have debugging enabled with the `PURPLE_UNSAFE_DEBUG` variable.  If I spent the time to strip every little piece of "sensitive" information from the logs, they'd be butchered at that point, and the code base would be even bigger.

**Comment by ThornedRose** [comment]
I had this exact same problem with the same debug log. What 'fixed' it for me however was changing from ConnMan to NetworkManager. I'm on Arch Linux and my network card is a NVIDIA Corporation MCP51 Ethernet Controller (rev a3) in case this helps anyone else.

**Comment by enielrodriguez** [comment]
I have the same problem, but is caused by a slow network connection.
I tried with an account with few messages and only 3 friends, and it worked.
But with mine, which has dozens of messages (all marked as read) and hundreds of friends, it does not work, it starts to download data but the connection ends with the mentioned error  (I check it in the log).
Is there any way to increase the connection timeout?
