### ISSUE TITLE
Protocol not showing in Add Account dropdown

### ISSUE THREAD

**Issue by AWildColin** [jgeboski/purple-facebook#34]
DLLs have been added to plugins directory, but the new Facebook protocol is not showing after restarting Pidgin and I'm unable to add a new account. Using release "purple-facebook-4098e875ebcb".

`/cygdrive/c/Program Files (x86)/Pidgin/plugins » ls -la                                                                                                            `
`total 5.5M`
`drwxrwx---+ 1 Administrators Domain Users    0 Jul 13 11:43 ./`
`drwxrwx---+ 1 Administrators Domain Users    0 Apr 21 11:55 ../`
`-rwxrwx---+ 1 Administrators Domain Users  21K Nov 23  2014 .dll*`
`-rwxrwx---+ 1 Administrators Domain Users  21K Nov 23  2014 autoaccept.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  13K Nov 23  2014 buddynote.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  25K Nov 23  2014 convcolors.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 425K Nov  8  2010 encrypt.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  16K Nov 23  2014 extplacement.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  14K Nov 23  2014 gtkbuddynote.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  19K Nov 23  2014 history.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  13K Nov 23  2014 iconaway.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  19K Nov 23  2014 idle.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  19K Nov 23  2014 joinpart.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  15K Nov 23  2014 libaim.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  91K Nov 23  2014 libbonjour.dll*`
**`-rwxrwx---+ 1 Administrators Domain Users 712K Jul 13 11:42 libfacebook.dll*`**
`-rwxrwx---+ 1 Administrators Domain Users 321K Nov 23  2014 libgg.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  16K Nov 23  2014 libicq.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 105K Nov 23  2014 libirc.dll*`
**`-rwxrwx---+ 1 Administrators Domain Users 561K Jul 13 11:42 libjson-glib-1.0.dll*`**
`-rwxrwx---+ 1 Administrators Domain Users 366K Nov 23  2014 libmsn.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 148K Nov 23  2014 libmxit.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 105K Nov 23  2014 libmyspace.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 121K Nov 23  2014 libnovell.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 114K Nov 23  2014 libsametime.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 168K Nov 23  2014 libsilc.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  55K Nov 23  2014 libsimple.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 456K Apr  4 10:43 libsipe.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  21K Nov 23  2014 libxmpp.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  23K Nov 23  2014 libyahoo.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  20K Nov 23  2014 libyahoojp.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  47K Nov 23  2014 log_reader.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  22K Nov 23  2014 markerline.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  14K Nov 23  2014 newline.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  29K Nov 23  2014 notify.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  17K Nov 23  2014 offlinemsg.dll*`
`drwxrwx---+ 1 Administrators Domain Users    0 Dec  2  2014 perl/`
`-rwxrwx---+ 1 Administrators Domain Users  51K Nov 23  2014 perl.dll*`
`-rwxrwx---+ 1 Administrators Domain Users 733K Oct 21  2014 pidgin-otr.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  29K Nov 23  2014 pidginrc.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  16K Nov 23  2014 psychic.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  16K Nov 23  2014 relnot.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  15K Nov 23  2014 sendbutton.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  68K Nov 23  2014 spellchk.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  12K Nov 23  2014 ssl.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  32K Nov 23  2014 ssl-nss.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  16K Nov 23  2014 statenotify.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  72K Nov 23  2014 tcl.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  30K Nov 23  2014 themeedit.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  32K Nov 23  2014 ticker.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  18K Nov 23  2014 timestamp.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  24K Nov 23  2014 timestamp_format.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  30K Nov 23  2014 win2ktrans.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  31K Nov 23  2014 winprefs.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  37K Nov 23  2014 xmppconsole.dll*`
`-rwxrwx---+ 1 Administrators Domain Users  44K Nov 23  2014 xmppdisco.dll*`

**Comment by jgeboski** [comment]
`mv "/cygdrive/c/Program Files (x86)/Pidgin/plugins/libjson-glib-1.0.dll" "/cygdrive/c/Program Files (x86)/Pidgin"`

**Comment by AWildColin** [comment]
I figured it had to be something obvious that I was missing. Fixed!
