### ISSUE TITLE
The plugin does not reconnect after network disruption

### ISSUE THREAD

**Issue by fangfufu** [jgeboski/purple-facebook#35]
Purple-facebook does not seem to reconnect back to Facebook automatically, after the computer loses Internet connection and reconnect back. My other IM networks get reconnected automatically, e.g. XMPP and purple-whatsapp. I don't know if this is an expected behaviour or a bug.

**Comment by jgeboski** [comment]
What version of the plugin are you running?  There is a patch in [dc35ba3e7fac](https://github.com/jgeboski/purple-facebook/releases/tag/dc35ba3e7fac) which should have fixed this.

**Comment by fangfufu** [comment]
I am not 100% sure. I have been keeping my repository up-to-date by doing 
```
git pull
./autogen.sh
```
Have I done it correctly?

**Comment by jgeboski** [comment]
What version is shown in `Help -> Plugin Information`?

**Comment by fangfufu** [comment]
4098e875ebcb

**Comment by jgeboski** [comment]
What does it display as the error before you manually reconnect?

**Comment by fangfufu** [comment]
```Unable to connect to graph.facebook.com: SSL Connection Failed```

**Comment by fangfufu** [comment]
Somehow the default XMPP plugin and the WhatsApp plugin just reconnects without any complaint. I don't have to manually reconnect them when my Internet comes back.

**Comment by jgeboski** [comment]
This has been fixed as of [aa4aa525233d](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/aa4aa525233d), and will appear in the next release.
