### ISSUE TITLE
Support for facebook tor .onion server

### ISSUE THREAD

**Issue by BoBeR182** [jgeboski/purple-facebook#36]
Facebook has an official onion server, please add support for it.
https://facebookcorewwwi.onion/

**Comment by jgeboski** [comment]
I just tried with the follow patch, but no luck.  If i had to guess, I would assume the onion address is web only.  I would also assume all the images on website are still directly from Akamai as well.

It is also worth noting, I am far from a Tor expert, I have only ever used it a few times.  Feel free to test the patch below, and see if you can get it working.  I am more than willing to support the onion addresses if they exist and work.

```
diff -r 305f27dd23c0 libpurple/protocols/facebook/api.h
--- a/libpurple/protocols/facebook/api.h	Mon Jul 13 12:57:52 2015 -0400
+++ b/libpurple/protocols/facebook/api.h	Tue Jul 14 12:55:02 2015 -0400
@@ -29,9 +29,9 @@
 #include "id.h"
 #include "mqtt.h"
 
-#define FB_API_HOST    "https://api.facebook.com"
-#define FB_API_BHOST   "https://b-api.facebook.com"
-#define FB_API_GHOST   "https://graph.facebook.com"
+#define FB_API_HOST    "https://api.facebookcorewwwi.onion"
+#define FB_API_BHOST   "https://b-api.facebookcorewwwi.onion"
+#define FB_API_GHOST   "https://graph.facebookcorewwwi.onion"
 #define FB_API_AGENT   "Facebook App / " PACKAGE " / " VERSION
 #define FB_API_KEY     "256002347743983"
 #define FB_API_SECRET  "374e60f8b9bb6b8cbb30f78030438895"
diff -r 305f27dd23c0 libpurple/protocols/facebook/mqtt.h
--- a/libpurple/protocols/facebook/mqtt.h	Mon Jul 13 12:57:52 2015 -0400
+++ b/libpurple/protocols/facebook/mqtt.h	Tue Jul 14 12:55:02 2015 -0400
@@ -29,7 +29,7 @@
 #define FB_MQTT_NAME "MQIsdp"
 #define FB_MQTT_VERS 3
 #define FB_MQTT_KA   60
-#define FB_MQTT_HOST "mqtt.facebook.com"
+#define FB_MQTT_HOST "mqtt.facebookcorewwwi.onion"
 #define FB_MQTT_PORT 443
 
 #define FB_MQTT_TIMEOUT_CONN (FB_MQTT_KA * 1500)
```

**Comment by dequis** [comment]
I kinda doubt they have separate hidden services for each different part of the facebook messenger infrastructure.

Also I believe all the subdomains in an .onion name resolve to the same hidden service, so it only makes sense to use subdomains like that if it's all http (and it's not)

**Comment by jgeboski** [comment]
I am closing this for now.  If someone can provide me with the proper onion addresses (which work), I'll implement onion support.
