### ISSUE TITLE
Ignoring Server Side Groups

### ISSUE THREAD

**Issue by GagHalfrunt42** [jgeboski/purple-facebook#40]
Just installed the Plugin, all looks good so far.

Would it be possible to add an option to ignore the "Buddies" group and instead use my client-side groups?  I like to use Pidgin as an integrated messenger so would like all accounts to appear under a single contact, e.g. if the user has Google, ICQ and Facebook accounts I would like to have it all appear under the same contact.

Before Facebook decided to drop XMPP I had it kind of working (not always reliable admittedly!) under XMPP using the xmpp-ignore-groups plugin.

**Comment by EionRobb** [comment]
I think your question is "can the plugin keep my Facebook buddies assigned where I had them grouped into contacts with XMPP?" which unfortunately the answer at this stage is "no".   The plugin doesn't force the buddies to end up in one group though (there's no such thing as a "server side group" in this plugin), so the xmpp-ignore-groups plugin isn't needed.

**Comment by GagHalfrunt42** [comment]
Thanks.  Yes, I guess that is the question I'm asking.  Are there any plans to allow integrated contacts?

**Comment by jgeboski** [comment]
It is on the TODO (#9).
