### ISSUE TITLE
Formated URL

### ISSUE THREAD

**Issue by Mariglianov** [jgeboski/purple-facebook#41]
Hello when facebook format an url adding a thumbnail to it, no message is received on Pidgin.

> Exemple
> ![capture du 2015-07-15 02 25 21](https://cloud.githubusercontent.com/assets/1238787/8688162/d402ebb6-2a98-11e5-9332-3123f1b5c61e.png)

**Comment by jgeboski** [comment]
It is on the TODO (#9).
