### ISSUE TITLE
Certain characters not sending correctly.

### ISSUE THREAD

**Issue by TJZAwsum** [jgeboski/purple-facebook#42]
I really appreciate how quickly this fix came out, but I'm having some issues.

When I type certain characters like " or > or < into the chat, they appear on Facebook as &quot; and &gt; and &lt; respectively. Not sure which characters cause this, but these are the ones I've encountered so far.

I'm using Windows 8.1 64 and Pidgin 2.10.11

**Comment by jgeboski** [comment]
Uh... what?  Isn't that what you want?

**Comment by jgeboski** [comment]
GitHub may have formatted your XML entities.  In any event, that bug was fixed, update to the latest version.

**Comment by TJZAwsum** [comment]
Haha wow, didn't notice that Github automatically formatted it. But yeah, it would send [this](http://i.imgur.com/m70bm0x.png) on the Facebook end when I used a quotation sign for example. But yes, the update fixed it, thank you.

If I may tack on a few questions without starting a new thread... Sorry if all of these have been brought up before.

I noticed that 'media' is on the to-do list. I see that I get a message on Pidgin that says " Non-Displayable Attachment " when my chat partner sends a picture, but I get nothing at all when they send a sticker. Is there plans to turn " Non-Displayable Attachment" into a direct link to the image?

Also it seems that randomly, I just won't get alerted at all when they send a message that happens to include a link, sometimes it happens even with messages without links. It seems totally random from what I understand. The previous and next message go through without issue.

Last, I was wondering if there was perhaps any way to enable auto updating when you update the plugin. If not, is there any way I can set up an email notification when a new update is published? This is the first time I've ever made an account on github so I'm not sure what options I have.

Last last, I just want to thank you for being so quick to develop this and fill the gap that Facebook annoyingly closed.

**Comment by jgeboski** [comment]
The "media" item on the TODO list will fix the non-displayable attachments, and turn them into a link, yes.  It will also fix links not coming through as a message.  As for an updater, I have no plans for an auto-updater.  I think @EionRobb was talking about creating a windows installer, but nothing more.
