### ISSUE TITLE
don't know if this a bug of this plugin..

### ISSUE THREAD

**Issue by hetzbh** [jgeboski/purple-facebook#45]
If I'm adding someone new to my Facebook contact and I start chatting with it, I see the contact name as a long number, not a name and I also don't see him on the contact list. The only way to "fix" it is to log off and log on again

**Comment by jgeboski** [comment]
Yeah, this is a known issue.  It is due to the fact that no incoming events are handled.  This is on the TODO (#9), and it likely to get done soon.
