### ISSUE TITLE
Carriage return replaced by `<br>`

### ISSUE THREAD

**Issue by Mariglianov** [jgeboski/purple-facebook#46]
Hello, when i send a message with some carriage return (ctrl + Enter), the carriage return charater is replaced by a `<br>` tag.
![capture du 2015-07-16 04 21 07](https://cloud.githubusercontent.com/assets/1238787/8714191/72de296a-2b72-11e5-9d7a-c6f9dffa2472.png)

**Comment by dequis** [comment]
Are you using the latest version? (`305f27dd23c0`)

Check in `Help => Plugin Information`

**Comment by fchaix** [comment]
Hello.
I the same problem with the <br> replacing the carriage return charater.
I am using the last version (I just git pull and recompiled the plugin), but the version displayed in `Help => Plugin Information` is not on the last version I see in the commits. It displays a34b993324e4.

**Comment by EionRobb** [comment]
Did you run the ./upgrade.sh to get the latest version from hg too?

**Comment by fchaix** [comment]
Oops, I didn't. My bad. It works now.

**Comment by Mariglianov** [comment]
Yep it worked with the last tarball release, thanks :+1:
