### ISSUE TITLE
Unknown HTTP error

### ISSUE THREAD

**Issue by ciakpey** [jgeboski/purple-facebook#49]
I have an error since yesterday and now I can't connect to the chat, I only have this error when I go through my vpn:

(22:28:24) http: Performing new request 0x276cd30 to graph.facebook.com.
(22:28:24) dnsquery: Performing DNS lookup for graph.facebook.com
(22:28:24) dns: Successfully sent DNS request to child 8342
(22:28:24) dns: Got response for 'graph.facebook.com'
(22:28:24) dnsquery: IP resolved for graph.facebook.com
(22:28:24) proxy: Attempting connection to 31.13.93.3
(22:28:24) proxy: Connecting to graph.facebook.com:443 with no proxy
(22:28:24) proxy: Connection in progress
(22:28:28) util: Writing file accounts.xml to directory /home/ta/.purple
(22:28:28) util: Writing file /home/ta/.purple/accounts.xml
(22:28:55) http: Timeout reached for request 0x276cd30
(22:28:55) http: Request 0x276cd30 performed without success.
(22:28:55) connection: Connection error on 0x27b1a30 (reason: 16 description: Unknown HTTP error)
(22:28:55) account: Disconnecting account ***********@****.com (0x23fd7f0)

**Comment by jgeboski** [comment]
What does `curl -I https://graph.facebook.com` say, when running through your VPN?

**Comment by ciakpey** [comment]
No response,
So I think that doesn't come from you, but facebook may block requests 
from ovh server.
You can close the issue
Thanks

**Comment by jgeboski** [comment]
You might try checking for IPv6 connection issues as well if you are using it.
