### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Hernou** [jgeboski/purple-facebook#50]
Hi,
I can't connect to my facebook account,
I try with my email, my facebook email, but it do not work :-(
![screenshot](http://i.imgur.com/lU14keH.png)

**Comment by jgeboski** [comment]
Is this a duplicate of #2? What version of the plugin are you using?

**Comment by EionRobb** [comment]
Looks like you're using "facebook.com/lio.hernou" as the account username? Try just using "lio.hernou" (i.e. Your username) instead

**Comment by Hernou** [comment]
lio.hernou do not work.

It looks great on this bug , but I do not understand what I have to do just to solve it ...

**Comment by jgeboski** [comment]
@Hernou I would like a version number: `Help => Plugin Information`.

**Comment by Hernou** [comment]
ok, I installed from git clone.
So I install it from your last realese 565fbae05259, and it work know. :-)
Really good plugin thanks you
