### ISSUE TITLE
Ubuntu 14.04 installation problem

### ISSUE THREAD

**Issue by jkubos** [jgeboski/purple-facebook#54]
It seems plugin can't be installed on Ubuntu 14.04.2 LTS:
```
root@pc-jarek:~# apt-get install purple-facebook
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 purple-facebook : Depends: libjson-glib but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Available packages are:
```
root@pc-jarek:~# apt-cache search libjson-glib
libjson-glib-1.0-0 - GLib JSON manipulation library
libjson-glib-1.0-0-dbg - GLib JSON manipulation library (debug symbols)
libjson-glib-1.0-common - GLib JSON manipulation library (common files)
libjson-glib-dev - GLib JSON manipulation library (development files)
libjson-glib-doc - GLib JSON manipulation library (documentation)
```

Could you please take a look on it? Thank you!

**Comment by kotarou3** [comment]
`libjson-glib` seems to be a virtual package, but no (real) package provides it

**Comment by andreasmoegelmose** [comment]
I had the same dependency-issue on Ubuntu 15.04. Everything seems to work if I remove the libjson-glib dependency as kotarou3 suggested.

I downloaded the .deb using

    sudo apt-get download purple-facebook

And then followed the instructions here: http://serverfault.com/a/383958/188346 to remove libjson-glib from the dependency list.

**Comment by jgeboski** [comment]
Sorry!  I have fixed this in 6bb0e31.  The builders have finished building.  Go ahead and update, it should work this time around.

**Comment by jkubos** [comment]
On 15.04 it works like charm. I will test 14.04 at home. Thank you for prompt response!

**Comment by jkubos** [comment]
I can confirm that 14.04 works too. Good job. Thank you!
