### ISSUE TITLE
Cannot connect - pidgin freezing

### ISSUE THREAD

**Issue by sioban** [jgeboski/purple-facebook#55]
Hi,

Once I added the FB account, pidgin freeze while trying to connect.

This is what I got from the logs (last lines, full log will be sent on request) :
(10:48:38) facebook: HTTP Response (01E07CE8):
(10:48:38) facebook:   Response Error: 200
(10:48:38) facebook:   Response Data: {"session_key":"[redacted]","uid":[redacted],"secret":"[redacted]","access_token":"[redacted]","machine_id":"[redacted]"}
(10:48:38) GLib-GObject: cannot register existing type `JsonParser'
(10:48:38) GLib: g_once_init_leave: assertion `initialization_value != 0' failed
(10:48:38) GLib-GObject: g_object_new: assertion `G_TYPE_IS_OBJECT (object_type)' failed

Note : 
- pidgin version : 2.10.11 (portable edition)
- plugin version : purple-facebook-565fbae05259
- platform : windows 7 / 64 bits

**Comment by EionRobb** [comment]
That will happen if you have two different json-glib dll's loaded

**Comment by sioban** [comment]
Thanks that was the problem :D
