### ISSUE TITLE
ejabberd transport

### ISSUE THREAD

**Issue by jkufner** [jgeboski/purple-facebook#57]
There should be a section in documentation about installing this as a transport for ejabberd (or any other) Jabber server.

**Comment by dequis** [comment]
That's... completely out of scope for this project. This is a protocol plugin for libpurple, primarily supported for pidgin.

If it has any bugs in particular with, e.g., spectrum2, we could do something about it, or at least help you debug the issue. From what I hear those bugs tend to be in their side, not the protocol plugin side.

**Comment by jkufner** [comment]
I just installed it with Spectrum and so far it works fine. Few configuration examples would be nice. GUI clients are easy, but what to write to config file?

**Comment by dequis** [comment]
Well if you have no issues then we have nothing to do here!

Like I said, not our department, and if it doesn't need anything significantly different to other protocol plugins, then the spectrum documentation should be enough.
