### ISSUE TITLE
Display message sent from the other clients of the same user

### ISSUE THREAD

**Issue by fangfufu** [jgeboski/purple-facebook#6]
Currently if I send messages from a different client, e.g. the web interface, these messages do not show up in Pidgin. However they do show up on the mobile client. I suspect the mobile client either poll the server for new messages, or get those messages pushed in. I wonder if you can implement this feature in Pidgin. This feature would be helpful so the conversations across different clients are synced. 

I think this feature enhancement request applies to bitlbee-facebook too. For Bitlbee, you could use the idea in http://wiki.znc.in/Privmsg or http://wiki.znc.in/Privmsg_prefix.

**Comment by jgeboski** [comment]
Merged into #9.
