### ISSUE TITLE
cannot compile on debian

### ISSUE THREAD

**Issue by amainyebriggs** [jgeboski/purple-facebook#60]
please compile for debian systems and post on git so we can have already compiled libfacebook.so and libfacebook.la   beacuse i have being finding it difficult to compile on my kali linux , i even clone the resent update as at 20th july 2015 by 22.24pm but still cannot compile 
thanks for your help

**Comment by jgeboski** [comment]
A debian repository has been setup recent.  See the [wiki](https://github.com/jgeboski/purple-facebook/wiki/Installing-on-*NIX#debian-and-ubuntu).
