### ISSUE TITLE
Failure when building Debian package

### ISSUE THREAD

**Issue by tremby** [jgeboski/purple-facebook#61]
I'm on Ubuntu 14.04.

When running the [suggested](https://github.com/jgeboski/purple-facebook/wiki/Building-on-*NIX) `sudo checkinstall` command it ends up saying building the Debian package failed, and if I choose to view the log I get this:

```
dpkg-deb: error: parsing file '/var/tmp/tmp.9Fqs0S9Agw/package/DEBIAN/control' near line 7 package 'purple':
 error in 'Version' field string 'facebook-1': version number does not start with digit
```

Are there any more details which would be useful?

**Comment by jgeboski** [comment]
Someone else added checkinstall to the wiki, and I have zero experience with it.  I will say, you should probably be using the [debian repository](https://github.com/jgeboski/purple-facebook/wiki/Installing-on-*NIX#debian-and-ubuntu).  It will save you a ton of pain.

Try the following:
```
SHDATE=$(date +%Y%m%d)
LNDATE=$(date -R)
GITREV=$(git -C source rev-parse --short=7 HEAD)
UPSREV=$(cat source/VERSION)

sudo checkinstall --pkgversion "0.0+${SHDATE}+${GITREV}+${UPSREV}"
```

Or try:
```
SHDATE=$(date +%Y%m%d)
LNDATE=$(date -R)
GITREV=$(git -C source rev-parse --short=7 HEAD)
UPSREV=$(cat source/VERSION)

dch -bv "0.0+${SHDATE}+${GITREV}+${UPSREV}" "Git build"
sudo dpkg-buildpackage -uc -us
sudo dpkg -i *.deb
```

**Comment by tremby** [comment]
On 20 Jul 2015 19:58, "James Geboski" <notifications@github.com> wrote:
> Someone else added checkinstall to the wiki, and I have zero experience
with it. I will say, you should probably be using the debian repository. It
will save you a ton of pain.

Oh, I had a quick look but didn't find one! Thanks. I'll test out your
suggestions first so we can update the wiki.

**Comment by jgeboski** [comment]
> Thanks. I'll test out your suggestions first so we can update the wiki.

That'd be lovely!

**Comment by tremby** [comment]
The first list worked great (I haven't tested the actual plugin yet), after I updated the commands to point to the current directory rather than a `source` directory.

**Comment by tremby** [comment]
Oh, maybe not. It made and installed a packaged called `purple`, which is a little confusing.

**Comment by jgeboski** [comment]
I guess you could try:
```
sudo checkinstall --pkgname "purple-facebook" --pkgversion "0.0+${SHDATE}+${GITREV}+${UPSREV}"
```

What I am getting out of all of this, is that there is a reason I have never used this "tool."

**Comment by dequis** [comment]
...why is this conversation even happening when there's a perfectly fine APT repo which uses perfectly fine debian build scripts instead of the hack that is checkinstall?

**Comment by tremby** [comment]
To try to fix the wiki, if such a thing was simple, as said above.

**Comment by tremby** [comment]
Anyway, what I was trying to achieve, in lieu of a repository (which I now know exists), was just build the deb file so I could install it. Is there a simple command to do that?

**Comment by dequis** [comment]
Honestly just `dpkg-buildpackage -uc -us` should do. It won't have a correct version string, but it generates a deb, good enough for local testing purposes.

**Comment by tremby** [comment]
This complains about a missing autoreconf module. I've spent long enough on it; I'll stop and add the repo. Thanks.

**Comment by dequis** [comment]
Well, FWIW, that's the `dh-autoreconf` package.

**Comment by tremby** [comment]
Thanks.
