### ISSUE TITLE
PM's from non friends do not identify who they are 

### ISSUE THREAD

**Issue by dicecollector** [jgeboski/purple-facebook#63]
Hi again .. sorry to keep bothering you ... I discovered after recreating my Pidgin accounts and fixing Facebook (not using SMPP anymore) that if someone messages me who is not one of my friends ... it does not identify who the contact person is ... it only gives a long number ... that does not seem to be the users FB id # ... as it is several orders of magnitude higher than mine 

My remedy is to goto FB and look at my current messages ... which of course does identify the sender 

I will supply a screenshot the next time it occurs

**Comment by dicecollector** [comment]
Here is the screenshot 
![github fb 01](https://cloud.githubusercontent.com/assets/13302826/8800626/9f0aabe6-2f71-11e5-8cf6-2f5e53148e86.jpg)

**Comment by dicecollector** [comment]
Another thing I have found ... if someone who is not connected to me in any way via FB ...  PM's me ... Pidgin will not even acknowledge it ... the sender receives 

"Your message will go to his Other folder because you aren't connected to him on Facebook. See More"

**Comment by jgeboski** [comment]
This is indirectly a duplicated of #53.
