### ISSUE TITLE
Plugin fails to register on Windows 7x64.

### ISSUE THREAD

**Issue by capitaladot** [jgeboski/purple-facebook#64]
![libfacebookinstalled](https://cloud.githubusercontent.com/assets/1619329/8800524/83ca23a6-2f81-11e5-9086-879dff0d16f8.png)
![libjsoninstalled](https://cloud.githubusercontent.com/assets/1619329/8800525/858a306e-2f81-11e5-88bb-fb86f9eca0de.png)
![nofacebookaccounttype](https://cloud.githubusercontent.com/assets/1619329/8800589/1b18d0cc-2f82-11e5-95f2-e4fa3d795c57.png)

Plugin Information lacks anything about Facebook/libpurple/etc.

**Comment by capitaladot** [comment]
From pidgin.log: 
(08:24:11) plugins: C:\Program Files (x86)\Pidgin\plugins\libfacebook.dll is not loadable: `C:\Program Files (x86)\Pidgin\plugins\libfacebook.dll': The specified procedure could not be found.

**Comment by jgeboski** [comment]
What version of pidgin?

**Comment by capitaladot** [comment]
@jgeboski Pidgin 2.10.11

**Comment by jgeboski** [comment]
Did you follow the [instructions](https://github.com/jgeboski/purple-facebook/wiki/Installing-on-Windows)?

**Comment by jgeboski** [comment]
Disregard my prior statement, the images above just loaded.

**Comment by jgeboski** [comment]
Just to confirm, you did restart pidgin completely, not just closing the buddy list?

**Comment by capitaladot** [comment]
All of of the above, including generating the log file as in "Debug Log on Windows", hence:

From pidgin.log: 
(08:24:11) plugins: C:\Program Files (x86)\Pidgin\plugins\libfacebook.dll is not loadable: `C:\Program Files (x86)\Pidgin\plugins\libfacebook.dll': The specified procedure could not be found.

**Comment by jgeboski** [comment]
Whoops!  Yup.  What files are in `C:\Program Files (x86)\Pidgin\Gtk\manifest`?

**Comment by capitaladot** [comment]
![gtkmanifest](https://cloud.githubusercontent.com/assets/1619329/8802394/16f168b2-2f8f-11e5-8aee-8bb6d8fe717a.png)

**Comment by jgeboski** [comment]
Did you use this plugin's [libjson-glib-1.0.dll](https://github.com/jgeboski/purple-facebook/releases/download/downloads/libjson-glib-1.0.dll), as it certainly does not look like it (in terms of size).  I assume you got the other `libjson-glib-1.0.dll` from one of @EionRobb's plugins.  Use the one from this plugin.  It is newer, and should be backwards compatible.

**Comment by capitaladot** [comment]
That made all the difference; sounds like it was my mistake, so apologies!
