### ISSUE TITLE
Avatars and contact details - vcard support

### ISSUE THREAD

**Issue by jkufner** [jgeboski/purple-facebook#65]
When using purple-facebook via Spectrum, I cannot see contact avatars in my roster. I guess that purple-facebook does not provide such information (it worked with XMPP transport, so Spectrum should be fine here).

I believe that name, link to facebook profile and avatar (profile photo) should be enough to display in contact's vcard and easy to obtain. If some additional data are available it will be only better, but these three are important.

**Comment by jgeboski** [comment]
Buddy icons (avatars) have been implemented, and work within pidgin.  If these are not working for you, fix your client side (spectrum) libpurple implementation.  As for user info, it is on the TODO (#9).

**Comment by dazzzl** [comment]
I've written a short get_info which resolves this:

static void fb_get_info(PurpleConnection * gc, const char *username)
{
        PurpleBuddyIcon *buddy_icon;
        size_t image_size;
        gconstpointer image_pointer;
        int icon_id = -1;
        gchar *value_tmp;

        PurpleNotifyUserInfo *info = purple_notify_user_info_new();
        buddy_icon = purple_buddy_icons_find(gc->account, username);
        if (buddy_icon)
        {
                image_pointer = purple_buddy_icon_get_data(buddy_icon, &image_size);
                icon_id = purple_imgstore_add_with_id(g_memdup(image_pointer, image_size), image_size, NULL);
                value_tmp = g_strdup_printf("<img id='%d'>", icon_id);
                purple_debug_info("facebook", "user info pic: '%s'\n", value_tmp);
                purple_notify_user_info_add_pair(info, NULL, value_tmp);
                g_free(value_tmp);
        }
        purple_notify_userinfo(gc, username, info, NULL, NULL);
}

**Comment by EionRobb** [comment]
That looks like some great code... To add to spectrum as a fallback for prpls with no get-info()

**Comment by jgeboski** [comment]
Thanks to @Ghabry, this has been fixed upstream as of hanzz/libtransport#64.
