### ISSUE TITLE
Accounts that are not in my facebook friends list

### ISSUE THREAD

**Issue by cyberalex4life** [jgeboski/purple-facebook#68]
Your last version makes contacts that I unfriended appear in the list. 
I also changed the username recently and some contacts that I never had on this account also appear. Probably the username used matches an old closed account username (I closed 2 accounts definitely before making this one).
This behaviour is both in Ubuntu 14.04.2 (with your "repository") and now in Manjaro.

**Comment by jgeboski** [comment]
> Your last version makes contacts that I unfriended appear in the list.

All versions should be doing this, as the plugin has yet to handle incoming events for added and removed friends.

> I also changed the username recently and some contacts that I never had on this account also appear.

Sounds like your `blist.xml` still contains your old friends.  Just remove the account from pidgin, and add it back with the new username.

**Comment by cyberalex4life** [comment]
No, it's not from blist.xml I have persons that I might have had on a closed account using the same username as the one I use now for this account (facebook let me changed it). If this doesn't make sense, or is literally not possible, then I might have added by mistake someone, then unfriended.
The thing is that when using the browser for facebook, it only shows me 6 friends in the chat (as much as I now have); instead pidgin shows 18. The previous version was ok, until I got some error at login, and had to compile this one.

**Comment by EionRobb** [comment]
Do you have a screenshot example of what you mean?  Do you mean the buddy list or listed in a multi-user chat window?

**Comment by cyberalex4life** [comment]
![buddy list_002](https://cloud.githubusercontent.com/assets/2423189/9021291/22985366-3844-11e5-8522-375dba7aa5d5.jpg)
![buddy list_003](https://cloud.githubusercontent.com/assets/2423189/9021292/2430a764-3844-11e5-8a6f-1560175ea7ad.jpg)

**Comment by cyberalex4life** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/2423189/9021300/66378fb0-3844-11e5-898b-8053ddfaea89.jpg)

**Comment by cyberalex4life** [comment]
It's a huge list in pidgin, and I only have 6 friends

**Comment by jgeboski** [comment]
To confirm, you have removed the account from Pidgin, and added it again, yes?

**Comment by cyberalex4life** [comment]
yup

**Comment by jgeboski** [comment]
Can you send me a [debugging](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs) log?

**Comment by cyberalex4life** [comment]
Log: http://ix.io/k3E
Backtrace: http://ix.io/k3F

**Comment by EionRobb** [comment]
That second one isn't a backtrace, but since there's no crashing its not needed anyway :)

"friendship_status":"ARE_FRIENDS"   appears for your 6 friends, and "friendship_status":"CAN_REQUEST"   on the rest

**Comment by EionRobb** [comment]
Oh, bugger, you should probably change your Skype password now too.... unfortunately I left that in the Skype plugin debug logs still :(

**Comment by cyberalex4life** [comment]
can you make them dissapear?

**Comment by cyberalex4life** [comment]
Obtaining a GDB Backtrace
$ PURPLE_UNSAFE_DEBUG=1 PURPLE_VERBOSE_DEBUG=1 gdb \
    -ex 'handle SIGPIPE nostop noprint pass' \
    -ex "set breakpoint pending on" \
    -ex "set pagination off" \
    -ex run -ex bt \
    --args pidgin --debug

**Comment by jgeboski** [comment]
Working on a patch now.

**Comment by jgeboski** [comment]
This has been fixed as of [600f41974cb3](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/600f41974cb3).  The fix will appear in the next release.

**Comment by cyberalex4life** [comment]
I changed almost all password I know (I was planning to)

**Comment by cyberalex4life** [comment]
Hi, this bug is on again on your latest release....
