### ISSUE TITLE
Wiki *nix instructions need updating.

### ISSUE THREAD

**Issue by mstargard** [jgeboski/purple-facebook#69]
I'm getting 404 errors on the URL

http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_14.04/./Packages

It looks like the jgeboski directory is empty. Were these files moved elsewhere?

Thanks,
M.

**Comment by jgeboski** [comment]
This is a temporary issue with OBS, and out of my control.  I will leave this open until the issue has been resolved.

**Comment by jgeboski** [comment]
References for people interested in the status:
  - https://github.com/openSUSE/obs-build/pull/175
  - http://lists.opensuse.org/archive/opensuse-buildservice/2015-07/msg00023.html

**Comment by pochy-ja** [comment]
The problem is solved 4 hours ago, but I had to re-add the Release.key because it was changed, but now works well.

**Comment by jgeboski** [comment]
The repository has been rebuilt.  Everything should be work as intended now.
