### ISSUE TITLE
Loging in when 2-factor is in use ?

### ISSUE THREAD

**Issue by DrYak** [jgeboski/purple-facebook#7]
What's the proper procedure to log in when 2 factor is in use ?

Application specific passwords don't seem to work.

Instead I log-in once with the website password.

Pidgin then shows a message box telling me : "Login approvals are on. Expect an SMS shortly with a code to use for log in (406)"

SMS arrives "Use {a 6 digit number} as your password for Facebook Messenger for Android".

But with that password I only get an error message:

"<data>:1:1048577: Parse error: scanner: unterminated string constant"

**Comment by jgeboski** [comment]
Application specific passwords should be working.  That is how I am logging in anyways.  I would really prefer not to support two-factor authentication within the plugin.  It is not only something else to maintain, but it is "insecure" given the support of application specific passwords.

> ":1:1048577: Parse error: scanner: unterminated string constant"

Is this the error you get from the SMS code or the application password?

**Comment by fangfufu** [comment]
You should create an app password at https://www.facebook.com/settings?tab=security&section=per_app_passwords&view

**Comment by DrYak** [comment]
> Is this the error you get from the SMS

Yes, the Pase error is when I use the 6-digit code from the SMS.

The application password fails with a plain and simple 

> Invalid username or password (401)

(i'm just using my username. No suffix attached, no "@facebook.com" like the older facebook plugin by eionrobb, nor "@chat.facebook.com" like the soon-to-be-removed Facebook's XMPP gateway)

The same application password works flawlessly using the XMPP gateway.

> You should create an app password 

I know, I have one for this pidgin. It works with XMPP, but fails with the purple-facebook pluging.

**Comment by jgeboski** [comment]
Try generating a different application password?

**Comment by DrYak** [comment]
> Try generating a different application password?

Hum, this time it brings me back to the parser error:

> &lt;data&gt;:1:1048577: Parse error: scanner: unterminated string constant

(Apparently, facebook doesn't like when an application password is already being in use, like by another pidgin plugin)

**Comment by jgeboski** [comment]
Could you please provide a [debug](https://github.com/jgeboski/purple-facebook#debugging) log containing the error and prior request(s)?

**Comment by jgeboski** [comment]
Closing due to lack of reply.  Reopen with the requested information if this issue is still present.

**Comment by DrYak** [comment]
Sorry, I hadn't have time to do more test before.

After running `update.sh` today (to update and patch the files from pidgin mercurial), everything works as it should. I suspect that I've somehow managed to have bad/corrupted/out-dated/out-of-sync in my pidgin directory. My fault indeed.

No need to reopen the bug. I'm replying only so other people with the same strange message know that they need to double check their pidgin subdirectory and maybe re-run `update.sh`.

**Comment by ceribik** [comment]
Would be nice if you mentioned the need to use an app-specific password in the pidgin error message.

**Comment by dequis** [comment]
The error message comes directly from facebook's server, we didn't write it, so we can't add more details to it.

**Comment by billyjbryant** [comment]
Now that Facebook has deprecated App Passwords, what are the solutions that work to log in when using MFA?

**Comment by Nardol** [comment]
> Now that Facebook has deprecated App Passwords, what are the solutions that work to log in when using MFA?

Make the account less secure by disabling 2FA... Or not connecting using Purple Facebook anymore.
I fount [this question on Superuser](https://superuser.com/questions/281134/pidgin-and-facebook-two-factor-authentication) but the proposed solution did not work for me.
