### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by danielb2** [jgeboski/purple-facebook#71]
Worked fine until a few days ago, but now I'm not able to see any of my facebook contacts.

As far as I can tell, this is the only output from the logs that appears like it's an issue

```                         │
08:40:13 jabber: Got a result iq with id purple20f9c3be
-8....@chat.facebook.com instead of expected
o...@chat.facebook.com
Unhandled IQ with id purple20f9c3be
util: Writing file accounts.xml to directory
/home/daniel/.purple
```

**Comment by jgeboski** [comment]
This plugin does not work over Jabber.  You are still using the old method.  Please see the [wiki](https://github.com/jgeboski/purple-facebook/wiki).

**Comment by danielb2** [comment]
Hah, I thought the "jabber' looked off, but I didn't think to double-check the account. Somehow this plugin got disabled and the old one enabled again. Hm!

thanks :)
