### ISSUE TITLE
Feature request - link to images in conversation

### ISSUE THREAD

**Issue by MikeTango** [jgeboski/purple-facebook#73]
Hi, 

could you implement a feature that, instead of saying *non-displayable attachments*, will show you a direct link to the image that was sent by the other party? The old XMPP would do that, and i hate going to the fb site, that's why i'm using your plugin for pidgin :)

**Comment by jgeboski** [comment]
This is already on the TODO (#9).  I will say, I started poking at this yesterday and today, and it certainly not as trivial as I thought it would be.

**Comment by MikeTango** [comment]
Oh, i read the TODO, should learn2read more closely. MEDIA. Thanks for 
the work.


Am 26.07.2015 um 21:57 schrieb James Geboski:
