### ISSUE TITLE
[pidgin] User connected notification shows facebook logo instead of user avatar

### ISSUE THREAD

**Issue by uosiu** [jgeboski/purple-facebook#74]
When remote user logs into facebook, Pidgin displays desktop notification that user is online.
Buddy list entries show users avatars, but notifications doesn't.

Pidgin 2.10.9-0ubuntu3.2 + purple_facebook from commit f2de0776b1f308f591bc63964517599ef1ec964a

**Comment by jgeboski** [comment]
What?

**Comment by unixasaurusrex** [comment]
I'm guessing the issue is the senders profile picture is not showing up in the notification.

**Comment by EionRobb** [comment]
This plugin doesn't provide notifcations, you'll want to lodge an issue with the plugin that's providing the notifications

**Comment by uosiu** [comment]
1) Plugin provide avatars for Pidgin's buddy list.
2) Pidgin shows notifications when buddy is online/offline
3) For example, when XMPP buddy shows as online, I can see "John Doe is online" and his avatar.
4) When facebook buddy shows as online, I can see "John Doe is online" and facebook logo instead of his profile picture.
![zrzut ekranu z 2015-07-29 08 33 39](https://cloud.githubusercontent.com/assets/1623893/8951349/347a2ca4-35cd-11e5-9871-3c6533c6959f.png)

**Comment by EionRobb** [comment]
No, Pidgin doesn't show any notifications, these are handled by another 3rd party plugin (probably libnotify in your case).  You'll need to try and sort out why that's happening with them
