### ISSUE TITLE
Windows binaries?

### ISSUE THREAD

**Issue by fullinterest** [jgeboski/purple-facebook#75]
Is it possible to have the lastest windows dll, I tried to compile, but I got some error

```
"../../../../../win32-dev/pidgin-2.10.11/libpurple/win32/rules.mak:4 : la recette pour la cible « marshal.o » a échouée
make[1]: *** [marshal.o] Erreur 1
make[1] : on quitte le répertoire « /cygdrive/d/pidgin_dev_root/purple-facebook-7c454f51b56b/pidgin/libpurple/protocols/facebook »
Makefile.mingw:59 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2"
```

**Comment by jgeboski** [comment]
Could you provide the entire make log?

**Comment by fullinterest** [comment]
$ make -f Makefile.mingw install
cd pidgin/libpurple/protocols/facebook && mkdir -p ../../../../win32-install-dir/plugins
make -C pidgin/libpurple/protocols/facebook -f Makefile.mingw install PURPLE_VERSION="2.10.11" PIDGIN_TREE_TOP="../../../../../win32-dev/pidgin-2.10.11" WIN32_DEV_TOP="../../../../../win32-dev/pidgin-2.10.11/.." PLUGIN_TOP="pidgin/libpurple/protocols/facebook" PURPLE_TOP="../../../../../win32-dev/pidgin-2.10.11/libpurple" PURPLE_INSTALL_PLUGINS_DIR="../../../../win32-install-dir/plugins" GPLUGIN_TOP="." GTK_TOP="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8" GTK_BIN="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/bin" GLIB_GENMARSHAL="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/bin/glib-genmarshal" JSON_GLIB_TOP="../../../../../win32-dev/pidgin-2.10.11/../json-glib-0.14"
make[1] : on entre dans le répertoire « /cygdrive/d/pidgin_dev_root/purple-facebook-7c454f51b56b/pidgin/libpurple/protocols/facebook »
gcc.exe -include purple-compat.h -Wno-unused-variable -Wno-unused-but-set-variable -O2 -Wall -Waggregate-return -Wcast-align -Wdeclaration-after-statement -Werror-implicit-function-declaration -Wextra -Wno-sign-compare -Wno-unused-parameter -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wundef -Wstack-protector -fwrapv -fno-strict-overflow -Wno-missing-field-initializers -Wformat-security -fstack-protector-all --param ssp-buffer-size=1 -pipe -mms-bitfields -g  -DPACKAGE_NAME=\"purple-facebook\" -DPACKAGE_TARNAME=\"purple-facebook\" -DPACKAGE_VERSION=\"7c454f51b56b\" -DPACKAGE_STRING=\"purple-facebook\ 7c454f51b56b\" -DPACKAGE_BUGREPORT=\"https://github.com/jgeboski/purple-facebook/issues\" -DPACKAGE_URL=\"https://github.com/jgeboski/purple-facebook\" -DPACKAGE=\"purple-facebook\" -DVERSION=\"7c454f51b56b\" -DPURPLE_PLUGINS -DHAVE_CYRUS_SASL -DHAVE_CONFIG_H -DWIN32_LEAN_AND_MEAN -I../../../../include -I../../../../pidgin -I../../../../pidgin/libpurple -I. -I../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/include -I../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/include/glib-2.0 -I../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/lib/glib-2.0/include -I../../../../../win32-dev/pidgin-2.10.11/../json-glib-0.14/include/json-glib-1.0 -I../../../../../win32-dev/pidgin-2.10.11/libpurple -I../../../../../win32-dev/pidgin-2.10.11/libpurple/win32 -I. -I../../../../../win32-dev/pidgin-2.10.11 -o marshal.o -c marshal.c
../../../../../win32-dev/pidgin-2.10.11/libpurple/win32/rules.mak:4 : la recette pour la cible « marshal.o » a échouée
make[1]: *** [marshal.o] Erreur 1
make[1] : on quitte le répertoire « /cygdrive/d/pidgin_dev_root/purple-facebook-7c454f51b56b/pidgin/libpurple/protocols/facebook »
Makefile.mingw:65 : la recette pour la cible « install » a échouée
make: *** [install] Erreur 2

**Comment by fullinterest** [comment]
Like that?

**Comment by jgeboski** [comment]
Try: `make -f Makefile.mingw clean install`

**Comment by fullinterest** [comment]
$ make -f Makefile.mingw clean install
make -C pidgin/libpurple/protocols/facebook -f Makefile.mingw clean PURPLE_VERSION="2.10.11" PIDGIN_TREE_TOP="../../../../../win32-dev/pidgin-2.10.11" WIN32_DEV_TOP="../../../../../win32-dev/pidgin-2.10.11/.." PLUGIN_TOP="pidgin/libpurple/protocols/facebook" PURPLE_TOP="../../../../../win32-dev/pidgin-2.10.11/libpurple" PURPLE_INSTALL_PLUGINS_DIR="../../../../win32-install-dir/plugins" GPLUGIN_TOP="." GTK_TOP="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8" GTK_BIN="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/bin" GLIB_GENMARSHAL="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/bin/glib-genmarshal" JSON_GLIB_TOP="../../../../../win32-dev/pidgin-2.10.11/../json-glib-0.14"
make[1] : on entre dans le répertoire « /cygdrive/d/pidgin_dev_root/purple-facebook-7c454f51b56b/pidgin/libpurple/protocols/facebook »
rm -f marshal.o api.o data.o facebook.o http.o json.o mqtt.o thrift.o util.o ../../http.o ../../purple-socket.o
rm -f libfacebook.dll
make[1] : on quitte le répertoire « /cygdrive/d/pidgin_dev_root/purple-facebook-7c454f51b56b/pidgin/libpurple/protocols/facebook »
cd pidgin/libpurple/protocols/facebook && mkdir -p ../../../../win32-install-dir/plugins
make -C pidgin/libpurple/protocols/facebook -f Makefile.mingw install PURPLE_VERSION="2.10.11" PIDGIN_TREE_TOP="../../../../../win32-dev/pidgin-2.10.11" WIN32_DEV_TOP="../../../../../win32-dev/pidgin-2.10.11/.." PLUGIN_TOP="pidgin/libpurple/protocols/facebook" PURPLE_TOP="../../../../../win32-dev/pidgin-2.10.11/libpurple" PURPLE_INSTALL_PLUGINS_DIR="../../../../win32-install-dir/plugins" GPLUGIN_TOP="." GTK_TOP="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8" GTK_BIN="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/bin" GLIB_GENMARSHAL="../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/bin/glib-genmarshal" JSON_GLIB_TOP="../../../../../win32-dev/pidgin-2.10.11/../json-glib-0.14"
make[1] : on entre dans le répertoire « /cygdrive/d/pidgin_dev_root/purple-facebook-7c454f51b56b/pidgin/libpurple/protocols/facebook »
gcc.exe -include purple-compat.h -Wno-unused-variable -Wno-unused-but-set-variable -O2 -Wall -Waggregate-return -Wcast-align -Wdeclaration-after-statement -Werror-implicit-function-declaration -Wextra -Wno-sign-compare -Wno-unused-parameter -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wundef -Wstack-protector -fwrapv -fno-strict-overflow -Wno-missing-field-initializers -Wformat-security -fstack-protector-all --param ssp-buffer-size=1 -pipe -mms-bitfields -g  -DPACKAGE_NAME=\"purple-facebook\" -DPACKAGE_TARNAME=\"purple-facebook\" -DPACKAGE_VERSION=\"7c454f51b56b\" -DPACKAGE_STRING=\"purple-facebook\ 7c454f51b56b\" -DPACKAGE_BUGREPORT=\"https://github.com/jgeboski/purple-facebook/issues\" -DPACKAGE_URL=\"https://github.com/jgeboski/purple-facebook\" -DPACKAGE=\"purple-facebook\" -DVERSION=\"7c454f51b56b\" -DPURPLE_PLUGINS -DHAVE_CYRUS_SASL -DHAVE_CONFIG_H -DWIN32_LEAN_AND_MEAN -I../../../../include -I../../../../pidgin -I../../../../pidgin/libpurple -I. -I../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/include -I../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/include/glib-2.0 -I../../../../../win32-dev/pidgin-2.10.11/../glib-2.28.8/lib/glib-2.0/include -I../../../../../win32-dev/pidgin-2.10.11/../json-glib-0.14/include/json-glib-1.0 -I../../../../../win32-dev/pidgin-2.10.11/libpurple -I../../../../../win32-dev/pidgin-2.10.11/libpurple/win32 -I. -I../../../../../win32-dev/pidgin-2.10.11 -o marshal.o -c marshal.c
../../../../../win32-dev/pidgin-2.10.11/libpurple/win32/rules.mak:4 : la recette pour la cible « marshal.o » a échouée
make[1]: *** [marshal.o] Erreur 1
make[1] : on quitte le répertoire « /cygdrive/d/pidgin_dev_root/purple-facebook-7c454f51b56b/pidgin/libpurple/protocols/facebook »
Makefile.mingw:65 : la recette pour la cible « install » a échouée
make: *** [install] Erreur 2

**Comment by jgeboski** [comment]
Is `pidgin/libpurple/protocols/facebook/marshal.c` empty?

**Comment by fullinterest** [comment]
It's the lastest release, this file is around ~6,67Ko (not empty then)

**Comment by jgeboski** [comment]
Does `/cygdrive/d/pidgin_dev_root/win32-dev/pidgin-2.10.11/libpurple/win32/rules.mak` exist?

**Comment by fullinterest** [comment]
Yes, it exist

"# Rules on how to make object files from various sources

%.o: %.c
	$(CC) $(CFLAGS) $(DEFINES) $(INCLUDE_PATHS) -o $@ -c $<

%.c: %.xs
	$(PERL) -MExtUtils::ParseXS -e 'ExtUtils::ParseXS::process_file(filename => "$<", output => "$@", typemap => "$(PURPLE_PERL_TOP)/common/typemap");'

%.o: %.rc
	$(WINDRES) -I$(PURPLE_TOP) -i $< -o $@

%.desktop: %.desktop.in $(wildcard $(PIDGIN_TREE_TOP)/po/*.po)
	LC_ALL=C $(PERL) $(INTLTOOL_MERGE) -d -u -c $(PIDGIN_TREE_TOP)/po/.intltool-merge-cache $(PIDGIN_TREE_TOP)/po $< $@"

**Comment by jgeboski** [comment]
I am running out of ideas.  Try removing `pidgin/libpurple/protocols/facebook/marshal.{c,h}`.  This will force `glib-genmarshal` to regenerate them.  I have just added a [patch](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/e1fa48ad1f89) upstream to have the `clean` target remove these.

This would be a great time to mention the [automated](https://ci.voidium.net/job/purple-facebook) builds.

**Comment by fullinterest** [comment]
Ohhhhh, best idea ever ^^
Could you add the link to the wiki in github?
Thanks to reply that fast to my question

**Comment by fullinterest** [comment]
I mean, a link like https://ci.voidium.net/job/purple-facebook/ to tell people there's automated builds

**Comment by jgeboski** [comment]
Step two of the [windows](https://github.com/jgeboski/purple-facebook/wiki/Installing-on-Windows) instructions links to the latest successful `libfacebook.dll`.  I have added a note to the wiki page about it.

**Comment by fullinterest** [comment]
Thanks about it, and thank you for making this plugin
