### ISSUE TITLE
"hg (mercurial) not found in PATH"

### ISSUE THREAD

**Issue by RomanSC** [jgeboski/purple-facebook#77]
Hey thanks for creating the plugin for this, especially that XMPP is now discontinued.

I'm trying to build using git and having issues building for Fedora 22 getting "hg (mercurial) not found in PATH" here:

user@localhost ~> cd purple-facebook/
user@localhost ~/purple-facebook> 
user@localhost ~/purple-facebook> sudo ./autogen.sh
hg (mercurial) not found in PATH
user@localhost ~/purple-facebook> 

Any idea what might be happening?

**Comment by jgeboski** [comment]
It is a pretty self-explanatory error message (or so I thought).  Install mercurial.

**Comment by RomanSC** [comment]
Cool, looks like I found all the correct dependencies you mentioned on the build guide except for that one. It's not running ./autogen.sh but then it get's to this and fails:

checking for GLIB... yes
checking for JSON... yes
checking for PURPLE... no
configure: error: Package requirements (purple        <  3) were not met:

No package 'purple' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PURPLE_CFLAGS
and PURPLE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Thanks for the quick reply and the help :+1:

**Comment by jgeboski** [comment]
Install the development version of libpurple.

**Comment by jgeboski** [comment]
The package is `libpurple-devel` in Fedora.

**Comment by RomanSC** [comment]
Yep, was able to find it with a dnf search only I ran "sudo dnf install pidgin-devel" after that it worked, was able to run "sudo make" and restarted pidgin, working great now!

I see in your guide you don't have "make install" after "make"

Is make install necessary?

**Comment by jgeboski** [comment]
It's there, it's just the next step.  There are two ways to install the plugin

**Comment by RomanSC** [comment]
Now that I think about it the formatting makes a lot of sense, I've always seen them listed right after another. 

Thanks again for the help!
