### ISSUE TITLE
Chat disconnects whole account

### ISSUE THREAD

**Issue by dahaic** [jgeboski/purple-facebook#78]
Hello, not sure about the whole issue [not well versed in the protocol], so I will describe it as user:

Was invited to chat by one friend, and one non-friend. After a while, non-friend left the chat, and after another while [not sure what triggered it, maybe my friend going offline?], I received system message  [into the chat window], and whole account crashed. Will update it with messages as soon as I reproduce it again :)

**Comment by dahaic** [comment]
Ok, so behaviour now is, that immediately after receiving message to that chat, it disconnects the account. Chat window contains this message:

The account has disconnected and you are no longer in this chat. You will automatically rejoin the chat when the account reconnects.

And "userlist" information was:
Failed to parse thread information

**Comment by jgeboski** [comment]
Could you sending me a [debugging](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs) log?

**Comment by t-animal** [comment]
It seems this happens, too, when a chat is renamed on facebook.

**Comment by jgeboski** [comment]
@t-animal see my previous comment.

**Comment by jgeboski** [comment]
Closing this due to lack of information.
