### ISSUE TITLE
Latest version marks all messages "seen" (on FB side) immediately

### ISSUE THREAD

**Issue by jaymzh** [jgeboski/purple-facebook#80]
Upgraded to the latest version last night, and when I got up this morning my phone saw all my messages as "seen"... 

[Potentially related: pidgin was set to 'away']

**Comment by jgeboski** [comment]
Yeah, this is a feature.  It can be disabled: Account Settings => "Advanced" Tab => Uncheck "Mark messages as read."

**Comment by fangfufu** [comment]
Can you set it so the thread gets marked as read after the user has typed in the input box?

**Comment by jaymzh** [comment]
Pidgin has a concept of "read" - it knows when I've switched to a tab. Why mark messages read I haven't possibly have seen? I'm away, the tab isn't selected, the name is still in blue (waiting message). I'm all for supporting "seen", but... this seems like buggy behavior.

**Comment by dequis** [comment]
>Pidgin has a concept of "read"

Pidgin (the GTK interface) does. Libpurple doesn't.

Nothing we can do, other than possibly adding the required APIs to libpurple3 (the next, unreleased, version). But that's way out of the scope of this project.

>Can you set it so the thread gets marked as read after the user has typed in the input box? 

That might actually work!

**Comment by fangfufu** [comment]
Pidgin has a concept of "user typing", right?

**Comment by EionRobb** [comment]
> > Pidgin has a concept of "read"
> Pidgin (the GTK interface) does.  Libpurple doesn't.
Checking purple_conversation_has_focus() and listening to the "conversation-updated" signal to see if the unread status has changed works well though (I do that in the skypeweb plugin)

**Comment by ZyperPL** [comment]
@jgeboski 
This is major issue, my girlfriend got angry because she thought that I'm reading but not answering to her messages!

**Comment by christophschw** [comment]
Did you follow jgeboski's instructions: Account Settings → "Advanced" Tab → Uncheck "Mark messages as read."?

**Comment by ZyperPL** [comment]
@christophschw This is not the solution. I still want the messages that I've seen marked as read. 
But why is it happening when I'm away? Is EionRobb's solution really impossible to implement?

**Comment by jgeboski** [comment]
Focused based marking has been implemented as of [3e818c95dfd9](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/3e818c95dfd9), and will appear in the next update.
