### ISSUE TITLE
How to add Persistent Notifications?

### ISSUE THREAD

**Issue by random6969** [jgeboski/purple-facebook#81]
I currently have Pidgin setup to "keep buddy list window on top always." 

Whenever anyone messages me, the chat window immediately pops up in front of whatever window i have open (chrome, for example). I like this because it lets me see new messages immediately.

Upon clicking anywhere on the current window, the Pidgin chat is sent to the background. Again, this is as expected.

My issue is that now if someone messages me, the chat window no longer pops up to the forefront. There is an occasional flash on the taskbar icon, but I rarely if ever notice it until minutes later.

What I would like is some way to set up Pidgin notifications so that when i click the current window (chrome for example) and Pidgin is sent to the background,any subsequent messages (from that sender or any other) will once again bring Pidgin's chatbox to the front.

P.S.: Sorry in advance if this is already a global option. I have tried messing around with the "message notification" plugin to no avail. Please help.

**Comment by EionRobb** [comment]
This is a general Pidgin question and nothing to do with the Facebook plugin
