### ISSUE TITLE
messages containing a hyperlink won't show up

### ISSUE THREAD

**Issue by christophschw** [jgeboski/purple-facebook#85]
If someone sends you a hyperlink and FB adds a preview of the link to the message, the message won't show up in Pidgin.

My version is 9e3520d6ec49.
Thanks for the fix!

**Comment by jgeboski** [comment]
Does removing the account from pidgin, and adding it again fix the issue?

**Comment by christophschw** [comment]
Yesss, it does! This was a quite fast workaround. Thanks.

**Comment by jgeboski** [comment]
This happens as the message queue needs to be recreated with the new parameters, which were introduced with the message attachment patch.  The plugin saves the queue identifier, and that needs to be cleared out in order for a new one to be created.  The easiest way to do this is to re-add the account to pidgin.

This is not geared towards you, but rather people who stumble upon this issue.  There is not any sort of backwards compatibility for this issue, and there will never be.  This plugin is still under heavy development, as it is merely a back-port of my GSoC work.  There is just no need for the plugin to start carrying around extra bloat when it is in a development stage.
