### ISSUE TITLE
Failure to connect - "Empty JSON data"

### ISSUE THREAD

**Issue by shlomif** [jgeboski/purple-facebook#86]
I am getting an "Empty JSON data" notice when I try to connect to Facebook using purple-facebook-9e3520d6ec49 . It started happening now. Please let me know if you need any more info. I should note that my username is "shlomi.fish".

**Comment by dequis** [comment]
Send jgeboski a [debug log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs)

**Comment by shlomif** [comment]
Apparently, this seems to have been a transient problem, because now it is working perfectly fine here (after I restarted my router). So I'm going to close this.

**Comment by jgeboski** [comment]
I have a feeling this is the exact same issue as #79.
