### ISSUE TITLE
account disabled, Invalid HTTP response code (401)

### ISSUE THREAD

**Issue by nekromoff** [jgeboski/purple-facebook#87]
probably some new FB setup blocking this plugin

**Comment by nekromoff** [comment]
(16:38:54) jabber: jabber_actions: have pep: NO
(16:38:54) account: Connecting to account xxxxxxxxxx
(16:38:54) connection: Connecting. gc = 0x7f431e49f8f0
(16:38:54) http: Performing new request 0x7f431e3967e0 to graph.facebook.com.
(16:38:54) dnsquery: Performing DNS lookup for graph.facebook.com
(16:38:54) dns: Successfully sent DNS request to child 4151
(16:38:54) dns: Got response for 'graph.facebook.com'
(16:38:54) dnsquery: IP resolved for graph.facebook.com
(16:38:54) proxy: Attempting connection to 66.220.158.19
(16:38:54) proxy: Connecting to graph.facebook.com:443 with no proxy
(16:38:54) proxy: Connection in progress
(16:38:54) proxy: Connecting to graph.facebook.com:443.
(16:38:54) proxy: Connected to graph.facebook.com:443.
(16:38:54) nss: subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=CA,C=US issuer=CN=DigiCert High Assurance CA-3,OU=www.digicert.com,O=DigiCert Inc,C=US
(16:38:54) nss: subject=CN=DigiCert High Assurance CA-3,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(16:38:54) nss: partial certificate chain
(16:38:54) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(16:38:54) certificate/x509/tls_cached: Checking for cached cert...
(16:38:54) certificate/x509/tls_cached: ...Found cached cert
(16:38:54) nss/x509: Loading certificate from /home/xxxxxxx/.purple/certificates/x509/tls_peers/graph.facebook.com
(16:38:54) certificate/x509/tls_cached: Peer cert matched cached
(16:38:54) nss/x509: Exporting certificate to /home/xxxxxxxxxx/.purple/certificates/x509/tls_peers/graph.facebook.com
(16:38:54) util: Writing file /home/xxxxx/.purple/certificates/x509/tls_peers/graph.facebook.com
(16:38:54) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=CA,C=US
(16:38:54) certificate: Successfully verified certificate for graph.facebook.com
(16:38:54) http: Request 0x7f431e3967e0 performed without success.
(16:38:54) connection: Connection error on 0x7f431e49f8f0 (reason: 16 description: Invalid HTTP response code (401))
(16:38:54) jabber: jabber_actions: have pep: NO
(16:38:54) account: Disconnecting account xxxxxxxxxxx (0x7f431da8ac20)
(16:38:54) connection: Disconnecting connection 0x7f431e49f8f0
(16:38:54) jabber: jabber_actions: have pep: NO
(16:38:54) connection: Destroying connection 0x7f431e49f8f0

**Comment by dequis** [comment]
Send jgeboski a full [debug log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs) following those instructions in the wiki.

**Comment by nekromoff** [comment]
sent

**Comment by jgeboski** [comment]
It is hard for me to say for sure with the leading information stripped.  What version of the plugin are you running?

**Comment by nekromoff** [comment]
i reinstalled the latest version and it works now

**Comment by jgeboski** [comment]
The wiki mentions nothing of `/etc/apt/sources.list`.

**Comment by nekromoff** [comment]
i know, but it should be the same format whether you use master
sources.lkist or your new custom-named file.

**Comment by jgeboski** [comment]
I can only assume it's a typo on your behalf.

**Comment by nekromoff** [comment]
okay, nevermind. it works now with the latest update.

**Comment by jgeboski** [comment]
There was no update.

**Comment by nekromoff** [comment]
surely there was:
https://github.com/jgeboski/purple-facebook/commits/master

**Comment by jgeboski** [comment]
That has *nothing* to do with your apt config.

**Comment by nekromoff** [comment]
i compiled it since apt-get complained about malformed url
