### ISSUE TITLE
Debian packaging failure due to path issues

### ISSUE THREAD

**Issue by krautos** [jgeboski/purple-facebook#90]
Hi there, just tried to build a package with the debian that's included and prepare for PPA upload. When i run it with pdebuild in an clean enviroment i get issues:

    dh_autoreconf
    aclocal: warning: couldn't open directory 'm4': No such file or directory
    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
    libtoolize: copying file `build-aux/ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: copying file `m4/ltoptions.m4'
    libtoolize: copying file `m4/ltsugar.m4'
    libtoolize: copying file `m4/ltversion.m4'
    libtoolize: copying file `m4/lt~obsolete.m4'
    configure.ac:29: installing 'build-aux/compile'
    configure.ac:33: installing 'build-aux/config.guess'
    configure.ac:33: installing 'build-aux/config.sub'
    configure.ac:27: installing 'build-aux/install-sh'
    configure.ac:27: installing 'build-aux/missing'
    Makefile.am: installing './INSTALL'
    configure.ac:91: error: required file 'pidgin/libpurple/protocols/facebook/Makefile.in' not found
    Makefile.am:2: error: required directory ./pidgin/libpurple/protocols/facebook does not exist
    autoreconf: automake failed with exit status: 1
    dh_autoreconf: autoreconf -f -i returned exit code 1
    make: *** [build] Error 2
    dpkg-buildpackage: error: debian/rules build gave error exit status 2
    E: Failed autobuilding of package
    I: unmounting dev/pts filesystem
    I: unmounting run/shm filesystem
    I: unmounting proc filesystem
    I: cleaning the build env 
    I: removing directory /var/cache/pbuilder/build//25177 and its subdirectories

Could give you a hand on the packaging as i won't install it unless packaged ;) Thx!

**Comment by jgeboski** [comment]
You need to `./update.sh` first, and then create a source tarball for dpkg.  There is also absolutely no need for a PPA, when I provide debian packages.  Please see the [wiki](https://github.com/jgeboski/purple-facebook/wiki/Installing-on-*NIX#debian-and-ubuntu).
