### ISSUE TITLE
Build error: purple-facebook on Centos 6

### ISSUE THREAD

**Issue by wa7qzr** [jgeboski/purple-facebook#91]
The purple-facebook-9e3520d6ec49 I downloaded came w/no "configure" script. Ran autogen.sh

Got an initial error: aclocal: unrecognized option -- `-Im4'

Found this in "Makefile.am":
ACLOCAL_AMFLAGS = -Im4
changed to:
ACLOCAL_AMFLAGS = -I m4

Now, it gen's this:
autoreconf: running: /usr/bin/autoconf --force
configure.ac:18: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

I'm stuck at this point.

**Comment by jgeboski** [comment]
I can only assume the first error is from an old version of `aclocal`.  As for the missing `m4_esyscmd_s` macro, it was introduced in autoconf-2.64, and CentOS 6 has autoconf-2.63.  I really have no interest in supporting software, which was released over six years ago.  I have added a check as of 7443c55, which checks for autoconf-2.64.

You could try using `./configure` with one of the [release](https://github.com/jgeboski/purple-facebook/releases) tarballs.  However, it appears you are going to run into issues with json-glib being out of date as well.
