### ISSUE TITLE
Release Key URL got changed

### ISSUE THREAD

**Issue by makernaren** [jgeboski/purple-facebook#93]
http://download.opensuse.org/repositories/home:/jgeboski/<version>/Release.key - This is the actual URL given by you in the wiki page. But above url is not working ( for ubuntu 14.04 ). The following does : 
http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_<version>/Release.key
Edit : For release key and the repository as well

**Comment by jgeboski** [comment]
This broke about three weeks ago.  See #18.
