### ISSUE TITLE
Adium Port

### ISSUE THREAD

**Issue by xTear** [jgeboski/purple-facebook#95]
is it possible to port this plugin to adium?

**Comment by jgeboski** [comment]
It is possible, but I will likely not be the one doing it, as I have very little experience with Mac development.  There is an [issue](https://trac.adium.im/ticket/16921) open for this plugin if you are interested.  I am closing this issue, as I have no intentions of taking this task on directly.  If someone needs things patched to make this happen, I am willing to work with them to get the ball rolling on Mac support.

**Comment by RobFog** [comment]
This would be great.
