### ISSUE TITLE
How to get newest code?

### ISSUE THREAD

**Issue by ZyperPL** [jgeboski/purple-facebook#96]
Is it possible to update a local repo directly from https://hg.pidgin.im/soc/2015/jgeboski/facebook ?
It is hard to wait for new commits on GitHub when you want newest changes.
Should I change some line in update.sh or it's not possible without further modifications?

**Comment by jgeboski** [comment]
A week (at max) is hard for you to wait?  Jeez.

Anyways, there is no easy way to update directly from mercurial.  Updates typically require the local patches to be updated as well.  Sometimes, if the changes upstream are trivial, it is easy to just amend the hash in `VERSION`.  However, that is usually not the case, as I often push tons of new stuff which requires modification of the local patches.

Also note, absolutely **no** support is offered if you change the hash in `VERSION`.  By far the easiest solution is to let me work, and you just be patient.
