### ISSUE TITLE
Synced outgoing messages all have incorrect time stamp.

### ISSUE THREAD

**Issue by TJZAwsum** [jgeboski/purple-facebook#97]
When an outgoing message is sent via a browser or phone or other Facebook medium, the message syncs with the Pidgin chat window. However, these messages all have incorrect time stamps. Every one of them has a time stamp of (12/31/1969 4:00:00 PM).

Really stoked about this message syncing feature regardless. Good work!

**Comment by jgeboski** [comment]
This has been fixed as of [02346252cb7e](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/02346252cb7e), and will appear in the next release.
