### ISSUE TITLE
Thumbnail url

### ISSUE THREAD

**Issue by Mariglianov** [jgeboski/purple-facebook#98]
Hello url and message with a thumbnail, still does not work.
No message is received on Pidgin.

**Comment by jgeboski** [comment]
Which plugin [version](https://github.com/jgeboski/purple-facebook/wiki#how-do-i-check-the-current-plugin-version)?

**Comment by Mariglianov** [comment]
The plugin version is : 20150811~635a32f~3d30d24fdbef~9
On linux.

**Comment by dequis** [comment]
@jgeboski guessing here, maybe it's a matter of re-creating the queue with the new settings to receive the new message types?

@Mariglianov in the pidgin accounts window, delete this one and add it again. Reconnect and try again, hopefully that helps.

**Comment by Mariglianov** [comment]
@dequis Yes it worked, thanks mate :+1:

**Comment by dequis** [comment]
Neat. Added a [FAQ entry](https://github.com/jgeboski/purple-facebook/wiki#after-upgrading-the-plugin-some-features-that-should-work-like-image-thumbnails-seem-to-be-broken) for this.

**Comment by jgeboski** [comment]
It is worth noting my last comment in #85.
