### ISSUE TITLE
Messages appear every login

### ISSUE THREAD

**Issue by christophschw** [jgeboski/purple-facebook#99]
If you disable "Mark messages as read" you'll get every formerly unread message as new message. Version 3d30d24fdbef

But great new feature btw!

**Comment by dequis** [comment]
This sounds like it's by design, though.

**Comment by christophschw** [comment]
It's not 100 percent clear what I mentioned: You'll get this message every login until the message is marked as "read"

**Comment by jgeboski** [comment]
This is a limitation of the `PurpleAccountOption` interface in libpurple.  There is no way to have the option depend on the state of another option.  I have little control over this, especially in libpurple2, the version you are using.  It is pretty simple though, make sure the mark as read option is enabled.
